NewStaffRoles::
    db "    1998 STAB     "
    db "     VEILEDER     " 
    db "     REGISSØR     "
    db "  MANUSFORFATTER  "
    db "   PROGRAMMERER   "
    db " KARAKTERDESIGNER "
    db "    KOMPONIST     "
    db "     GRAFIKK      "
    db "  TEKNISK STØTTE  "
    db "  NORSK VERSJON   " ;ops. DAN OWSEN får plutselig denne crediten og. 
    db " SÆRLIG TAKK TIL  "

DebugStaffRoles::
    db "    FEILSØKING    "

OriginalStaffRoles::
    db "    1993 STAB     "
    db "FANGEHULLDESIGNER "
    db "   ILLUSTRATØR    "
    db "    PRODUSENT     "
    db "  ANSV PRODUSENT  "
    db "                  "

NewStaffPeople::
    db "                  "
    db "  TAKASHI TEZUKA  "
    db "YOSINORI TUTIYAMA "
    db " NOBUO MATSUMIYA  "
    db "    EIJI NOTO     "
    db "   KIYOSHI KODA   "
    db "SIGEHIRO KASAMATU "
    db "  MIKIO MISHIMA   "
    db "   KYOKO KIMURA   "
    db "   YUICHI OZAKI   "
    db "   KEIKO IZAWA    "
    db "   N KOGANEZAWA   "
    db "TOBIAS V  LANGHOFF"
    db "JULIUS V  LANGHOFF"
    db " A  K-GRENASBERG  "
    db "  AKIYA SAKAMOTO  "
    db " R&D2 DEBUG STAFF "
    db " SUPER MARIO CLUB "
    db "YASUHISA YAMAMURA "
    db "  KENSUKE TANABE  "
    db " YOSHIAKI KOIZUMI "
    db "  KAZUAKI MORITA  "
    db "TAKAMITSU KUZUHARA"
    db " MASANAO ARIMOTO  "
    db "  SHIGEFUMI HINO  "
    db "  KAZUMI TOTAKA   "
    db "  MINAKO HAMANO   "
    db "  KOZUE ISHIKAWA  "
    db "  YOUICHI KOTABE  "
    db "    DAN OWSEN     "
    db " TOSHIHIKO NAKAGO "
    db "    KOJI KONDO    "
    db " TOMOAKI KUROUME  "
    db " MASAICHI OKUMURA "
    db "    KANAE WADA    "
    db " SHIGERU MIYAMOTO "
    db " HIROSHI YAMAUCHI "
    db "THE  END          "
