Dialog190::
    db "Høøh? Hvem er   "
    db "denna mistenke- "
    db "lige jyplingen?!"
    db "Okei, gutta, la "
    db "oss kvitte oss  "
    db "med'n!@"
;   db "Ennh?  Who's    "
;   db "this suspicious-"
;   db "looking runt?!  "
;   db "Okay boys, let's"
;   db "get ridda him!@"

Dialog191::
    db "Du må være en   "
    db "leiemorder sendt"
    db "av Madam Mjau-  "
    db "Mjau for å redde"
    db "kjøteren! Du kom"
    db "hit for å ta    "
    db "meg, men det er "
    db "jeg som kommer  "
    db "til å ta deg!!@"
;   db "You must be an  "
;   db "assassin sent by"
;   db "Madam MeowMeow  "
;   db "to rescue the   "
;   db "mutt!  You came "
;   db "here to get me, "
;   db "but it is I who "
;   db "will get you!!@"

Dialog192::
    db "Å, #####. Jeg   "
    db "kommer også ofte"
    db "til denne lands-"
    db "byen for å syn- "
    db "ge! Det virker  "
    db "som om nesten   "
    db "alle elsker min "
    db "«Balladen om    "
    db "Vindfisken»!    "
    db "#####, hva er   "
    db "din favoritt-   "
    db "sang?@"
;   db "Oh, #####.  I   "
;   db "often come to   "
;   db "this village to "
;   db "sing, too!  It  "
;   db "seems that just "
;   db "about everyone  "
;   db "loves my 'Ballad"
;   db "of the Wind     "
;   db "Fish!'  #####,  "
;   db "what is your    "
;   db "favorite song?@"

Dialog193::
    db "Vær så snill å  "
    db "aldri glemme    "
    db "denne sangen_…  "
    db "eller meg_…@"
;   db "Please, don't   "
;   db "ever forget this"
;   db "song...or me...@"

Dialog194::
    db "Takk for alt!   "
    db "#####, du er den"
    db "snilleste gutten"
    db "jeg kjenner. Én "
    db "gang ønsket jeg "
    db "meg noe fra     "
    db "Vindfisken_…    "
    db "Hva ønsket var? "
    db "Det var_…       "
    db "Nei, det er en  "
    db "hemmelighet!@"
;   db "Thank you for   "
;   db "everything!     "
;   db "#####, you are  "
;   db "the kindest boy "
;   db "I know.  One day"
;   db "I made a wish to"
;   db "the Wind Fish..."
;   db "What was the    "
;   db "wish?  It was..."
;   db "No, it's secret!@"

Dialog195::
    db "#####, én dag   "
    db "kommer du til å "
    db "forlate denne   "
    db "øya_… Jeg kan   "
    db "føle det i mitt "
    db "hjerte_… Lov meg"
    db "at du aldri     "
    db "glemmer meg_…   "
    db "Ellers vil jeg  "
    db "aldri tilgi deg!@"
;   db "#####, some day "
;   db "you will leave  "
;   db "this island...  "
;   db "I just know it  "
;   db "in my heart...  "
;   db "...Don't ever   "
;   db "forget me... If "
;   db "you do, I'll    "
;   db "never forgive   "
;   db "you!@"

Dialog196::
    db "... ... ... ... "
    db "Den virker helt "
    db "oppslukt av     "
    db "Marins sang!@"
;   db "... ... ... ... "
;   db "It seems to be  "
;   db "totally absorbed"
;   db "in Marin's song!@"

Dialog197::
    db "De sier at      "
    db "«Balladen om    "
    db "Vindfisken» er  "
    db "sang om oppvåk- "
    db "ning. Jeg lurer "
    db "på om Vindfisken"
    db "vil oppfylle    "
    db "ønsket mitt hvis"
    db "han våkner?@"
;   db "They say the    "
;   db "'Ballad of the  "
;   db "Wind Fish' is a "
;   db "song of awaken- "
;   db "ing.  I wonder, "
;   db "if the Wind Fish"
;   db "wakes up, will  "
;   db "he make my wish "
;   db "come true?@"

Dialog198::
    db "Hæ? Vil du at   "
    db "jeg skal bli med"
    db "inn dit? Nei,   "
    db "jeg tror nok jeg"
    db "venter her ute_…"
    db "Vær forsiktig,  "
    db "#####!@"
;   db "Eh?  You want me"
;   db "to go in there? "
;   db "No, I think I'll"
;   db "wait out here..."
;   db "Take care of    "
;   db "yourself, #####!@"

Dialog199::
    db "Åååå! Åååå, du  "
    db "er en slem gutt,"
    db "#####!@"
;   db "Ahhh!  Ahhh, you"
;   db "are a bad boy,  "
;   db "#####!@"

Dialog19A::
    db "Her er en liten "
    db "bonusbehandling!"
    db "Se, hjertene    "
    db "dine er fulle!@"
;   db "Here's some     "
;   db "bonus treatment!"
;   db "Behold!  Your   "
;   db "Hearts are full!@"

Dialog19B::
    db "Ja, jeg err Sjur"
    db "Donavitch! Hav- "
    db "frushtatuen nede"
    db "ved den bukt er "
    db "mitt mesterwerk!"
    db "Når sant skal   "
    db "sies, err den   "
    db "shtatue ikke    "
    db "fertig_… Den    "
    db "kunst, den_… err"
    db "vanskelig for   "
    db "deg å forstå,   "
    db "err den ikke?@"
;   db "Ya, I am Schule "
;   db "Donavitch!  Zee "
;   db "mermaid statue  "
;   db "by zee bay iz my"
;   db "masterpiece! ..."
;   db "To tell you zee "
;   db "truth, zis werk "
;   db "iz not complete!"
;   db "Zee art, it'z..."
;   db "difficult for   "
;   db "you to grasp, iz"
;   db "it not?@"

Dialog19C::
    db "  DEN SØRGENDE  "
    db "     HAVFRUE    "
    db "     Av SJUR    "
    db "?_… Et skjell   "
    db "mangler her_…@"
;   db "  THE MOURNING  "
;   db "     MERMAID    "
;   db "    By SCHULE   "
;   db "? ...A scale is "
;   db "missing...@"

Dialog19D::
    db "Sneglehuset@"
;    db "Seashell Mansion@"

Dialog19E::
    db "Inngang til     "
    db "  Yahara <right>@"
;    db "Entrance to     "
;    db "  Yarna Desert <right>@"

Dialog19F::
Dialog1A0::
    db "  Den mystiske  "
    db "     skogen     "
    db " (Den er bitte- "
    db "  litt mystisk)@"
;   db "   Mysterious   "
;   db "     Forest     "
;   db " (It's a little "
;   db " bit mysterious)@"

Dialog1A1::
    db "Våger du deg ned"
    db "de strømmende   "
    db "stryk på flåte? "
    db "Gå videre til   "
    db "kontoret med en "
    db "gang, takk!@"
;    db "Do you want to  "
;    db "challenge the   "
;    db "river rapids on "
;    db "a raft?  Proceed"
;    db "to the office at"
;    db "once, please!@"

Dialog1A2::
    db "Øst <right>  Ulele-   "
    db "       sletta   "
    db "Lenger øst      "
    db "       Snutebu@"
;   db "East <right> Ukuku    "
;   db "       Prairie  "
;   db "Farther East    "
;   db "  Animal Village@"

Dialog1A3::
    db "   Tindeggen   @"
;    db "Mt. Tamaranch   @"

Dialog1A4::
    db "<right> Halehula      "
    db "<down> Tromlekysten @"
;    db "<right> Tail Cave     "
;    db "<down> Toronbo Shores@"

Dialog1A5::
    db "<right> Symresumpen   "
    db "<down> Den mystiske  "
    db "  skogen@"
;    db "<right> Gopongo Swamp "
;    db "<down> Mysterious    "
;    db "  Forest@"

Dialog1A6::
    db "Vær oppmerksom  "
    db "på sprekker i   "
    db "gulvet! Tunge   "
    db "personer burde  "
    db "ikke stå på dem!@"
;    db "Beware of floors"
;    db "with cracks!  A "
;    db "heavy person    "
;    db "should not stand"
;    db "on them!@"

Dialog1A7::
    db "Telefonkiosk@"
;   db "Telephone Booth @"

Dialog1A8::
    db "      FARE!     "
    db "  Ingen adgang! "
    db "(Unntatt VovVov)@"
;   db "     DANGER!    "
;   db "    Keep out!   "
;   db "(Except BowWow)@"

Dialog1A9::
    db "<down> GÅ DENNE VEIEN@"
;   db "<down> GO THIS WAY@"

Dialog1AA::
    db "<up> GÅ DENNE VEIEN@"
;   db "<up> GO THIS WAY@"

Dialog1AB::
    db "<right> GÅ DENNE VEIEN@"
;   db "<right> GO THIS WAY@"

Dialog1AC::
    db "<left> GÅ DENNE VEIEN@"
;   db "<left> GO THIS WAY@"

Dialog1AD::
    db "   PRØV IGJEN   "
    db "   FRA STARTEN@"
;   db " TRY AGAIN FROM "
;   db "   THE START@"

Dialog1AE::
    db "BRAVO! DU KLARTE"
    db "DET! BELØNNINGEN"
    db "ER MOT <right>!@"
;   db "GREAT!  YOU DID "
;   db "IT!  YOUR REWARD"
;   db "IS <right> THIS WAY!@"

Dialog1AF::
    db "PÅ TURNÉ        "
    db "        VORTIMER@"
;    db "GONE ON TOUR    "
;    db "         MAMU@"

Dialog1B0::
    db "<right> Gale Tale     "
    db "<down> Mons' pytt@"
;    db "<right> Crazy Tracy   "
;    db "<down> Manbo's Pond@"

Dialog1B1::
    db "<right> Snutebu       "
    db "<down> Martes bukt@"
;    db "<right> Animal Village"
;    db "<down> Martha's Bay@"

Dialog1B2::
    db "<right> Velkommen til"
    db "  Snutebu!@"
;   db "<right> Welcome to the"
;   db " Animal Village!@"

Dialog1B3::
    db "<right> Kirkegård     "
    db "<down> Ulelesletta@"
;    db "<right> Cemetery      "
;    db "<down> Ukuku Prairie @"

Dialog1B4::
    db "Du er nær Tipp- "
    db "topphøydene.    "
    db "Fotobutikken er "
    db "like ved.@"
;    db "You're close to "
;    db "Tal Tal Heights."
;    db "The Camera Shop "
;    db "is nearby.@"

Dialog1B5::
    db "<right> Tindeggen     "
    db "<left> Symresumpen @"
;    db "<right> Tamaranch Mt. "
;    db "<left> Goponga Swamp @"

Dialog1B6::
    db "MUSIKK, FISKEN  "
    db "ROMSTERER I EGG "
    db "DU ER DER_…@"
;   db "MUSIC, THE FISH "
;   db "STIRS IN THE EGG"
;   db "YOU ARE THERE...@"

Dialog1B7::
    db "VINDFISKEN KUN I"
    db "NAVNET, FOR DEN "
    db "ER VERKEN ELLER.@"
;   db "THE WIND FISH IN"
;   db "NAME ONLY, FOR  "
;   db "IT IS NEITHER.@"

Dialog1B8::
Dialog1B9::
    db "I MULDEN HVILER "
    db "HEMMELIGHETER,  "
    db "UNDER SÅLENE_…@"
;   db "IN SOIL SLEEPS  "
;   db "SECRETS, BENEATH"
;   db "YOUR SOLES...@"

Dialog1BA::
    db "I DISSE TRAKTER "
    db "DØLGES DET@"
;   db "AROUND HERE,    "
;   db "SECRETS ARE NIGH@"

Dialog1BB::
    db "HEMMELIGHETER ER"
    db "SOM VANN NÅR DET"
    db "KOMMER TIL BROER@"
;   db "SECRETS ARE LIKE"
;   db "WATER WHEN IT   "
;   db "COMES TO BRIDGES@"

Dialog1BC::
    db "NÅ MÅ DU SE     "
    db "LANGT ETTER EN  "
    db "HEMMELIGHET_…@"
;   db "NOW YOU NEED    "
;   db "LOOK FAR FOR    "
;   db "A SECRET...@"

Dialog1BD::
    db "VINDFISKEN SOVER"
    db "LENGE_… HELTENS "
    db "LIV BORTE_…@"
;   db "THE WIND FISH   "
;   db "SLUMBERS LONG..."
;   db "THE HERO'S LIFE "
;   db "GONE...@"

Dialog1BE::
    db "SJØEN BÆRER     "
    db "SKUM, SØVN BÆRER"
    db "DRØMMER. BEGGE  "
    db "ENDER LIKT      "
    db "KRÆSJ!@"
;   db "SEA BEARS FOAM, "
;   db "SLEEP BEARS     "
;   db "DREAMS. BOTH END"
;   db "IN THE SAME WAY "
;   db "CRASSSH!@"

Dialog1BF::
Dialog1C0::
    db "Å?! #####, jeg  "
    db "ser'u har en fin"
    db "pinne_… Kan jeg "
    db "låne'n litt?    "
    db "    Kan  Kan'ke<ask>" ;får ikke plass til kan ikke
;    db "Oh?!  #####, I  "
;    db "see ya have a   "
;    db "nice stick...   "
;    db "Can I borrow it "
;    db "for a second?   "
;    db "    Can  Can't<ask>"

Dialog1C1::
    db "<stick> ble til bikake"
    db "<honeycomb>! Du skjønner  "
    db "ikke hvordan det"
    db "gikk til, men du"
    db "tar den!@"
;    db "<stick> became the    "
;    db "honeycomb <honeycomb>!    "
;    db "You're not sure "
;    db "how it happened,"
;    db "but take it!@"

Dialog1C2::
    db "Hmmm, #####, du "
    db "er slem!@"
;    db "Hmmm, #####, you"
;    db "are mean!@"

Dialog1C3::
    db "Se opp for      "
    db "kråkeboller!    "
    db "Ikke ta på dem  "
    db "med bare henda!@"
;   db "Beware of Sea   "
;   db "Urchins!  Don't "
;   db "touch them with "
;   db "your bare hands!@"

Dialog1C4::
Dialog1C5::
    db "Jeg var sulten  "
    db "no' så inni ham-"
    db "pen, så jeg dro "
    db "og henta bananer"
    db "på stranda_…    "
    db "#####, hvis du  "
    db "vil ha, bør du  "
    db "dra og hente    "
    db "sjæl!@"
;    db "I was hungry    "
;    db "somethin' fierce"
;    db "so I went and   "
;    db "got bananas at  "
;    db "the beach...    "
;    db "#####, if you   "
;    db "want some, you  "
;    db "should go and   "
;    db "get some!@"

Dialog1C6::
    db "Velkommen til   "
    db "Skjalgs banan-  "
    db "modneri! Jeg er "
    db "Skjalg, dette er"
    db "bananbungalowen!"
    db "Hobbyen min er å"
    db "samle på sjelden"
    db "hermetikk.      "
    db "Broren min er   "
    db "kunstner, så jeg"
    db "antar rare hob- "
    db "byer ligger til "
    db "slekta!@"
;    db "Welcome to      "
;    db "Sale's House O' "
;    db "Bananas!  I'm   "
;    db "Sale, this is my"
;    db "house! Actually,"
;    db "my hobby is col-"
;    db "lecting rare and"
;    db "unusual canned  "
;    db "food. My brother"
;    db "is an artist, so"
;    db "I guess strange "
;    db "hobbies run in  "
;    db "the family!@"

Dialog1C7::
    db "Hva er det du   "
    db "har der?! Det er"
    db "hermetikk! Men  "
    db "for guds skyld, "
    db "mann, gi den <dogfood>  "
    db "til MEG!! VÆR SÅ"
    db "SNILL!          "
    db "Han er helt     " 
    db "hysterisk! Hva  "
    db "skal du gjøre?  "
    db "    Gi   Ikke gi<ask>"
;    db "What's that you "
;    db "have?!  It's    "
;    db "canned food! For"
;    db "heaven's sake,  "
;    db "man, give that <dogfood>"
;    db "to ME!!  PLEASE!"
;    db "He's hysterical!"
;    db "What do you do? "
;    db "    Give Don't<ask>"

Dialog1C8::
    db "Å, tusen takk!  "
    db "Gi meg den!@"
;    db "Oh thank you!   "
;    db "I'll take that!@"

Dialog1C9::
    db "Det er vel ingen"
    db "vits i å trygle?"
    db "Du får si ifra  "
    db "hvis du om-     "
    db "bestemmer deg.@"
;    db "I don't suppose "
;    db "it would do any "
;    db "good to beg?    "
;    db "Well, if you    "
;    db "change your     "
;    db "mind, tell me.@"

Dialog1CA::
    db "  JAFS JAFS!!   "
    db "... ... ... ... "
    db "Fantastisk! Jeg "
    db "vet at det ikke "
    db "er et rettferdig"
    db "bytte, men her  "
    db "har du en klase "
    db "bananer! NAM_…@"
;    db "  MUNCH MUNCH!! "
;    db "... ... ... ... "
;    db "That was great! "
;    db "I know it's not "
;    db "a fair trade,   "
;    db "but here's some "
;    db "bananas! YUM...@"

Dialog1CB::
    db "Du ga ham <dogfood> og  "
    db "fikk bananer <bananas> i"
    db "gjengjeld! Smil,"
    db "du har gjort en "
    db "god deal!@"
;   db "You gave him <dogfood>  "
;   db "and got bananas "
;   db "<bananas> in return!    "
;   db "Good deal!@"

Dialog1CC::
    db "Takk igjen! Det "
    db "var snadder!@"
;   db "Thank you again!"
;   db "That was yummy!@"

Dialog1CD::
    db "Hei, kompis! Har"
    db "du noensinne    "
    db "seilt en flåte  "
    db "ned strykene?   "
    db "Det går an, ved "
    db "Tipptopphøydene!"
    db "Du burde prøve!@"
;    db "Hey friend! Have"
;    db "you ever ridden "
;    db "the rapids on a "
;    db "raft?  You can, "
;    db "near Tal Tal    "
;    db "Heights!  You   "
;    db "ought to try it!@"

Dialog1CE::
    db "Fanker'n heller!"
    db "Jeg har gått tom"
    db "for honning! Om "
    db "jeg hadde det,  "
    db "kunne jeg lagd  "
    db "et herremåltid!@"
;    db "Rik'm rak'm! I  "
;    db "ran out of      "
;    db "ingredients!  If"
;    db "I had honey, I  "
;    db "could make this "
;    db "fit for a king!@"
; 

Dialog1CF::
    db "Hei hå! Du der! "
    db "Er det muligens "
    db "en <honeycomb> du har der?"
    db "Jeg gikk nettopp"
    db "tom! Vil du     "
    db "bytte den mot en"
    db "ananas?         "
    db "    Ja   Nei<ask>"
;    db "Hi ho! Hey you! "
;    db "Is that possibly"
;    db "a <honeycomb> you have?   "
;    db "I just ran out! "
;    db "Will you swap it"
;    db "for a pineapple?"
;    db "    Yes  No<ask>"

Dialog1D0::
    db "Du ga ham <honeycomb> mot "
    db "<pineapple>! Den er ikke  "
    db "like søt, men   "
    db "deilig likevel!@"
;    db "You exchanged <honeycomb> "
;    db "for <pineapple>!  It's not"
;    db "as sweet, but it"
;    db "is delicious!   @"

Dialog1D1::
    db "Det var himla   "
    db "synd, men jeg   "
    db "vet at de der er"
    db "sjelden vare!@"
;    db "That's a crying "
;    db "shame, but I    "
;    db "realize those   "
;    db "are a rare      "
;    db "delicacy!@"

Dialog1D2::
    db "Hei hå! Ja, jeg "
    db "vet, den store  "
    db "klumpen ligger  "
    db "og sover midt i "
    db "veien som fører "
    db "til Yahara-     "
    db "ørkenen! Når han"
    db "sover rikker han"
    db "seg ikke på lee-"
    db "eeenge. Men hei!"
    db "Ta med deg lille"
    db "Marin og vekk   "
    db "ham med sangen  "
    db "hennes! Den lat-"
    db "sabben ville    "
    db "våknet med et   "
    db "rykk hvis han   "
    db "hørte henne     "
    db "synge, det er   "
    db "jeg sikker på!  "
    db "He he he!@"
;    db "Hi ho! Yeah, I  "
;    db "know, that tub  "
;    db "of goo is asleep"
;    db "right in the way"
;    db "to Yarna Desert!"
;    db "Once he's asleep"
;    db "he won't budge  "
;    db "for a loooooonng"
;    db "time.  But hey! "
;    db "Take Little     "
;    db "Marin and wake  "
;    db "him up with her "
;    db "song!  That slob"
;    db "would wake up   "
;    db "with a jump if  "
;    db "he heard her    "
;    db "sing, for sure! "
;    db "Heh heh heh!@"

Dialog1D3::
    db "Planen min er å "
    db "åpne en avdeling"
    db "i Måsebu!@"
;    db "My ultimate plan"
;    db "is to open a    "
;    db "branch in Mabe  "
;    db "Village!@"

Dialog1D4::
    db "HEI HÅ! Lille   "
    db "Marin! Vel-     "
    db "kommen!         "
    db "... ... ... ... "
    db "Å søren, du er  "
    db "også her_…      "
    db "Beklager_…@"
;    db "HI HO!  Little  "
;    db "Marin!  Welcome!"
;    db "... ... ... ... "
;    db "Oh, shucks!  You"
;    db "are here too... "
;    db "Sorry...@"

Dialog1D5::
    db "Å, #####, jeg er"
    db "glad du fant    "
    db "dette stedet.   "
    db "Blir du litt og "
    db "snakker med meg?"
    db "    Ja!  Nei_…<ask>"
;    db "Oh, #####, I'm  "
;    db "glad you found  "
;    db "this place.     "
;    db "Will you stay   "
;    db "and talk to me  "
;    db "for a while?    "
;    db "    Yes! No...<ask>"

Dialog1D6::
    db "Jeg skjønner.   "
    db "Jeg blir her og "
    db "ser på bølgene  "
    db "en stund_…@"
;    db "Okay, I'll just "
;    db "watch the waves "
;    db "for a while...@"

Dialog1D7::
    db "På stranda_…    "
    db " Marin  <marin>@"
;    db "At the beach... "
;    db " Marin  <marin>@"

Dialog1D8::
    db "Jeg lurer på    "
    db "hvor disse      "
    db "kokosnøttpalmene"
    db "kommer fra?     "
    db "_… Tarin sier at"
    db "det ikke finnes "
    db "noe bortenfor   "
    db "havet, men jeg  "
    db "tror det må være"
    db "ett eller annet "
    db "der_… Hjertet   "
    db "mitt hoppet over"
    db "et slag da jeg  "
    db "fant deg, #####!"
    db "Jeg tenkte at   "
    db "denne personen  "
    db "har kommet for å"
    db "gi oss en       "
    db "beskjed_…@"
;    db "I wonder where  "
;    db "these coconut   "
;    db "trees come from?"
;    db "...Tarin says   "
;    db "there is nothing"
;    db "beyond the sea, "
;    db "but I believe   "
;    db "there must be   "
;    db "something over  "
;    db "there...  When I"
;    db "discovered you, "
;    db "#####, my heart "
;    db "skipped a beat! "
;    db "I thought, this "
;    db "person has come "
;    db "to give us a    "
;    db "message...@"

Dialog1D9::
    db "... ... ... ... "
    db "... ... ... ... "
    db "Hvis jeg var en "
    db "måke, ville jeg "
    db "flydd så langt  "
    db "jeg kunne! Jeg  "
    db "ville flydd til "
    db "steder langt av "
    db "gårde og sunget "
    db "for mange folk! "
    db "_… Jeg lurer på "
    db "om drømmen min  "
    db "blir oppfylt    "
    db "hvis jeg ber til"
    db "Vindfisken_…_…@"
;    db "... ... ... ... "
;    db "... ... ... ... "
;    db "If I was a sea  "
;    db "gull, I would   "
;    db "fly as far as I "
;    db "could!  I would "
;    db "fly to far away "
;    db "places and sing "
;    db "for many people!"
;    db "...If I wish to "
;    db "the Wind Fish,  "
;    db "I wonder if my  "
;    db "dream will come "
;    db "true... ... ...@"

Dialog1DA::
    db "Hei! Hører du   "
    db "etter?          "
    db "#####, hører du "
    db "etter hva jeg   "
    db "sier?           "
    db "    Ja   Nei_…<ask>"
;    db "Hey!  Are you   "
;    db "listening?      "
;    db "#####, are you  "
;    db "listening to me?"
;    db "    Yeah No...<ask>"

Dialog1DB::
    db "Jeg har lyst til"
    db "å vite alt om   "
    db "deg_… Eeh_… Øh_…"
    db "Ha ha ha ha!@"
;    db "I want to know  "
;    db "everything about"
;    db "you...Err...Uhh,"
;    db "Ha ha ha ha!@"
; bedre forslag enn bare Eeh_… Eh_…? mvh Julius

Dialog1DC::
    db "Hm? Hvalrossen  "
    db "vil at jeg skal "
    db "komme til ham?  "
    db "OK, la oss dra!@"
;    db "Hunh? The walrus"
;    db "wants me to go  "
;    db "to him?  It     "
;    db "doesn't matter, "
;    db "I will go with  "
;    db "you to him...@"

Dialog1DD::
    db "Uææææææ! Auuuuu!"
    db "... ... ... ... "
    db "Jeg har mista   "
    db "helt lysten på  "
    db "honning!@"
;    db "Unnnngh! Owwwww!"
;    db "... ... ... ... "
;    db "I've sure lost  "
;    db "my taste for    "
;    db "honey!@"

Dialog1DE::
    db "Hmf! Du drømmer "
    db "deg alltid bort!"
    db "Kan du være så  "
    db "snill å høre på "
    db "meg neste gang?!@"
;    db "Humph! Your head"
;    db "is always in the"
;    db "clouds! Will you"
;    db "please listen to"
;    db "me next time?!@"

Dialog1DF::
    db "Ha! Er det alt  "
    db "du har?!        "
    db "Gjør deg klar   "
    db "for DETTE!@"
;    db "Ha! That's all  "
;    db "you've got?!    "
;    db "Get ready for   "
;    db "THIS!@"

Dialog1E0::
    db "ZZZ ZZZ ZZZ ZZZ "
    db " ... <marin> ... <marin> ...@"
;    db "ZZZ ZZZ ZZZ ZZZ "
;    db " ... <marin> ... <marin> ...@"

Dialog1E1::
    db "Ja, det er den  "
    db "latsabben av en "
    db "hvalross! Skal  "
    db "vi gi ham en    "
    db "overraskelse?   "
    db "    Ja   Nei_…<ask>"
;    db "Yes, it's that  "
;    db "lazy walrus!    "
;    db "Shall we give   "
;    db "him a little    "
;    db "surprise?       "
;    db "    Yes  No...<ask>"

Dialog1E2::
    db "Aha ha ha! Wow! "
    db "Han våknet      "
    db "virkelig med et "
    db "rykk!@"
;    db "Aha ha ha!  Wow!"
;    db "He certainly    "
;    db "woke with a     "
;    db "start!@"

Dialog1E3::
    db "Hm? Å, han roper"
    db "på meg_…        "
    db "Det er det samme"
    db "som alltid_…    "
    db "Ha ha!@"
;    db "Hunh?  Oh, he's "
;    db "calling me...   "
;    db "It's the same as"
;    db "always... Ha ha!@"
; "Calling" er roping? Eller kan det være at noen kaller på noen? Kan vel ihvertfall ikke være at noen ringer mvh Julius

Dialog1E4::
    db "Du har rett, det"
    db "ville være slemt"
    db "å vekke ham nå! "
    db "Vi lar ham sove "
    db "litt lenger!@"
;    db "You're right, it"
;    db "would be mean to"
;    db "wake him up now!"
;    db "Let's let him   "
;    db "sleep some more!@"

Dialog1E5::
    db "#####, jeg går  "
    db "til Snutebu! Vær"
    db "snill og kom    "
    db "innom, greit?@"
;    db "#####, I'm going"
;    db "to the Animal   "
;    db "Village!  Please"
;    db "drop by, okay?@"

Dialog1E6::
    db "Voff voff voff! "
    db " <marin>  <marin>!  <marin>   <marin>!  "
    db "_… <link>??@"
;   db "Arfh! Arfh! Arf!"
;    db " <marin>  <marin>!  <marin>   <marin>!  "
;    db "_… <link>??@"
    
Dialog1E7::
    db "Det nøtter'nte, "
    db "lille kompis! En"
    db "fisk tok kroken "
    db "min_… Jeg prøver"
    db "å kaste snøret i"
    db "vannet, men     "
    db "får'nte noe napp"
    db "_… Jeg tenkte   "
    db "meg at dette    "
    db "ville skje_…@"
;   db "It's no use,    "
;   db "little buddy!  A"
;   db "fish took my    "
;   db "hook... I keep  "
;   db "casting my line "
;   db "into the water, "
;   db "but I haven't   "
;   db "got a bite... I "
;   db "thought this    "
;   db "would happen...@"

Dialog1E8::
    db "Å! Hva er det du"
    db "har der? Er det "
    db "en fiskekrok?   "
    db "Det er nok best "
    db "at du gir den   "
    db "til meg. Jeg kan"
    db "la deg få den   "
    db "neste fangsten  "
    db "min hvis du lar "
    db "meg få den_…    "
    db "    Okei Nei<ask>"
;   db "Oh! What is that"
;   db "you have in your"
;   db "hand?  It's not "
;   db "a fishing hook, "
;   db "is it?  You had "
;   db "better let me   "
;   db "have it.  I'll  "
;   db "give you my next"
;   db "catch if you let"
;   db "me have it...   "
;   db "    Okay No<ask>"

Dialog1E9::
    db "Se og lær hvor- "
    db "dan en proff    "
    db "gjør det.@"
;   db "Keep your eyes  "
;   db "open and watch  "
;   db "a pro at work.@"

Dialog1EA::
    db "Du burde være   "
    db "greiere mot meg!"
    db "Jeg trodde vi   "
    db "var kompiser!@"
;   db "You should be   "
;   db "more kind to me!"
;   db "I thought we    "
;   db "were buddies!@"

Dialog1EB::
    db "Oi, det er en   "
    db "SVÆÆÆÆÆÆÆÆÆRING!@"
;   db "My, that's a    "
;   db "BIIIIG one!@"

Dialog1EC::
    db "<fishhook> ble til et    "
    db "perlekjede <bra>!   "
    db "For en flaks!@"
;    db "The <fishhook> became a  "
;    db "necklace <bra>!     "
;    db "L-l-lucky!@"

Dialog1ED::
    db "Jeg kan'ke vente"
    db "med å se hva det"
    db "neste jeg får   "
    db "blir!@"
;    db "I can't wait to "
;    db "see what I'll   "
;    db "catch next!@"

Dialog1EE::
    db "Mannen min har  "
    db "gått seg bort i "
    db "skogen! Vær så  "
    db "snill, finn ham!@"
;   db "My husband is   "
;   db "lost in the     "
;   db "woods! Please   "
;   db "go find him!@"

Dialog1EF::
    db "Hei, kan du se  "
    db "meg?! Det må    "
    db "bety at du har  "
    db "et forstørrel-  "
    db "sesglass. Jeg er"
    db "ingen bølle. Jeg"
    db "vil bare leve i "
    db "fred.@"
;    db "Hey, you can see"
;    db "me?! You must   "
;    db "have a magnify- "
;    db "ing glass. I'm  "
;    db "not a trouble   "
;    db "maker. I just   "
;    db "want to live in "
;    db "peace.@"

Dialog1F0::
    db "Da jeg svømte i "
    db "bukta, skylte en"
    db "bølge bort det  "
    db "dyrebare perle- "
    db "kjedet fra rundt"
    db "halsen min! Hvis"
    db "du finner det,  "
    db "skal jeg la deg "
    db "ta et skjell fra"
    db "halen min!@"
;    db "When I was swim-"
;    db "ming in the bay,"
;    db "the waves took a"
;    db "very important  "
;    db "necklace from   "
;    db "around my neck! "
;    db "If you find it, "
;    db "I will let you  "
;    db "take a scale    "
;    db "from my tail!   @"
; hmmmmm denne klarte jeg ikke helt hehe

Dialog1F1::
    db "Jeg har allerede"
    db "lett her i nær- "
    db "heten!@"
;    db "I have already  "
;    db "looked around   "
;    db "here!@"

Dialog1F2::
    db "Åå! Der er det! "
    db "Det er perle-   "
    db "kjedet mitt! Gi "
    db "det tilbake! Jeg"
    db "skal la deg få  "
    db "et skjell, som  "
    db "jeg sa!         "
    db "    Gi   Behold<ask>"
;    db "Ahh!  That's it!"
;    db "That's my neck- "
;    db "lace!  Give it! "
;    db "Give it back!  I"
;    db "will give you a "
;    db "scale as I said!"
;    db "    Give Keep<ask>"

Dialog1F3::
    db "Lov meg at du   "
    db "bare tar ett!@"
;    db "Promise!  You'll"
;    db "only take one!@"

Dialog1F4::
    db "Du er hjerteløs "
    db "og slem!@"
;    db "You are heart-  "
;    db "less and cruel!@"

Dialog1F5::
    db "Du ga tilbake   "
    db "perlekjedet <bra> og"
    db "fikk et skjell <scale>"
    db "fra halen til   "
    db "havfruen. Hvor- "
    db "dan skal du     "
    db "bruke det?@"
;    db "You returned the"
;    db "necklace <bra> and  "
;    db "got a scale <scale> of"
;    db "the mermaid's   "
;    db "tail.  How will "
;    db "you use this?@"

Dialog1F6::
    db "Dette kaller jeg"
    db "«Jeg var veldig "
    db "redd». Smil!@"
;    db "I'll call this  "
;    db "'I Was Very     "
;    db "Afraid.' Smile!@"
; 

Dialog1F7::
    db "En kunstner ba  "
    db "meg en gang om å"
    db "posere for ham, "
    db "og han ville    "
    db "også ha et      "
    db "skjell_… Kan    "
    db "legenden om     "
    db "forstørrelses-  "
    db "glasset være    "
    db "sann_…?@"
;    db "An artist once  "
;    db "asked me to pose"
;    db "for him, and he "
;    db "wanted a scale, "
;    db "too...  Can the "
;    db "legend of the   "
;    db "Magnifying Lens "
;    db "be true...?@"

Dialog1F8::
    db "Hei der! Det er "
    db "meg, fotografen!"
    db "Hva sier du, er "
    db "Zora hjemme? Jeg"
    db "MÅ ta et bilde. "
    db "Jeg kaller det  "
    db "«Jeg fant Zora».@"
;    db "Hi there! It's  "
;    db "me, the photo-  "
;    db "grapher! You say"
;    db "Zora is in the  "
;    db "house? I HAVE to"
;    db "take a picture  "
;    db "of that. I'll   "
;    db "call it 'I Found"
;    db "Zora.'@"

Dialog1F9::
    db "Rikards villa@"
;   db "Richard's Villa @"

Dialog1FA::
    db "Elveslottet     "
    db "10 minutter <right> <up>@"
;    db "Kanalet Castle  "
;    db "10 Min. <right> <up>@"

Dialog1FB::
    db "Elveslottet     "
    db "5 minutter <right>@"
;    db "Kanalet Castle  "
;    db "5 Min. <right>@"

Dialog1FC::
    db "Elveslottet     "
    db "50 skritt <up>@"
;    db "Kanalet Castle  "
;    db "50 Paces <up>@"
; forslag til noe bedre her tas imot

Dialog1FD::
    db "«RRRING! RRRING!"
    db "KLIKK! Ja, hallo"
    db "du snakker med  "
    db "Bowler, og hvem "
    db "prater jeg med  "
    db "nå?_… Okei, er  "
    db "du klar for å   "
    db "sortere litt    "
    db "søppel, #####!? "
    db "KLIKK!»  ??? _… "
    db "Du må ha ringt  "
    db "feil nummer_… @ "
;    db "'BRRING! BRRING!"
;    db " BRRING! CLICK! "
;    db "Yeees!  It's the"
;    db "Bucket Mouse!   "
;    db "Thanks for call-"
;    db "ing! ...Well... "
;    db "CLICK!'  ??? ..."
;    db "You must have   "
;    db "dialed a wrong  "
;    db "number...@"

Dialog1FE::
     db "Oi! Det er en   "
     db "sværing! Og den "
     db "har en hjertebit"
     db "også! Du får 20 "
     db "rupier i premie "
     db "attpå! Vil du   "
     db "prøve igjen?    "
     db "    Ja   Nei<ask>"
;    db "Oh!  It's a big "
;    db "one!  And it has"
;    db "a Piece of      "
;    db "Heart, too!  You"
;    db "get a 20 Rupee  "
;    db "prize on top of "
;    db "that! Try again?"
;    db "    Yes  No<ask>"

Dialog1FF::
     db "Oi! Det er en   "
     db "sværing! Og den "
     db "har en hjertebit"
     db "også! Du har    "
     db "fullført enda en"
     db "hjertebeholder! "
     db "Du får 20 rupier"
     db "i premie attpå! "
     db "Vil du prøve    "
     db "igjen?          "
     db "    Ja   Nei<ask>"
;    db "Oh!  It's a big "
;    db "one!  And it has"
;    db "a Piece of      "
;    db "Heart, too!  You"
;    db "have completed  "
;    db "another Heart   "
;    db "Container!  On  "
;    db "top of that, you"
;    db "get a 20 Rupee  "
;    db "prize! Want to  "
;    db "try again?      "
;    db "    Yes  No<ask>"

Dialog200::
    db "«Hvordan håndte-"
    db "re skjoldet ditt"
    db "som en proff!»  "
    db "Les denne boka? "
    db "    Ja   Nei<ask>"
;    db " 'How To Handle "
;    db "   Your Shield  "
;    db "   Like A Pro!' "
;    db "Read this book? "
;    db "    YES  NO<ask>"

Dialog201::
    db "«Hvis du holder "
    db "knappen nede,   "
    db "kan du forsvare "
    db "deg mot fienders"
    db "angrep, og noen "
    db "fiender kan også"
    db "vippes_… I til- "
    db "legg til det    "
    db "vanlige skjoldet"
    db "finnes det en   "
    db "speilvariant som"
    db "kan forsvare mot"
    db "stråler!»@"
;    db "'If you hold the"
;    db "Button down, you"
;    db "can defend your-"
;    db "self from enemy "
;    db "attacks, and you"
;    db "can flip some   "
;    db "enemies, too... "
;    db "Besides the     "
;    db "standard shield "
;    db "there is also a "
;    db "mirrored variety"
;    db "which can defend"
;    db "against beams!'@"

Dialog202::
     db "    «Velg       "
     db " gjenstanden som"
     db " passer for deg»"
     db "Les denne boka? "
     db "    Ja   Nei<ask>"
;    db " 'Selecting The "
;    db "   Item That's  "
;    db "  Right For You'"
;    db "Read this book? "
;    db "    YES  NO<ask>"

Dialog203::
    db "«Du kan velge de"
    db "gjenstandene du "
    db "liker best og   "
    db "tildele dem A-  "
    db "og B-knappen på "
    db "underskjermen.  "
    db "Ved å bruke for-"
    db "skjellige gjen- "
    db "stander kan du  "
    db "kjempe uten et  "
    db "sverd! Prøv     "
    db "mange ulike ting"
    db "for å finne ut  "
    db "hva som passer  "
    db "deg best!»@"
;    db "'You can select "
;    db "your favorite   "
;    db "item for the A  "
;    db "and B Buttons on"
;    db "the Sub-Screen. "
;    db "Using different "
;    db "items, you can  "
;    db "fight without a "
;    db "sword!  Try many"
;    db "different things"
;    db "to find what's  "
;    db "right for you!'@"

Dialog204::
     db " «Hvordan bruke "
     db "   kartet: En   "
     db "     manual»    "
     db "Les denne boka? "
     db "    Ja   Nei<ask>"
;    db " 'Auto Map and  "
;    db "Memo Guide Book'"
;    db "Read this book? "
;    db "    YES  NO<ask>"

Dialog205::
    db "«Du kan se et   "
    db "øykart ved å    "
    db "trykke på       "
    db "SELECT-knappen. "
    db "De mørke delene "
    db "av kartet er    "
    db "steder du ikke  "
    db "har besøkt ennå."
    db "Flytt markøren  "
    db "og trykk på A-  "
    db "knappen for å få"
    db "mer informasjon "
    db "om et område,   "
    db "eller se igjen  "
    db "meldingen du    "
    db "fikk der_…»     "
    db "Åh, så praktisk!@"
;    db "'You can see an "
;    db "island map by   "
;    db "pressing the    "
;    db "SELECT Button.  "
;    db "The dark parts  "
;    db "of the map are  "
;    db "places you have "
;    db "not yet visited."
;    db "Move the cursor "
;    db "and press the A "
;    db "Button to get   "
;    db "more information"
;    db "about an area,  "
;    db "or to replay the"
;    db "message you got "
;    db "there...'  Ahhh!"
;    db "How convenient!@"

Dialog206::
     db " «Hemmelighetene"
     db " til den virvl- "
     db "  ende klingen» "
     db "Les denne boka? "
     db "    Ja   Nei<ask>"
;    db " 'Secrets Of The"
;    db " Whirling Blade'"
;    db "Read this book? "
;    db "    YES  NO<ask>"

Dialog207::
    db "«Den virvlende  "
    db "klingeteknikken "
    db "har blitt over- "
    db "levert fra gene-"
    db "rasjon til gene-"
    db "rasjon i heltens"
    db "familie. For å  "
    db "bruke den, hold "
    db "nede sverdknapp-"
    db "en og lad opp   "
    db "kraften din. Når"
    db "du har nok, kan "
    db "du slippe       "
    db "knappen! Kan du "
    db "mestre dette?»@"
;    db "'The Whirling   "
;    db "Blade technique "
;    db "has been handed "
;    db "down from gener-"
;    db "ation to gener- "
;    db "ation by the    "
;    db "family of the   "
;    db "hero. To use it,"
;    db "hold down the   "
;    db "Sword Button and"
;    db "build up your   "
;    db "power.  When you"
;    db "have enough, you"
;    db "can release the "
;    db "Button!  Can you"
;    db "master this?'@"

Dialog208::
     db "  «Teorien om   "
     db "   ormehull»    "
     db "Les denne boka? "
     db "    Ja   Nei<ask>"
;    db "'The Properties "
;    db "  Of Warp Holes'"
;    db "Read this book? "
;    db "    YES  NO<ask>"

Dialog209::
    db "«Det finnes noen"
    db "ormehull på     "
    db "Koholint. Du kan"
    db "teleportere mel-"
    db "lom disse. Hvis "
    db "du hopper inn i "
    db "ormehullet du   "
    db "kom fra, vil du "
    db "gå til det neste"
    db "i rekken. Du kan"
    db "bare teleportere"
    db "til et hull du  "
    db "har sett med    "
    db "egne øyne_…»@"
;    db "'There are some "
;    db "Warp Holes on   "
;    db "Koholint Island."
;    db "You can warp to "
;    db "and fro using   "
;    db "these holes.  If"
;    db "you jump into   "
;    db "the Warp Hole   "
;    db "at which you    "
;    db "arrived, you    "
;    db "will go to the  "
;    db "next one in the "
;    db "sequence.  You  "
;    db "can only warp to"
;    db "a hole you have "
;    db "seen with your  "
;    db "own eyes...'@"

Dialog20A::
    db "   «Moro med    "
    db "     bomber»    "
    db "Les denne boka? "
    db "    Ja   Nei<ask>"
;    db "'Fun With Bombs'"
;    db "Read this book? "
;    db "    YES  NO<ask>"

Dialog20B::
    db "«Etter at du har"
    db "lagt en bombe,  "
    db "kan du plukke   "
    db "den opp igjen   "
    db "ved å trykke på "
    db "knappen. Du kan "
    db "så kaste den ved"
    db "å trykke på     "
    db "knappen én gang "
    db "til. Visste du  "
    db "det?»@"
;    db "'After you put a"
;    db "Bomb down, you  "
;    db "can pick it up  "
;    db "by pressing the "
;    db "Button again.   "
;    db "You can then    "
;    db "throw it by     "
;    db "pushing the     "
;    db "Button one more "
;    db "time.  Did you  "
;    db "know that?'@"

Dialog20C::
    db "  «Atlas over   "
    db "   Koholint»    "
    db "Du kan flytte   "
    db "markøren og     "
    db "sjekke navnet på"
    db "et sted_… Vil du"
    db "se på kartet?   "
    db "    Se   La være<ask>"
;    db "   'Atlas Of    "
;    db "Koholint Island'"
;    db "You can move the"
;    db "cursor and look "
;    db "up the name of a"
;    db "place...  Do you"
;    db "want to look at "
;    db "this map?       "
;    db "    Look Don't<ask>"

Dialog20D::
    db "«De dunkle gåt- "
    db "ene og mysteri- "
    db "ene på Koholint»"
    db "Vil du virkelig "
    db "lese den?       "
    db "    Ja   Nei<ask>"
;    db " 'Dark Secrets  "
;    db "  And Mysteries "
;    db "   Of Koholint' "
;    db "Do you really   "
;    db "want to read it?"
;    db "    YES  NO<ask>"

Dialog20E::
    db "Gisp! Hv-hva er "
    db "dette!_… _… Du  "
    db "kan ikke lese   "
    db "den lille tekst-"
    db "en uten å bruke "
    db "forstørrelses-  "
    db "glass_… @"
;    db "Gasp! Wha-What's"
;    db "this! ... ...   "
;    db "You can't read  "
;    db "the tiny print  "
;    db "without the aid "
;    db "of a magnifying "
;    db "glass...@"

Dialog20F::
Dialog210::
    db "_… graven min_… "
    db "_… ta meg til_… "
    db " _… min grav_… @"
;    db "...my grave...  "
;    db "...take me...   "
;    db "...my grave...@"

Dialog211::
    db "   _… huset_…   "
    db "_… ta meg til_… "
    db "   _… huset_…   "
    db "_… ved bukta_…@"
;    db "...the house... "
;    db " ...take me...  "
;    db "...the house... "
;    db "...at the bay...@"

Dialog212::
    db " _… N-N-Nei!_…  "
    db " _… I-ikke dit!@"
;    db "...N-N-No!...   "
;    db "...N-not there!@"

Dialog213::
    db "    _… Her!_…   "
    db "   _… gå inn_…  "
    db " _… mitt hus_… @"
;    db "   ...Here!...  "
;    db "   ...enter...  "
;    db " ...my house...@"

Dialog214::
    db "  _… Nostalgi_… "
    db "  _… uendret_…  "
    db "   _… uhuuu_…@"
;    db " ...Nostalgia..."
;    db " ...unchanged..."
;    db " ...boo hoo...@"

Dialog215::
    db "  _… Nok nå_…   "
    db " _… kirkegård_… "
    db "_… ta meg til_… "
    db " _… min grav_… @"
;    db "  ...Enough...  "
;    db " ...cemetery... "
;    db "  ...take me... "
;    db " ...my grave...@"

Dialog216::
    db "_… Tusen takk_… "
    db " _… En krukke_… "
    db "_… i mitt hjem_…"
    db "  _… se inni_…  "
    db " _… far_… vel_…@"
;    db "...Thank you... "
;    db " ...a jar...    "
;    db "...in my home..."
;    db "...look inside.."
;    db "...bye...bye...@"

Dialog217::
    db "Rundt og rundt, "
    db "går eggets vei_…"
    db "<left> <left> <up> <right> <right> <up> <left> <up> "
    db "??_… Hmmm, denne"
    db "boka utsondrer  "
    db "hemmeligheter_…@"
;    db "Round and round,"
;    db "the passageways "
;    db "of the Egg...   "
;    db "<left> <left> <up> <right> <right> <up> <left> <up> "
;    db "??  ...Hmmmmmm, "
;    db "this book reeks "
;    db "of secrets...@"

Dialog218::
    db "Rundt og rundt, "
    db "går eggets vei_…"
    db "<right> <up> <up> <right> <up> <up> <right> <up> "
    db "??_… Hmmm, denne"
    db "boka utsondrer  "
    db "hemmeligheter_…@"
;    db "Round and round,"
;    db "the passageways "
;    db "of the Egg...   "
;    db "<right> <up> <up> <right> <up> <up> <right> <up> "
;    db "??  ...Hmmmmmm, "
;    db "this book reeks "
;    db "of secrets...@"

Dialog219::
    db "Rundt og rundt, "
    db "går eggets vei_…"
    db "<left> <up> <right> <up> <left> <up> <right> <up> "
    db "??_… Hmmm, denne"
    db "boka utsondrer  "
    db "hemmeligheter_…@"
;    db "Round and round,"
;    db "the passageways "
;    db "of the Egg...   "
;    db "<left> <up> <right> <up> <left> <up> <right> <up> "
;    db "??  ...Hmmmmmm, "
;    db "this book reeks "
;    db "of secrets...@"

Dialog21A::
    db "Rundt og rundt, "
    db "går eggets vei_…"
    db "<right> <right> <right> <right> <up> <up> <up> <up> "
    db "??_… Hmmm, denne"
    db "boka utsondrer  "
    db "hemmeligheter_…@"
;    db "Round and round,"
;    db "the passageways "
;    db "of the Egg...   "
;    db "<right> <right> <right> <right> <up> <up> <up> <up> "
;    db "??  ...Hmmmmmm, "
;    db "this book reeks "
;    db "of secrets...@"

Dialog21B::
    db "_… Du er sein!  "
    db "Trodde du var   "
    db "borte for godt!@"
;    db "...You're late! "
;    db "I thought you'd "
;    db "never come back!@"

Dialog21C::
    db "_… IIIK! Du er  "
    db "skadet! Grrr!   "
    db "Ikke vær så     "
    db "dumdristig!@"
;    db "...EEEK!  You're"
;    db "hurt!  Arrrgh!  "
;    db "Don't be so     "
;    db "reckless!@"

Dialog21D::
    db "#####! Du er    "
    db "tilbake! Er du  "
    db "skadet?@"
;    db "#####! You're   "
;    db "back!  Are you  "
;    db "hurt?@"

Dialog21E::
    db "_… Din idiot!   "
    db "Jeg sa jo at    "
    db "dette ville skje"
    db "_… Hæ?! Hva? Jeg"
    db "sa ikke noenting"
    db "jeg, virkelig!@"
;    db "...You idiot!   "
;    db "I told you this "
;   db "would happen... "
;    db "Eh?!  What?  I  "
;    db "didn't say any- "
;    db "thing, really!@"

Dialog21F::
Dialog220::
    db "Hei kompis! Det "
    db "er alvorlig! Ja,"
    db "veldig alvorlig!"
    db "Ja, det er det! "
    db "Skoboldene kom  "
    db "til landsbyen!  "
    db "Ja, det stemmer!"
    db "En hel gjeng med"
    db "skobolder! Så_… "
    db "Helt sant! Alle "
    db "gikk til huset_…"
    db "Ja, det huset,  "
    db "og så gjorde de "
    db "noe i VovVovs   "
    db "hus!! Det var et"
    db "skikkelig ille  "
    db "skue, med de    "
    db "s-s-skoboldene! "
    db "Så, altså, æææ! "
    db "... ... ... ... "
    db "... ... ... ... "
    db "Det kan være    "
    db "raskere å finne "
    db "ut av det selv!@"
;    db "Hey buddy!  It's"
;    db "serious!  Yeah, "
;    db "really serious!!"
;    db "Yeah, it is!    "
;    db "The Moblins came"
;    db "to the village! "
;    db "Yeah, that's    "
;    db "right!  A whole "
;    db "gang of Moblins!"
;    db "Then... It's for"
;    db "real!  They all "
;    db "went to the     "
;    db "house...  Yeah, "
;    db "that house, and "
;    db "then they did   "
;    db "something at Bow"
;    db "Wow's house!!   "
;    db "It was a really "
;    db "bad scene, with "
;    db "the M-m-moblins!"
;    db "So, I mean, ahh!"
;    db "... ... ... ... "
;    db "... ... ... ... "
;    db "It might be     "
;    db "faster to find  "
;    db "out for yourself"
;    db "what happened!@"

Dialog221::
    db "Jeg fant en bra "
    db "gjenstand som   "
    db "skylte opp på   "
    db "stranda_… Jeg   "
    db "bytter den mot  "
    db "det du har på B-"
    db "knappen_…       "
    db "    Okei Nei<ask>"
;    db "I found a good  "
;    db "item washed up  "
;    db "on the beach... "
;    db "I'll trade it to"
;    db "you for what you"
;    db "have in your B  "
;    db "Button...       "
;    db "    Okay No<ask>"

Dialog222::
    db "Ok, vi bytter!  "
    db "Når du ikke vil "
    db "ha bumerangen   "
    db "lenger kan du   "
    db "komme tilbake!@"
;    db "Okay, let's do  "
;    db "it!  When you   "
;    db "don't want the  "
;    db "Boomerang any   "
;    db "more, come back!@"

Dialog223::
    db "Åh, ja, eh_…    "
    db "Okei, samma det.@"
;    db "Oh, yeah, uh... "
;    db "okay, whatever.@"

Dialog224::
    db "Du fikk bumeran-"
    db "gen i bytte mot "
    db "gjenstanden du  "
    db "hadde.@"
;    db "You got the     "
;    db "Boomerang in    "
;    db "exchange for the"
;    db "item you had.@"

Dialog225::
    db "Gi meg tilbake  "
    db "bumerangen, jeg "
    db "ber deg! Jeg gir"
    db "deg tilbake     "
    db "gjenstanden din!"
    db "    Okei Ikke nå<ask>"
;    db "Give me back the"
;    db "Boomerang, I beg"
;    db "you! I'll return"
;    db "the item you    "
;    db "gave to me!     "
;    db "    Okay Not Now"
;    db "<ask>"

Dialog226::
    db "Gjenstanden kom "
    db "tilbake til deg."
    db "Du returnerte   "
    db "bumerangen.@"
;    db "The item came   "
;    db "back to you. You"
;    db "returned the    "
;    db "Boomerang.@"

Dialog227::
    db "Hm_… Ikke gi meg"
    db "den gjenstanden "
    db "_… Hva med noe  "
    db "annet?@"
;    db "Ah... Don't give"
;    db "me that item... "
;    db "How about some- "
;    db "thing else?@"

Dialog228::
    db "«RRRING! RRRING!"
    db "Ja, det er Ul-  "
    db "rik! Du har ikke"
    db "funnet de 5     "
    db "gullbladene?    "
    db "Pass på de du   "
    db "har. Noen kan   "
    db "prøve å ta dem! "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "You haven't     "
;    db "found the 5     "
;    db "Golden Leaves?  "
;    db "Keep an eye on  "
;    db "the ones you    "
;    db "have. Someone   "
;    db "might try and   "
;    db "take 'em! Bye!  "
;    db "CLICK!'@"

Dialog229::
    db "«RRRING! RRRING!"
    db "Ja, det er Ul-  "
    db "rik! Du har ikke"
    db "funnet de 5     "
    db "gullbladene?    "
    db "Prøv å bombe mi-"
    db "stenkelige sted-"
    db "er. Håper det   "
    db "hjelper! Ha det!"
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "You haven't     "
;    db "found the 5     "
;    db "Golden Leaves?  "
;    db "Try bombing sus-"
;    db "picious places. "
;    db "Hope that helps."
;    db "Bye!            "
;    db "CLICK!'@"

Dialog22A::
    db "«RRRING! RRRING!"
    db "Ja, det er Ul-  "
    db "rik! Du har ikke"
    db "funnet de 5     "
    db "gullbladene?    "
    db "Gå og skrem den "
    db "kråka ved slott-"
    db "et og se om det "
    db "hjelper! Ha det!"
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "You haven't     "
;    db "found the 5     "
;    db "Golden Leaves?  "
;    db "Go scare that   "
;    db "crow by the     "
;    db "castle and see  "
;    db "if that helps!  "
;    db "Bye!            "
;    db "CLICK!'@"

Dialog22B::
    db "«#####s reiser» "
    db "Vil du kikke i  "
    db "albumet ditt?   "
    db "    Se   La være<ask>"
;    db "'The Travels of "
;    db "#####' Do you   "
;    db "want to look at "
;    db "your album?     "
;    db "    Look Don't<ask>"

Dialog22C::
    db "Hvilket bilde   "
    db "vil du se? Bruk "
    db "<dpad> for å velge,  "
    db "og trykk så på  "
    db "A-knappen!@"
;    db "Which picture   "
;    db "would you like  "
;    db "to see? Use <dpad> to"
;    db "select, then    "
;    db "press the A     "
;    db "Button!@"

Dialog22D::
    db "Du er i nærheten"
    db "av Ørnetårnet.  "
    db "Vokt Dem for    "
    db "fuglen!@"
;    db "You are near the"
;    db "Eagle's Tower.  "
;    db "Beware of the   "
;    db "bird!@"

Dialog22E::
    db "Hei, #####. Du  "
    db "vet jeg elsker å"
    db "ta bilder. Ville"
    db "ikke dette gamle"
    db "slottet være et "
    db "flott motiv?@"
;    db "Hi, #####. You  "
;    db "know I love to  "
;    db "take pictures.  "
;    db "Wouldn't this   "
;    db "old castle make "
;    db "a great photo?@"

Dialog22F::
Dialog230::
    db "Hæ? Et nøkkel-  "
    db "hull her? Det   "
    db "står: «Hale-    "
    db "nøkkelhullet»@"
;    db "Hunh?  A keyhole"
;    db "here?  It says, "
;    db "'Tale Keyhole'@"

Dialog231::
    db "Hæ? Et nøkkel-  "
    db "hull her? Det   "
    db "står: «Slim-    "
    db "nøkkelhullet»@"
;    db "Hunh?  A keyhole"
;    db "here?  It says, "
;    db "'Slime Keyhole'@"

Dialog232::
    db "Hæ? Et nøkkel-  "
    db "hull her? Det   "
    db "står: «Ulke-    "
    db "nøkkelhullet»@"
;    db "Hunh?  A keyhole"
;    db "here?  It says, "
;    db "'Angler Keyhole'@"

Dialog233::
    db "Hæ? Et nøkkel-  "
    db "hull her? Det   "
    db "står: «Fugle-   "
    db "nøkkelhullet»@"
;    db "Hunh?  A keyhole"
;    db "here?  It says, "
;    db "'Bird Keyhole'@"

Dialog234::
    db "Hæ? Et nøkkel-  "
    db "hull her? Det   "
    db "står: «Ansikts- "
    db "nøkkelhullet»@"
;    db "Hunh?  A keyhole"
;    db "here?  It says, "
;    db "'Face Keyhole'@"

Dialog235::
    db "Noen, HJELP!@"
;    db "Somebody, HELP!@"

Dialog236::
    db "Hei! #####! Noen"
    db "monstre satte   "
    db "meg her oppe!   "
    db "Hva skal jeg    "
    db "gjøre?! Jeg har "
    db "høydeskrekk!!@"
;    db "Hey!  #####!    "
;    db "Some monsters   "
;    db "put me up here! "
;    db "What should I   "
;    db "do?!  I'm afraid"
;    db "of heights!!@"

Dialog237::
    db "Jøss! Det var en"
    db "overraskelse!   "
    db "Takk, #####!@"
;    db "Yow!  That was a"
;    db "surprise! #####,"
;    db "thank you!@"

Dialog238::
    db "... ... ... ... "
    db "... ... ... ... "
    db "Du_… #####_… @"
;    db "... ... ... ... "
;    db "... ... ... ... "
;    db "Say... #####... @"

Dialog239::
    db "Øh_… Jeg vet    "
    db "ikke hvordan jeg"
    db "skal si dette_… "
    db "men_…@"
;    db "Uhh... I don't  "
;    db "know how to say "
;    db "this... but...@"

Dialog23A::
    db "Hæ?! Tarin??!   "
    db "... ... ... ... "
    db "Øh_… Glem det,  "
    db "jeg_… Jeg må gå!@"
;    db "Hunh?!  Tarin??!"
;    db "... ... ... ... "
;    db "Uh... Nevermind,"
;    db "I... I gotta go!@"

Dialog23B::
    db "MAAAAAAARINNNN!!@"
;    db "MAAAAAAARINNNN!!@"

Dialog23C::
    db "Ingenting enda?!"
    db "Jeg er utålmodig"
    db "og vil ha de    "
    db "gullbladene lev-"
    db "ert snart! Mot  "
    db "som dette for-  "
    db "tjener et bilde,"
    db "synes du ikke?@ " ;ganske rar dialog. er visst ganske annerledes på japansk i følge den tjekkiske siden
;    db "Nothing yet?! I "
;    db "grow tired of   "
;    db "waiting. I want "
;    db "those Golden    "
;    db "Leaves delivered"
;    db "soon!           "
;    db "Courage like    "
;    db "this deserves a "
;    db "photo, don't you"
;    db "think?@"

Dialog23D::
    db "Hei, Marin og   "
    db "#####! Tar dere "
    db "bilder? Dere bør"
    db "ta bilder av    "
    db "alle, inkludert "
    db "meg.@"
;    db "Hey, Marin and  "
;    db "#####! Are you  "
;    db "taking pictures?"
;    db "You should take "
;    db "pictures of     "
;    db "everyone,       "
;    db "including me.@"

Dialog23E::
    db "Jeg bruker dette"
    db "til å ta bilder."
    db "Er dere klare?  "
    db "Paddehaaaaaatt!@" ;noen bedre?
;    db "I use this to   "
;    db "take pictures.  "
;    db "Are you ready?  "
;    db "Say 'mushroom!'@"

Dialog23F::
    db "OK, det var det."
    db "Jeg går hjem nå.@"
;    db "OK, I'm done.   "
;    db "I'll go home    "
;    db "now.@"

Dialog240::
    db "«RRRING! RRRING!"
    db "Det er Ulrik! Å,"
    db "jeg hørte fra   "
    db "bestemor at det "
    db "er noe skjult   "
    db "bak fossen i    "
    db "Tipptopp-       "
    db "fjellene.       "
    db "Hjelper det deg?"
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "This is Ulrira! "
;    db "Oh, I heard from"
;    db "grandma that    "
;    db "there is some-  "
;    db "thing hidden    "
;    db "behind the falls"
;    db "in the Tal Tal  "
;    db "Mountains.  Does"
;    db "that help?  Bye!"
;    db "CLICK!'@"

Dialog241::
    db "«RRRING! RRRING!"
    db "Ulrik her_… Ja, "
    db "da jeg var kun  "
    db "en pjokk, husker"
    db "jeg at jeg så et"
    db "høyt tårn i     "
    db "fjellene! Du bør"
    db "dra dit! Er det "
    db "til hjelp for   "
    db "deg? Ha det bra!"
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira here...  "
;    db "Yes, when I was "
;    db "just a lad, I   "
;    db "recall seeing a "
;    db "high tower in   "
;    db "the mountains!  "
;    db "You should go   "
;    db "there!  Is that "
;    db "helpful for you?"
;    db "Bye! CLICK!'@"

Dialog242::
    db "«RRRING! RRRING!"
    db "Hallo, det er   "
    db "Ulrik som snakk-"
    db "er! #####, det  "
    db "er på tide at du"
    db "går egget i møte"
    db "på Tindeggen!   "
    db "Vær forsiktig,  "
    db "#####! Ha det!  "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hello, this is  "
;    db "Ulrira speaking!"
;    db "#####, it's time"
;    db "for you to face "
;    db "the Egg on Mt.  "
;    db "Tamaranch!  Be  "
;    db "careful, #####! "
;    db "Bye!  CLICK!'@"

Dialog243::
    db "«RRRING! RRRING!"
    db "Dette er Ulrik! "
    db "Du har gått deg "
    db "bort i egget?   "
    db "Hmmmm. Nei, den "
    db "saken kan jeg   "
    db "ikke hjelpe deg "
    db "med. Hva med    "
    db "biblioteket? Og "
    db "du, ikke slutt å"
    db "ringe meg bare  "
    db "fordi jeg ikke  "
    db "visste ett lite "
    db "svar! KLIKK!»@"    
;    db "'BRRING! BRRING!"
;    db "This is Ulrira! "
;    db "You're lost in  "
;    db "the Egg?  Hmmmm."
;    db "No sir, I can't "
;    db "help you on that"
;    db "one.  How about "
;    db "the library?    "
;    db "And hey, don't  "
;    db "stop calling me "
;    db "because I didn't"
;    db "know one little "
;    db "answer!  CLICK!'@"

Dialog244::
    db "«RRRING! RRRING!"
    db "Ulrik til       " 
    db "tjeneste! Å? Du "
    db "burde ta VovVov "
    db "hjem nå, Madam  "
    db "Mjau-Mjau ville "
    db "sette pris på   "
    db "det! Ha det bra!"
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira at your  "
;    db "service!  Oh?   "
;    db "You should take "
;    db "BowWow home now,"
;    db "Madam MeowMeow  "
;    db "would appreciate"
;    db "it! Bye! CLICK!'@"

Dialog245::
    db "«RRRING! RRRING!"
    db "Dette er Ulrik! "
    db "Ja, du begynner "
    db "å like musikk?  "
    db "Vel, en frosk   "
    db "som heter Vort- "
    db "imer, som bor i "
    db "Skiltlabyrinten,"
    db "kan kanskje noen"
    db "nye sanger, men "
    db "han tar seg godt"
    db "betalt for å    "
    db "spille dem! Ha  "
    db "det bra! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Yeah, this is   "
;    db "Ulrira!  You are"
;    db "starting to like"
;    db "music, eh?      "
;    db "Well, a frog    "
;    db "named Mamu, who "
;    db "lives in the    "
;    db "Signpost Maze,  "
;    db "might know some "
;    db "new songs, but  "
;    db "he charges a lot"
;    db "to play them!   "
;    db "Bye!  CLICK!'@"

Dialog246::
    db "«RRRING! RRRING!"
    db "Hei, det er Ul- "
    db "rik! Du gjør det"
    db "bra! Din streben"
    db "vil snart være  "
    db "over_… Har du   "
    db "forresten besøkt"
    db "hønsehuset på   "
    db "fjellet? Det er "
    db "en hule med noe "
    db "viktig like ved."
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "You are doing   "
;    db "great!  Your    "
;    db "efforts will end"
;    db "soon... By the  "
;    db "way, have you   "
;    db "visited the Hen "
;    db "House on the    "
;    db "mountain?  There"
;    db "is a cave nearby"
;    db "with something  "
;    db "important in it."
;    db "Bye!  CLICK!'@"

Dialog247::
    db "«RRRING! RRRING!"
    db "Det er Ulrik som"
    db "snakker! Blir   "
    db "fiendene for    "
    db "sterke for deg? "
    db "I så fall bør du"
    db "samle alle sneg-"
    db "lehusene_… Bare "
    db "tro på deg selv "
    db "og gjør ditt    "
    db "beste! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira speaking!"
;    db "Are your enemies"
;    db "too strong for  "
;    db "you?  In that   "
;    db "case, you better"
;    db "collect all the "
;    db "Seashells...Just"
;    db "believe in your-"
;    db "self and do your"
;    db "best!  CLICK!'@"

Dialog248::
    db "«RRRING! RRRING!"
    db "Ulrik her!_…    "
    db "Kjør på! Du er  "
    db "der nesten! Jeg "
    db "heier på deg! Ha"
    db "det bra! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira here! ..."
;    db "Go for it!      "
;    db "You're almost   "
;    db "there! I'm pull-"
;    db "ing for you!    "
;    db "Bye!  CLICK!'@"

Dialog249::
    db "Ta gjerne et    "
    db "bilde av meg.   "
    db "I hvilken vinkel" 
    db "du vil!@"
;    db "Go ahead and    "
;    db "take a picture  "
;    db "of me. Any angle"
;    db "you like!@"

Dialog24A::
    db "Yahara? Det er  "
    db "en vei dit sør- "
    db "over, men du kan"
    db "kanskje ikke gå "
    db "gjennom hvis den"
    db "late hvalrossen "
    db "er i veien!@"
;    db "Yarna Desert?   "
;    db "There's a way to"
;    db "get there to the"
;    db "south, but you  "
;    db "might not be    "
;    db "able to get     "
;    db "through if that "
;    db "lazy walrus is  "
;    db "in the way!@"

Dialog24B::
    db "Ahhh_… Sukk_…   "
    db "På en så fin dag"
    db "trenger vi en   "
    db "sang fra Marin!@"
;    db "Ahhh... Sigh... "
;    db "On such a nice  "
;    db "day, we need a  "
;    db "song from Marin!@"

Dialog24C::
    db "Halla! Visste du"
    db "at Snutebu og   "
    db "Måsebu er       "
    db "søsterbyer? Ja, "
    db "selv om de ikke "
    db "er store nok til"
    db "å kalles byer_… "
    db "Uansett, jeg har"
    db "hørt fra en     "
    db "veldig god kilde"
    db "at de har et    "
    db "drømmmetempel i "
    db "Måsebu, og at   "
    db "det er noe bra  "
    db "der inne_…       "
    db "Er det sant?@"
;    db "Hey! Did ya know"
;    db "Animal Village  "
;    db "and Mabe Village"
;    db "are sister      "
;    db "cities?  Yes,   "
;    db "even though they"
;    db "aren't large    "
;    db "enough to be    "
;    db "called cities..."
;    db "Anyway, I heard "
;    db "from a very good"
;    db "source that they"
;    db "have a Dream    "
;    db "Shrine in Mabe, "
;    db "and that it has "
;    db "something good  "
;    db "inside...  Is   "
;    db "that true?@"

Dialog24D::
    db "Jeg kan ikke dra"
    db "til Måsebu på   "
    db "grunn av alle   "
    db "monstrene. Jeg  "
    db "håper det går   "
    db "bra med Marin.@"
;    db "I can't go to   "
;    db "Mabe Village    "
;    db "because of all  "
;    db "the monsters.   "
;    db "I hope Marin    "
;    db "is all right.@"
