Dialog108::
    db "Hei! Det er meg,"
    db "fotografen!     "
    db "Du virker nys-  "
    db "gjerrig på      "
    db "Bestefar Ulrik.@"
;    db "Hi! It's me, the"
;    db "photographer!   "
;    db "You seem curious"
;    db "about Grandpa   "
;    db "Ulrira.@"

Dialog109::
    db "Jeg kaller dette"
    db "«##### oppdager "
    db "Bestefar Ulriks "
    db "hemmelighet»!@"
;    db "I'll call this  "
;    db "'##### Dis-     "
;    db "covers Ulrira's "
;    db "Secret!'@"

Dialog10A::
    db "Stikk av nå     "
    db "før han finner  "
    db "deg, #####.@    "
;    db "#####, now run  "
;    db "away before he  "
;    db "finds you.@"

Dialog10B::
    db "Jeg skal frem-  "
    db "kalle bildet nå."
    db "Kom innom og se "
    db "det senere, ok?@"
;    db "I'll go develop "
;    db "this. Come see  "
;    db "it later, OK?@"

Dialog10C::
    db "Jeg ELSKER å ta "
    db "bilder. Får jeg "
    db "lov til å ta et "
    db "bilde av deg?   "
    db "    Ja  Nei<ask>"
;    db "I just LOVE to  "
;    db "take pictures.  "
;    db "Will you let me "
;    db "take your       "
;    db "picture?        "
;    db "    YES  NO<ask>"

Dialog10D::
    db "Gå bakerst i    "
    db "rommet og still "
    db "deg opp foran   "
    db "bakteppet.@     "
;    db "Go to the back  "
;    db "of the room and "
;    db "stand in front  "
;    db "of the screen.@"

Dialog10E::
    db "Hei der! Jeg har"
    db "ikke tatt bilde "
    db "av deg ennå! Gå "
    db "tilbake og stå  "
    db "foran bakteppet!@"
;    db "Hey! I haven't  "
;    db "taken your      "
;    db "picture yet! Go "
;    db "back and stand  "
;    db "in front of the "
;    db "screen!@"

Dialog10F::
    db "Bildet skal hete"
    db "«Her står en    "
    db "modig mann».    "
    db "Smiiil!@"
;    db "I'll call this  "
;    db "'Here Stands A  "
;    db "Brave Man.'     "
;    db "Say cheese!@"

Dialog110::
    db "Uglestatuen for-"
    db "søker å si noe, "
    db "men du forstår  "
    db "ikke hva den    "
    db "sier fordi den  "
    db "mangler nebbet.@"
;    db "This owl statue "
;    db "is trying to say"
;    db "something, but  "
;    db "you can't       "
;    db "understand it   "
;    db "because it has  "
;    db "no beak.@"

Dialog111::
    db "'I've got what  "
    db "was inside this "
    db "box.  Come and  "
    db "get it, if you  "
    db "can!'  Master <skull>@"

Dialog112::
    db "Gulp!  You found"
    db "me!  You're a   "
    db "real pesky kid, "
    db "you know that?!@"

Dialog113::
    db "Arrgh!  I can't "
    db "beat you!  I'm  "
    db "outta here!@"

Dialog114::
    db "You again?!  You"
    db "keep going and  "
    db "going... I can't"
    db "outlast you!    "
    db "All right, let's"
    db "do it!@"

Dialog115::
    db "WOOF! Dig! RUFF!@"

Dialog116::
    db "You put the     "
    db "missing scale in"
    db "the mermaid     "
    db "statue!@"

Dialog117::
    db "Hey! Be more    "
    db "careful next    "
    db "time!@"

Dialog118::
    db "Hey, man!  When "
    db "you want to save"
    db "just push all   "
    db "the Buttons at  "
    db "once!  Uhh...   "
    db "Don't ask me    "
    db "what that means,"
    db "I'm just a kid!@"

Dialog119::
    db "Well, it seems  "
    db "that after you  "
    db "save, you will  "
    db "start at the    "
    db "last door you   "
    db "went through... "
    db "I'm not really  "
    db "sure why that is"
    db "'cause I'm just "
    db "a kid!@"

Dialog11A::
    db "I heard that you"
    db "can press SELECT"
    db "to look at the  "
    db "island map...   "
    db "But, I don't    "
    db "understand what "
    db "they mean by    "
    db "that...@"

Dialog11B::
    db "When you're     "
    db "running out of  "
    db "Hearts, you'd   "
    db "better enter a  "
    db "house or cave..."
    db "Why?  I have no "
    db "idea, I'm just a"
    db "kid!@"

Dialog11C::
    db "Hey, dude! What "
    db "do you think of "
    db "Marin?  Uhh...  "
    db "I don't know,   "
    db "I'm just a kid!@"

Dialog11D::
    db "Where are you   "
    db "from, brother?  "
    db "...Outside the  "
    db "island?  What is"
    db "'outside?'  I've"
    db "never thought   "
    db "about it...@"

Dialog11E::
    db "The giant egg on"
    db "top of Tamaranch"
    db "Mountain?  They "
    db "say the Wind    "
    db "Fish is sleeping"
    db "inside of it... "
    db "Why?  I don't   "
    db "know either...@"

Dialog11F::
    db "Dude!  You're   "
    db "asking me when  "
    db "we started to   "
    db "live on this    "
    db "island?  What do"
    db "you mean by     "
    db "'when?'  Whoa!  "
    db "The concept just"
    db "makes my head   "
    db "hurt!@"

Dialog120::
    db "Marin? She likes"
    db "to go stare at  "
    db "the ocean all by"
    db "herself...  Why?"
    db "Hey, I'm just a "
    db "kid, don't ask  "
    db "me!@"

Dialog121::
    db "Hey... Where're "
    db "you two going   "
    db "together?  Hunh?"
    db "Uh, I didn't    "
    db "mean anything..."
    db "I'm just a kid!@"

Dialog122::
    db "Hey hey, bro!   "
    db "About the Dream "
    db "Shrine there... "
    db "They say there's"
    db "something good  "
    db "inside... ...   "
    db "I better not say"
    db "anything else   "
    db "as I'm just a   "
    db "kid!@"

Dialog123::
    db "Hunh?!  Marin's "
    db "not with you?   "
    db "What happened to"
    db "her?@"

Dialog124::
    db "WHOA! That's a  "
    db "big one! Hey,   "
    db "photo guy! Can  "
    db "you take a      "
    db "picture of this?@"

Dialog125::
    db "I have a        "
    db "feelin' that    "
    db "I'll catch a big"
    db "fish again.@"

Dialog126::
    db "If you keep me a"
    db "secret, I'll    "
    db "tell you some-  "
    db "thing useful.   "
    db "Go to Toronbo   "
    db "Shores, use the "
    db "magnifying glass"
    db "and you will    "
    db "find someone    "
    db "like me.@"

Dialog127::
    db "Tsk tsk...  What"
    db "a shame...@"

Dialog128::
    db "Oh thank you!   "
    db "You are indeed a"
    db "generous person!"
    db "Ah!  I will give"
    db "you this in     "
    db "return!@"

Dialog129::
    db "You traded your "
    db "<yoshi> for <ribbon>!  Maybe "
    db "you can trade   "
    db "the ribbon for  "
    db "something else!@"

Dialog12A::
    db "Because they all"
    db "look alike, even"
    db "I am sometimes  "
    db "confused. . .   "
    db "By the way, my  "
    db "baby wants a    "
    db "Yoshi Doll.     "
    db "I saw one at the"
    db "Trendy Game,    "
    db "but I couldn't  "
    db "get it.@"

Dialog12B::
    db "Oh!  Will you   "
    db "give that doll  "
    db "to my baby?!    "
    db "    Yes  No<ask>"

Dialog12C::
    db "Because they all"
    db "look alike, even"
    db "I am sometimes  "
    db "confused...     @"

Dialog12D::
    db "Ahem!  Really, I"
    db "must insist that"
    db "you not bring   "
    db "that awful beast"
    db "in here!  Leave "
    db "that creature   "
    db "outside and then"
    db "we can talk!    "
    db "Good Bye!@"

Dialog12E::
    db "You want to know"
    db "about that      "
    db "ghost? I'll bet "
    db "he's happy      "
    db "thanks to you.  "
    db "Are you ready   "
    db "for a picture?@"

Dialog12F::
    db "Ho ho ho!       "
    db "I really appre- "
    db "ciate what you  "
    db "did for my poor,"
    db "precious BowWow!"
    db "You are such a  "
    db "nice boy!  How  "
    db "can I ever repay"
    db "you?  I know... "
    db "  SMOOOOOOOCH!  "
    db "You got a reward"
    db "from Madam Meow-"
    db "Meow... ... ... "
    db "L-l-lucky!@"

Dialog130::
    db "Ho ho ho!  My   "
    db "BowWow is so    "
    db "proud of his    "
    db "fine fur coat!@"

Dialog131::
    db "AIEEEEEEEE!     "
    db "It's terrrrible!"
    db "My BowWow was   "
    db "dognapped by... "
    db "Mo-mo-MOBLINS!! "
    db "OHHH!  AHHHH!   "
    db "Please! Somebody"
    db "help my poor    "
    db "BowWow!!@"

Dialog132::
    db "Oh thank you!   "
    db "I'm so happy you"
    db "brought my baby "
    db "back! Now, would"
    db "you be a dear   "
    db "and take him for"
    db "a walk? It would"
    db "really help me  "
    db "out a lot!  You "
    db "will?!  Thanks!@"

Dialog133::
    db "Well... I pretty"
    db "much stick to   "
    db "myself, me and  "
    db "my letters...   "
    db "My name's Write!"
    db "The only thing I"
    db "don't like about"
    db "my hobby is that"
    db "I never receive "
    db "a response...@"

Dialog134::
    db "What's this?!  A"
    db "letter for me?! "
    db "I'm so happy!   "
    db "...And look! The"
    db "letter came with"
    db "a photograph!@"

Dialog135::
    db "Mmm... She's so "
    db "beautiful...    "
    db "I must give you "
    db "something for   "
    db "your trouble... "
    db "Hmm...  Well, it"
    db "looks like all I"
    db "have is this    "
    db "broom... how'll "
    db "that be?        "
    db "    Fine No...<ask>"

Dialog136::
    db "You got a Broom "
    db "as your reward  "
    db "from Mr. Write! "
    db "But that photo  "
    db "was not of...@"

Dialog137::
    db "Please! I really"
    db "must insist you "
    db "have this <broom>!    "
    db "    Okay No Way<ask>"

Dialog138::
    db "Oh boy!  Letter "
    db "writing is such "
    db "a great hobby!@"

Dialog139::
    db "Hello!  I'm     "
    db "writing back to "
    db "Christine now!@"

Dialog13A::
    db "Salutations!    "
    db "You wouldn't    "
    db "know by the look"
    db "of me, but I    "
    db "used to live in "
    db "the castle! My  "
    db "servants went   "
    db "berserk and I   "
    db "was forced to   "
    db "flee to my      "
    db "villa... So, you"
    db "want the key to "
    db "Ukuku Prairie,  "
    db "do you?  I may  "
    db "be able to help "
    db "you...  Let's   "
    db "make... a deal, "
    db "shall we? I want"
    db "you to retrieve "
    db "the Golden Leaf "
    db "I left behind in"
    db "the castle when "
    db "I fled...       "
    db "    Okay No Way<ask>"

Dialog13B::
    db "I am impressed. "
    db "There are five  "
    db "leaves in all.  "
    db "Remember to buy "
    db "a shovel on your"
    db "way back.@"

Dialog13C::
    db "Well, I never!  "
    db "I thought you   "
    db "looked cowardly,"
    db "but...  Please, "
    db "leave me... just"
    db "get out here!@"

Dialog13D::
    db "Ahh!  Tres Bien!"
    db "I see you have  "
    db "recovered all of"
    db "the leaves! Now,"
    db "move this box   "
    db "and you will    "
    db "find your       "
    db "reward!@"

Dialog13E::
    db "I am forever in "
    db "your debt for   "
    db "getting my      "
    db "leaves back!@"

Dialog13F::
    db "Ah!  Bonjour!   "
    db "#####, for the  "
    db "love of justice,"
    db "and my own sake,"
    db "you must find   "
    db "all the leaves!@"

Dialog140::
    db "Eh_… Em_… Ehem_…"
    db "Hvordan skal jeg"
    db "si_… Vær snill  "
    db "og ring_…       "
    db "Utenfor_…       "
    db "Det virker som  "
    db "at gamle Ulrik  "
    db "er en innadvendt"
    db "fyr én til én_…@"
;    db "Er...Uh...Hmm..."
;    db "How to say...   "
;    db "Please call...  "
;    db "Outside...  ... "
;    db "It seems that   "
;    db "old man Ulrira  "
;    db "is a shy guy,   "
;    db "in person...@"

Dialog141::
    db "«RRRING! RRRING!"
    db "Hallo!  Det er  "
    db "meg, Ulrik! Spør"
    db "meg om hva du   "
    db "vil om øya! Hvis"
    db "du går deg vill "
    db "er det bare å   "
    db "ringe! Ha det!  "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hello!  It's me,"
;    db "Ulrira!  Ask me "
;    db "anything about  "
;    db "the island!  If "
;    db "you get lost,   "
;    db "give me a call! "
;    db "Bye! CLICK!'@"

Dialog142::
    db "«RRRING! RRRING!"
    db "Hallo, det er   "
    db "Ulrik! _… Vel,  "
    db "de fleste sko-  "
    db "bolder bor i Den"
    db "mystiske skogen,"
    db "men det er også "
    db "noen i hulene i "
    db "Tipptopphøydene."
    db "Håper det var   "
    db "dette du lurte  "
    db "på! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hello, this is  "
;    db "Ulrira! ...Well,"
;    db "most Moblins    "
;    db "live in the Mys-"
;    db "terious Forest, "
;    db "but some live in"
;    db "the caves of Tal"
;    db "Tal Heights...  "
;    db "I hope that is  "
;    db "what you wanted "
;    db "to know! CLICK!'@"

Dialog143::
    db "«RRRING! RRRING!"
    db "Ja, du snakker  "
    db "med Ulrik. De   "
    db "ufordøyelige    "
    db "blomstene i Sym-"
    db "resumpen_… De   "
    db "blomstene er det"
    db "beste VovVov vet"
    db "å spise. Ta ham "
    db "med på tur dit  "
    db "da, vel? KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Yes, this is    "
;    db "Ulrira.  The    "
;    db "Indigestible    "
;    db "Flowers of      "
;    db "Goponga Swamp..."
;    db "Those flowers   "
;    db "are BowWow's    "
;    db "favorite.  Why  "
;    db "don't you take  "
;    db "him for a walk  "
;    db "there?  CLICK!'@"

Dialog144::
    db "«RRRING! RRRING!"
    db "Hei, det er     "
    db Ulrik! _… Har du "
    db "møtt alle på    "
    db "hele øya? Det er"
    db "en mann ved navn"
    db "Rikard som bor  "
    db "ved Jettegrytene"
    db "sørøst for      "
    db "landsbyen. Du   "
    db "burde stikke in-"
    db "nom! Det er alt "
    db "jeg kan fortelle"
    db "deg nå! "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "...Have you met "
;    db "everyone on the "
;    db "island?  There's"
;    db "a man named     "
;    db "Richard who     "
;    db "lives in Pothole"
;    db "Field, southeast"
;    db "of the village. "
;    db "Why not pay him "
;    db "a visit?  That's"
;    db "all I can tell  "
;    db "you for now!    "
;    db "Bye!  CLICK!'@"

Dialog145::
    db "«RRRING! RRRING!"
    db "Gamle Ulrik her!"
    db "_… Liker du     "
    db "bananer? Prøv å "
    db "snakke med folk "
    db "i landsbyen     "
    db "igjen!          "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Old man Ulrira  "
;    db "here! ...Do you "
;    db "like bananas?   "
;    db "Try talking to  "
;    db "people in the   "
;    db "village again!  "
;    db "Bye!  CLICK!'@"

Dialog146::
    db "«RRRING! RRRING!"
    db "Ulrik her! Vet  "
    db "du, det er et   "
    db "bibliotek i     "
    db "landsbyen som   "
    db "har masse infor-"
    db "masjon til deg! "
    db "Snakkes!        "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira speaking!"
;    db "You know, there "
;    db "is a library in "
;    db "the village that"
;    db "might have some "
;    db "good information"
;    db "for you!  Talk  "
;    db "to you later!   "
;    db "CLICK!'@"

Dialog147::
    db "«RRRING! RRRING!"
    db "Ja, det er      "
    db "Ulrik! Sier du  "
    db "at du ikke har  "
    db "funnet alle fem "
    db "gullbladene? Du "
    db "får spørre kråka"
    db "på slottet. Jeg "
    db "tipper han kan  "
    db "hjelpe. Ha det! "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "You say you     "
;    db "haven't found   "
;    db "all five Golden "
;    db "Leaves? Go ask  "
;    db "the crow at the "
;    db "castle. I'm sure"
;    db "he can help you."
;    db "Bye!            "
;    db "CLICK!'@"

Dialog148::
    db "«RRRING! RRRING!"
    db "Ulrik her! _…   "
    db "Spade_… Har du  "
    db "kjøpt en spade? "
    db "Kanskje du kan  "
    db "finne noe hvis  "
    db "du graver her og"
    db "der! Ha det!    "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira here! ..."
;    db "Shovel...  Did  "
;    db "you purchase a  "
;    db "shovel?  You may"
;    db "find something  "
;    db "if you dig here "
;    db "and there!  Bye!"
;    db "CLICK!'@"

Dialog149::
    db "«RRRING! RRRING!"
    db "Ja, det er      "
    db "Ulrik! Hula på  "
    db "Ulele-sletta er "
    db "nøkkelen! Ja,   "
    db "jeg mener nøk-  "
    db "kelhula, eller  "
    db "Nøkkelkjelleren,"
    db "da! Ha det! "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "The cave in the "
;    db "Ukuku Prairie is"
;    db "the key!  Yes, I"
;    db "mean the key    "
;    db "cave, no pun    "
;    db "intended!  Bye! "
;    db "CLICK!'@"

Dialog14A::
    db "«RRRING! RRRING!"
    db "Hei, dette er   "
    db "Ulrik! Sørøst på"
    db "øya, i Yahara-  "
    db "ørkenen, finner "
    db "du noe som heter"
    db "Ulkenøkkelen.   "
    db "Hmmm_… Hvor mye "
    db "tydeligere må   "
    db "jeg si det?     "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, this is     "
;    db "Ulrira!  In the "
;    db "Yarna Desert,   "
;    db "which is located"
;    db "in the southeast"
;    db "of the island,  "
;    db "you will find   "
;    db "something called"
;    db "the Angler Key. "
;    db "Hmmm... How much"
;    db "more obvious do "
;    db "I have to be?   "
;    db "Bye! CLICK!'@"

Dialog14B::
    db "«RRRING! RRRING!"
    db "Dette er Ulrik! "
    db "Nå hjemsøkes du "
    db "av et spøkelse? "
    db "Vel, hva med å  "
    db "ta ham med dit  "
    db "han har lyst til"
    db "å dra?          "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "This is Ulrira! "
;    db "Now you're being"
;    db "haunted by a    "
;    db "ghost?! Well,   "
;    db "how about taking"
;    db "him where he    "
;    db "wants to go?    "
;    db "Bye! CLICK!'@"

Dialog14C::
    db "«RRRING! RRRING!"
    db "Hei, det er     "
    db "Ulrik! Marulkens"
    db "munn er vidåpen?"
    db "Det høres ut som"
    db "et perfekt sted "
    db "å dykke!        "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "The Catfish's   "
;    db "mouth is wide   "
;    db "open?  It sounds"
;    db "like a great    "
;    db "place to dive!  "
;    db "Bye!  CLICK!'@"

Dialog14D::
    db "«RRRING! RRRING!"
    db "Ulrik her! _… _…"
    db "Har du vært i   "
    db "Ansiktstempelet?"
    db "Det ligger nord "
    db "for Snutebu. Det"
    db "er en veldig    "
    db "interessant     "
    db "ruin_… KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira here! ..."
;    db "Have you been to"
;    db "the Face Shrine?"
;    db "It is north of  "
;    db "Animal Village. "
;    db "That is a very  "
;    db "interesting     "
;    db "ruin... CLICK!'@"

Dialog14E::
    db "«RRRING! RRRING!"
    db "Hei, det er     "
    db "Ulrik! Har du   "
    db "høst om Måsebus "
    db "flygende hane?  "
    db "I de gode, gamle"
    db "dager pleide den"
    db "å la oss fly når"
    db "vi holdt den    "
    db "over hodet_… Nå "
    db "ligger den      "
    db "begravd under   "
    db "værhanen_… Var  "
    db "det nyttig for  "
    db "deg? Håper det! "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "Have you heard  "
;    db "of the Flying   "
;    db "Rooster of Mabe "
;    db "Village?  In the"
;    db "good old days,  "
;    db "it used to give "
;    db "us rides if we  "
;    db "held it above   "
;    db "our heads... Now"
;    db "it is lying     "
;    db "under the       "
;    db "Weathercock...  "
;    db "Is that useful  "
;    db "for you?  I hope"
;    db "so! Bye! CLICK!'@"

Dialog14F::
    db "«RRRING! RRRING!"
    db "Hei, det er     "
    db "Ulrik! Er hodet "
    db "til skilpadden  "
    db "i veien? Pust   "
    db "litt liv i den, "
    db "så beveger den  "
    db "seg! Det er helt"
    db "sant! Sant!     "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "The head of the "
;    db "turtle is in    "
;    db "your way?  Put  "
;    db "life into it and"
;    db "it will move!   "
;    db "It's true! True!"
;    db "Bye!  CLICK!'@"

Dialog150::
    db "   _… SUMP_…    "
    db "En sti åpner seg"
    db "i anemonene_…@" 
;    db "   ...SWAMP...  "
;    db " A path opens..."
;    db "in the blooms...@"

Dialog151::
    db "  _… SLETTE_…   "
    db "  _… SLETTE_…   "
    db "    Slettene    "
    db "    venter_…@"
;    db "  ...PRAIRIE... "
;    db "  ...PRAIRIE... "
;    db " The Prairie is "
;    db "     waiting...@"

Dialog152::
    db "   _… FOSS_…    "
    db "Det er skjult i "
    db "fossen_…@"
;    db "...WATERFALL... "
;    db "It is hidden in "
;    db "the waterfall...@"

Dialog153::
    db "   _… BUKT_…    "
    db "Veien din går   "
    db "inn i bukta_…@"
;    db "    ...BAY...   "
;    db "Your road goes  "
;    db "into the bay... @"

Dialog154::
    db "  _… TEMPEL_…   "
    db "En av øyas      "
    db "hemmeligheter i "
    db "tempelet_…@"
;    db "   ...SHRINE... "
;    db "An island secret"
;    db "in the shrine...@"

Dialog155::
    db "   _… FJELL_…   "
    db "Noe kaller      "
    db "_… fra fjellet_…"
    db "  mountains...@"
;    db " ...MOUNTAIN... "
;    db "Something calls "
;    db "  ...from the   "
;    db "  mountains...@"

Dialog156::
    db " _… LEIRGAUK_…  "
    db "Leirgaukens     "
    db "musikk fører_…@"
;    db "  ...OCARINA... "
;    db "The music of the"
;    db "Ocarina leads...@"

Dialog157::
    db "   _… EGG_…     "
    db "Egget på fjellet"
    db "kaller på deg!@"
;    db "    ...EGG....  "
;    db "The Egg on the  "
;    db "mountain calls!@"

Dialog158::
Dialog159::
    db "Da får DU feie  "
    db "denne øya!@"
;    db "Then YOU sweep  "
;    db "the island!@"

Dialog15A::
    db "YAHOO!   I'm    "
    db "fine, and you?!@"

Dialog15B::
    db "YAHOO!  I worked"
    db "too hard and now"
    db "my broom is worn"
    db "to the handle!@"

Dialog15C::
    db "YAHOO!  YAHOO!  "
    db "A new broom?!   "
    db "For me?  It is, "
    db "isn't it?!      "
    db "    Yes  No<ask>"

Dialog15D::
    db "Okei! Da kan du "
    db "få denne fiske- "
    db "kroken jeg fant "
    db "da jeg feide ved"
    db "elvebredden!@"
;    db "Okay!  In return"
;    db "you can have    "
;    db "this fishing    "
;    db "hook I found    "
;    db "when I swept by "
;    db "the river bank!@"

Dialog15E::
    db "Du byttet <broom> mot "
    db "fiskekroken <fishhook>!  "
    db "Hva kommer      "
    db "fiskekroken til "
    db "å bli til?@"
;    db "You exchanged <broom> "
;    db "for the fishing "
;    db "hook <fishhook>!  What   "
;    db "will the fishing"
;    db "hook become?@"

Dialog15F::
    db "YAHOO!  A new   "
    db "broom!  Superb!@"

Dialog160::
    db "Kiiiki!  What?! "
    db "All right, mutt!"
    db "Let's battle!!@"

Dialog161::
    db "Chi-kiita! Chi- "
    db "kiita!  Kiki the"
    db "monkey!  Hungry!"
    db "Kiki the monkey!@"

Dialog162::
    db "    <bananas>!    <bananas>!    "
    db "Oooh! Ooh! Kiki!"
    db "Monkeys!  Come! "
    db "Repay him! Kiki!@"

Dialog163::
    db "Monkey business!"
    db "Done!  Bye bye! "
    db "Oooh!  Kiki!@"

Dialog164::
    db "Du fant en pinne"
    db "en av apene la  "
    db "igjen_… Du tar  "
    db "den!@"
;    db "You found a     "
;    db "stick a monkey  "
;    db "left behind...  "
;    db "You take it!@"

Dialog165::
    db "    <bananas>!    <bananas>!    "
    db "  Oooh!  Oooh!  "
    db " Gi til Julius?!"
    db "    Ja   Nei!<ask>"
;    db "    <bananas>!    <bananas>!    "
;    db "  Oooh!  Oooh!  "
;    db " Give to Kiki!? "
;    db "    Yes  No!<ask>"

Dialog166::
    db "Du har virkelig "
    db "ingen anelse om "
    db "hvordan man     "
    db "snakker til en  "
    db "dame, har du    "
    db "vel? Du skulle  "
    db "hatt med deg    "
    db "blomster eller  "
    db "noe, da ville   "
    db "jeg vært mer    "
    db "tilbøyelig til å"
    db "snakke med deg_…"
    db "I mitt tilfelle "
    db "ville Hibiscus  " 
    db "vært det beste_…@"
;    db "You don't know  "
;    db "the proper      "
;    db "etiquette when  "
;    db "dealing with a  "
;    db "lady, do you?   "
;    db "You should have "
;    db "brought flowers "
;    db "or something,   "
;    db "then I might be "
;    db "more inclined to"
;    db "talk with you..."
;    db "Oh yes, in my   "
;    db "case, hibiscus  "
;    db "are best...@"

Dialog167::
    db "Å, du tok med en"
    db "hibiscus til    "
    db "meg! Så søtt!   "
    db "Vel, siden du er"
    db "slik en sjarmør,"
    db "kan du gjøre meg"
    db "en tjeneste? Vil"
    db "høre?"
    db "    Ja   Nei<ask>"
;    db "Oh, you brought "
;    db "me a hibiscus!  "
;    db "How sweet! Well,"
;    db "since you are   "
;    db "such a gentleman"
;    db "I have a request"
;    db "to make of you. "
;    db "Will you listen?"
;    db "    Yes  No<ask>"

Dialog168::
    db "Jeg trenger å få"
    db "levert dette    "
    db "brevet til en   "
    db "William som bor "
    db "ved kanten av   "
    db "den mystiske    "
    db "skogen, er du   "
    db "snill!@"
;    db "I would like you"
;    db "to take this    "
;    db "letter to a Mr. "
;    db "Write who lives "
;    db "on the border of"
;    db "the Mysterious  "
;    db "Forest, please!@"

Dialog169::
    db "_… Jaha? Og jeg "
    db "som trodde du   "
    db "var en galant   "
    db "herre_…@"
;    db "...Is that so?  "
;    db "And I thought   "
;    db "you were a      "
;    db "gentleman...@"

Dialog16A::
    db "Du byttet <flower2> mot "
    db "en geits brev <letter>!"
    db "_… Kjempebra!?@"
;    db "You traded <flower2> for"
;    db "a goat's letter "
;    db "<letter>!  ...Great!?@"

Dialog16B::
    db "Vet du, noen    "
    db "ganger klarer   "
    db "jeg ikke å mot- "
    db "stå fristelsen  "
    db "og spise papir, "
    db "selv hvis det er"
    db "et brev til min "
    db "kjære William_… "
    db "Så flaut!@"
;    db "You know, some- "
;    db "times I can't   "
;    db "help eating a   "
;    db "delicious piece "
;    db "of paper, even  "
;    db "if it's a letter"
;    db "to my darling   "
;    db "Mr. Write... How"
;    db "embarrassing!@"

Dialog16C::
    db "Du reddet Vov-  "
    db "Vov! For et gru-"
    db "fullt beist!@"
;    db "You've saved    "
;    db "BowWow!  What a "
;    db "fearsome beast!@"

Dialog16D::
    db "Wow! Hanen har  "
    db "gjenoppstått!   "
    db "Han virker      "
    db "veldig vennlig!@"
;    db "Wow! The Rooster"
;    db "has recovered!  "
;    db "He seems very   "
;    db "friendly!@"

Dialog16E::
    db "«RRRING! RRRING!"
    db "Ja, det er      "
    db "Ulrik! Kona mi  "
    db "dro til Snutebu "
    db "og lot meg være "
    db "igjen alene. Kan"
    db "du si at hun må "
    db "komme hjem så   "
    db "fort hun er     "
    db "ferdig med å    "
    db "feie?           "
    db "Ha det!         "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "My wife went to "
;    db "the Animal      "
;    db "Village and left"
;    db "me all alone.   "
;    db "Can you tell    "
;    db "her to come home"
;    db "as soon as she  "
;    db "is done         "
;    db "cleaning?       "
;    db "Bye!            "
;    db "CLICK!'@"

Dialog16F::
    db "Bestemor er ikke"
    db "her. Hun er i   "
    db "Snutebu. Det var"
    db "dét bestefar    "
    db "Ulrik sa på     "
    db "telefonen!@"
;    db "Grandma's not   "
;    db "here. She's in  "
;    db "the Animal      "
;    db "Village. That's "
;    db "what Grandpa    "
;    db "Ulrira said on  "
;    db "the phone!@"

Dialog170::
    db "Jepp, Fartein   "
    db "gikk seg bort,  "
    db "akkurat som han "
    db "sa! Nå er jeg   "
    db "så skrubbsulten "
    db "at jeg ikke kan "
    db "røre meg! Har du"
    db "noe proviant?   "
    db "    Ja   Niks<ask>"
;    db "Yep, Papahl got "
;    db "lost, just like "
;    db "he said!  Now, I"
;    db "am so famished I"
;    db "can't move!  Can"
;    db "you give me some"
;    db "vittles?        "
;    db "    Yes  Nope<ask>"

Dialog171::
    db "Du er en iskald "
    db "kis_…@"
;    db "You're one cold "
;    db "hombre...@"

Dialog172::
    db "Denne <pineapple> er helt "
    db "nydelig! Jeg    "
    db "skal spise <pineapple>  "
    db "med én gang!    "
    db " Bon Appetit!@"
;    db "This <pineapple> is so    "
;    db "delicious!  I'm "
;    db "going to eat the"
;    db "<pineapple> right now!    "
;    db " Bon Appetit!@"

Dialog173::
    db "AH! Dette er    "
    db "ikke ment som en"
    db "belønning_… Her,"
    db "ta denne <flower2>! Det "
    db "Det er en       "
    db "hibiscus!@"
;    db "AH!  This isn't "
;    db "meant to be a   "
;    db "reward...  Here,"
;    db "take this <flower2>!    "
;    db "It's a hibiscus!@"

Dialog174::
    db "Du byttet <pineapple> mot "
    db "en <flower2>!@"
;    db "You traded the <pineapple>"
;    db "for the <flower2>!@"

Dialog175::
    db "Nydelig! Nam!   "
    db "Nå er jeg full  "
    db "av energi!@"
;    db "Delicious!  Yum!"
;    db "I'm filled with "
;    db "energy, now!@"

Dialog176::
    db "Jeg må bare si  "
    db "takk igjen!@"
;    db "I've got to say,"
;    db "thanks again!@"

Dialog177::
    db "Jupp, Fartein   "
    db "gikk seg bort,  "
    db "akkurat som han "
    db "sa! Nå er jeg   "
    db "så skrubbsulten "
    db "at jeg ikke kan "
    db "røre meg! Har du"
    db "noen rasjoner?  "
    db "    Ja   Niks<ask>"
;    db "Yep, Papahl got "
;    db "lost, just like "
;    db "he said!  Now, I"
;    db "am so famished I"
;    db "can't move!  Can"
;    db "you give me some"
;    db "vittles?        "
;    db "    Nope Can't<ask>"

Dialog178::
    db "She's had an    "
    db "awful tragedy   "
    db "in the house    "
    db "across the way! "
    db "It's just awful,"
    db "and all I can do"
    db "is sweep!@"

Dialog179::
    db "Jeg er dette    "
    db "husets sjel. Jeg"
    db "har ventet på en"
    db "som kunne over- "
    db "vinne mørket.   "
    db "Finn alle de    "
    db "hemmelige skjel-"
    db "lene og gå gjen-"
    db "nom åpningen for"
    db "å få det        "
    db "ultimate sverd!@"
;    db "I am the spirit "
;    db "of the mansion. "
;    db "I have been     "
;    db "waiting for     "
;    db "someone to      "
;    db "overcome the    "
;    db "darkness. Find  "
;    db "all the secret  "
;    db "shells and go   "
;    db "through the     "
;    db "gate to receive "
;    db "the ultimate    "
;    db "sword!@"
; Forslag til synonymer for «ultimate» tas imot med thx

Dialog17A::
    db "Hmmm. Ingen ting"
    db "skjedde. Du har "
    db "nok ikke nok    "
    db "skjell.@"
;    db "Hmmm. No        "
;    db "response. You   "
;    db "must not have   "
;    db "enough shells.@"

Dialog17B::
Dialog17B::
    db "Min jobb her er "
    db "fullført.@"
;    db "My job here     "
;    db "is finished.@"

Dialog17C::
    db "Hei du! Har du  "
    db "vært i foto-    "
    db "butikken i Tipp-"
    db "topphøydene?    "
    db "Ungdommer liker "
    db "å gå dit og ta  "
    db "bilder av seg   "
    db "selv. Virker    "
    db "litt rart, spør "
    db "du meg.@"
;    db "Hey you! Have   "
;    db "you been to the "
;    db "Camera Shop in  "
;    db "Tal Tal Heights?"
;    db "Iyoung people   "
;    db " like to go ther"
;    db "eand take       "
;    db " pictures of    "
;    db " themselves.    "
;    db " Seems kinda    "
;    db " funny to me.@"

Dialog17D::
    db "Kom inn og få en"
    db "suvenir i form  "
    db "av et bilde!@"
;    db "Step right up   "
;    db "and get your    "
;    db "souvenir photo!@"

Dialog17E::
    db "Godt jobba! Bruk"
    db "det på fiendene "
    db "dine og se hva  "
    db "som skjer. Hvis "
    db "du går tom, er  "
    db "det bare å dra  "
    db "til skogen og   "
    db "plukke mer sopp,"
    db "så skal jeg lage"
    db "mer.@"
;    db "Good job!       "
;    db "Use it on your  "
;    db "enemies and see "
;    db "what happens.   "
;    db "If you run out, "
;    db "go to the for-  "
;    db "est, pick some  "
;    db "mushrooms, and  "
;    db "I will make you "
;    db "more.@"

Dialog17F::
   db ". . . . ! Jeg kan"
    db "ikke røre meg!  "
    db "Men det går bra."
    db "Det lille       "
    db "sverdet ditt kan"
    db "ikke knuse denne"
    db "flaska!@" 
;    db ". . . .! I can't"
;    db "move! But I am  "
;    db "still all right."
;    db "Your little     "
;    db "sword won't     "
;    db "break this      "
;    db "bottle!@"

Dialog180::
    db "Sminke! Smykker!"
    db "Kjoler! Jeg vil "
    db "ha alt sammen!  "
    db "Sukk_… Og noen  "
    db "aksessoarer     "
    db "hadde vært      "
    db "fint_…@"
;    db "Make-up! Jewels!"
;    db "Dresses!  I want"
;    db "it all!  Sigh..."
;    db "And some new    "
;    db "accessories     "
;    db "would be nice...@"

Dialog181::
    db "Sminke! Smykker!"
    db "Kjoler! Jeg vil "
    db "ha alt sammen!  "
    db "Sukk_… Og noen  "
    db "aksessoarer     "
    db "hadde vært      "
    db "fint_…          "
    db "Å! Den sløyfa!  "
    db "Jeg trenger den!"
    db "Vil du bytte den"
    db "mot hundemat?   "
    db "    Ja   Nei!<ask>"
;    db "Make-up! Jewels!"
;    db "Dresses!  I want"
;    db "it all!  Sigh..."
;    db "And some new    "
;    db "accessories     "
;    db "would be nice..."
;    db "Oh! That Ribbon!"
;    db "I need it!  Will"
;    db "you trade for my"
;    db "dog food?       "
;    db "    Yes  No!<ask>"

Dialog182::
    db "Du byttet <ribbon> mot "
    db "<dogfood>! Den er full  "
    db "av saftig kjøtt!@"
;    db "You exchanged <ribbon> "
;    db "for <dogfood>! It's full"
;    db "of juicy beef!@"

Dialog183::
    db "Heldig! Takk!   "
    db "Vel, her har du "
    db "<dogfood>!@"
;    db "Lucky!  Thanks! "
;    db "Well, here's    "
;    db "your <dogfood>!@"

Dialog184::
    db "Hæ?! Jeg kan    "
    db "ikke tro det! Du"
    db "er så slem!!@"
;    db "Eh?!  I can't   "
;    db "believe it!  You"
;    db "are the worst!!@"

Dialog185::
    db "Jeg er Mons,    "
    db "månefiskens     "
    db "barn! Har du en "
    db "leirgauk?       "
    db "    Ja   Nei<ask>"
;    db "I am Manbo,     "
;    db "child of the Sun"
;    db "Fish!  Have you "
;    db "got an Ocarina? "
;    db "    Yes  No<ask>"

Dialog186::
    db "Nei vel_… Blubb "
    db "Blubb Blupp!@"
;    db "Very well...    "
;    db "Glub Blub Bloop!@"

Dialog187::
    db "Ahaha! Da kan   "
    db "jeg lære deg    "
    db "sangen min!     "
    db "Blupp!@"
;    db "Ahaha!  Then I  "
;    db "can teach you my"
;    db "song! Bloop!@"

Dialog188::
    db "Du lærte Mons'  "
    db "Mambo! Du burde "
    db "spille den når  "
    db "du kommer deg   "
    db "opp av vannet!@"
;    db "You've learned  "
;    db "Manbo's Mambo!  "
;    db "When you get out"
;    db "of the water,   "
;    db "play it!@"

Dialog189::
    db "Jeg er Mons,    "
    db "månefiskens     "
    db "barn! Når du    "
    db "spiller mamboen "
    db "min kan du tele-"
    db "portere til     "
    db "Mons' pytt! Prøv"
    db " å spille denne "
    db "melodien i      "
    db "fangehull også! "
    db "Cha-cha-cha!@"
;    db "I am Manbo,     "
;    db "child of the Sun"
;    db "Fish!  When you "
;    db "play my Mambo,  "
;    db "you can warp to "
;    db "Manbo Pond!  Try"
;    db "this tune in the"
;    db "dungeons, too!  "
;    db "Cha-cha-cha!@"

Dialog18A::
    db "Aha_… Du har    "
    db "ingen leirgauk, "
    db "så_… Blubb!@"
;    db "Aha... You don't"
;    db "have an Ocarina,"
;    db "so...Glub glub!@"

Dialog18B::
    db "Kyllinger nå til"
    db "dags har ikke   "
    db "kampviljen de   "
    db "pleide å ha! I  "
    db "gamle dager     "
    db "kunne de fly,   "
    db "flaks flaks! Men"
    db "nå, se her!     "
    db "Klukk klukk!@"
;    db "Chickens these  "
;    db "days don't have "
;    db "the fighting    "
;    db "spirit they used"
;    db "to!  In the old "
;    db "days, they could"
;    db "fly, flap flap! "
;    db "But now, see?   "
;    db "Cluck cluck!@"

Dialog18C::
    db "Wow!  Utrolig!  "
    db "Den hanen der   "
    db "flyr faktisk!   "
    db "Det er akkurat  "
    db "som jeg sa, hæ? "
    db "Har du prøvd å  "
    db "holde ham over  "
    db "hodet? Klukk    "
    db "klukk!@"
;    db "Wow!  Amazing!  "
;    db "That rooster is "
;    db "actually flying!"
;    db "It's just like I"
;    db "said, eh?  Have "
;    db "you tried to    "
;    db "hold him over   "
;    db "your head? Cluck"
;    db "Cluck!@"

Dialog18D::
    db "Åååå!  Endelig! "
    db "Denne flygende  "
    db "hanen er den    "
    db "beste!@"
;    db "Wooo!  Finally! "
;    db "This flying     "
;    db "rooster is the  "
;    db "greatest!@"

Dialog18E::
    db "   Her hviler   "
    db "Den flyende hane@"
;    db " Here Sleeps The"
;    db " Flying Rooster@"

Dialog18F::
    db "Er det den hav- "
    db "frueshell? Jeg  "
    db "kan ikke bruke  "
    db "den nå. Jeg må  "
    db "jobbe med denne "
    db "tegning. Du kan "
    db "gå og gjøre     "
    db "ferdig den      "
    db "shtatue for meg.@"
;    db "Iz zat zee      "
;    db "Mermaid scale?  "
;    db "I can't use it  "
;    db "now. I have to  "
;    db "werk on zis     "
;    db "drawing. You    "
;    db "should go finish"
;    db "zee mermaid     "
;    db "statue for me.@"
