Dialog0A4::
    db "Du fikk Ansikts-"
    db "nøkkelen!@"
;    db "You've got the  "
;    db "Face Key!@"

Dialog0A5::
    db "Du fikk Fugle-  "
    db "nøkkelen!@"
;    db "You've got the  "
;    db "Bird Key!@"

Dialog0A6::
    db "Endelig fikk du "
    db "et kart! Trykk  "
    db "på START-knappen"
    db "for å se på det!@"
;    db "At last, you got"
;    db "a Map!  Press   "
;    db "the START Button"
;    db "to look at it!@"

Dialog0A7::
    db "Du fikk kom-    "
    db "passet! Nå kan  "
    db "du se hvor      "
    db "kistene og Mare-"
    db "rittet skjuler  "
    db "seg! Dette kom- "
    db "passet har en ny"
    db "egenskap: En    "
    db "tone forteller  "
    db "deg om en nøkkel"
    db "er gjemt i rom- "
    db "met du går inn  "
    db "i!@"
;    db "You've got the  "
;    db "Compass!  Now,  "
;    db "you can see     "
;    db "where the chests"
;    db "and Nightmare   "
;    db "are hidden! This"
;    db "Compass has a   "
;    db "new feature-- a "
;    db "tone will tell  "
;    db "you if a key is "
;    db "hidden in a room"
;    db "when you enter! @"

Dialog0A8::
    db "Du fant et      "
    db "steinnebb! La   "
    db "oss finne ugle- "
    db "statuen det     "
    db "hører til.@"
;    db "You found a     "
;    db "stone beak!     "
;    db "Let's find the  "
;    db "owl statue that "
;    db "belongs to it.@"

Dialog0A9::
    db "Du fikk Mare-   "
    db "rittnøkkelen!   "
    db "Nå kan du åpne  "
    db "døra til Mare-  "
    db "rittets reir!@"
;    db "You've got the  "
;    db "Nightmare's Key!"
;    db "Now you can open"
;    db "the door to the "
;    db "Nightmare's     "
;    db "Lair!@"

Dialog0AA::
    db "Du fant en liten"
    db "nøkkel! Med den "
    db "kan du åpne en  "
    db "låst dør.@"
;    db "You got a Small "
;    db "Key!  You can   "
;    db "open a locked   "
;    db "door.@"

Dialog0AB::
    db "   Du fikk 20   "
    db "     rupier!    "
    db "     Hurra!@"
;    db "   You got 20   "
;    db "     Rupees!    "
;    db "      JOY!@"

Dialog0AC::
    db "    Du fikk 50  "
    db "      rupier!   "
    db "    Veldig bra!@"
;    db "    You got 50  "
;    db "      Rupees!   "
;    db "    Very Nice!@"

Dialog0AD::
    db "   Du fikk 100  "
    db "     rupier!    "
    db " Hvilken glede!@"
;    db "   You got 100  "
;    db "     Rupees!    "
;    db "  You're Happy!@"

Dialog0AE::
    db "   Du fikk 200  "
    db "     rupier!    "
    db "Du er i ekstase!@"
;    db "   You got 200  "
;    db "     Rupees!    "
;    db "You're Ecstatic!@"

Dialog0AF::
    db "La meg være i   "
    db "fred! Jeg prøver"
    db "å sitte stille  "
    db "så Sjur kan male"
    db "meg!@"
;    db "Leave me alone! "
;    db "I'm trying to   "
;    db "sit still so    "
;    db "Schule can paint"
;    db "my portrait!@"

Dialog0B0::
    db "BZZZZZZ! BZZZZZ!"
    db "UTENFORZZTÅENDE!@"
;    db "BUZZZZZ! BUZZZZ!"
;    db "   OUTZZZIDER!  @"

Dialog0B1::
    db "ÆDDA BÆDDA!     "
    db "Du finner meg   "
    db "aldri! HA HA!@"
;    db "NEENER NEENER!  "
;    db "You can't find  "
;    db "me!  NYAH NYAH!@"

Dialog0B2::
    db "BLUBB! BLUBB!   "
    db "GULP!  GULP!    "
    db "BLRRRG!  MAAAT! "
    db "BLUUUUBB!  GULP!@"    
;    db "BLOOOP! BLOOOP! "
;    db "  GLUB!  GLUB!  "
;    db "OGGGH!  FOOOOD! "
;    db "BLOOOOP!  GLUB!@"

Dialog0B3::
    db "Ssså_… Du er den"
    db "utenforssstående"
    db "som har kommet  "
    db "for å vekke     "
    db "Vindfisssken_…  "
    db "TIII-HI-HIIIII! "
    db "Jeg skal ssspise"
    db "deg!@"
;    db "Ssso...you are  "
;    db "the outsssider, "
;    db "come to wake the"
;    db "Wind Fisssh...  "
;    db "KEEE-HEE-HEEEH! "
;    db "I shall eat you!@"

Dialog0B4::
    db "HO HO HO!       "
    db "Jeg er slemming-"
    db "en på menyen i  "
    db "dag!! HO HO HO!@"
;    db "HO HO HO!       "
;    db "I'm your bad guy"
;    db "this time!!     "
;    db "HO HO HO!@"

Dialog0B5::
    db "TSSSK, TSSSK!   "
    db "Det virker ikke "
    db "sssom du vet hva"
    db "ssslags øy dette"
    db "er_…            "
    db "TIII-HIII-HIII! "
    db "For en dust_…   "
    db "TII-HII-HII!!@"
;    db "TSSSK, TSSSK!   "
;    db "You don't ssseem"
;    db "to know what    "
;    db "kind of island  "
;    db "thisss iss...   "
;    db "KEEE-HEEE-HEEE! "
;    db "What a fool...  "
;    db "KEE-HEE-HEH!!@"

Dialog0B6::
    db "Hei dumrian! Vil"
    db "du ha et tips?  "
    db "Mitt svake punkt"
    db "er_… !!         "
    db "Oops, der holdt "
    db "jeg på å for-   "
    db "snakke meg      "
    db "igjen_…@"
;    db "Hey dummy! Need "
;    db "a hint?  My weak"
;    db "point is... !!  "
;    db "Whoops!  There I"
;    db "go, talking too "
;    db "much again...@"

Dialog0B7::
    db "Greit, hør her! "
    db "Hvis Vindfisken "
    db "våkner, kommer  "
    db "alt på denne øya"
    db "til å forsvinne "
    db "for alltid! Og  "
    db "da mener jeg_…  "
    db "ALT!@"
;    db "Okay, listen up!"
;    db "If the Wind Fish"
;    db "wakes up, every-"
;    db "thing on this   "
;    db "island will be  "
;    db "gone forever!   "
;    db "And I do mean..."
;    db "EVERYTHING!@"

Dialog0B8::
Dialog0B9::
    db "Kreftene mine_… "
    db "Borte_… Jeg_…   "
    db "tapte! Men du   "
    db "vil også gå tapt"
    db "hvis Vindfisken "
    db "våkner! Som meg "
    db "er_… du_… i_…   "
    db "drømmen_… hans_…@"
;    db "My energy...    "
;    db "gone...I...lost!"
;    db "But you will be "
;    db "lost too, if the"
;    db "Wind Fish wakes!"
;    db "Same as me...you"
;    db "...are...in...  "
;    db "his...dream...@"

Dialog0BA::
    db "PØH! Jeg kommer "
    db "ikke til å spare"
    db "på noe! Jeg     "
    db "skal få deg til "
    db "å ønske at du   "
    db "aldri ble født!!@"
;    db "BAH!  I'm not   "
;    db "going to hold   "
;    db "back!  I'm going"
;    db "to make you wish"
;    db "you were never  "
;    db "born!!@"

Dialog0BB::
Dialog0BC::
    db "KNITRE-FVOOOFF! "
    db "Du er ferdig!   "
    db "Jeg vil aldri la"
    db "deg spille på   "
    db "Sirenenes       "
    db "instrumenter!! @"
;    db "CRACKLE-FWOOOSH!"
;    db "You're finished!"
;    db "I will never let"
;    db "you play the    "
;    db "Instruments of  "
;    db "the Sirens!!@"

Dialog0BD::
    db "K-K-KNITRE!     "
    db "Hvorfor kom du  "
    db "hit? Hvis det   "
    db "ikke var for    "
    db "deg, ville ingen"
    db "ting ha måttet  "
    db "endre seg! Du   "
    db "kan ikke vekke  "
    db "Vindfisken! Husk"
    db "at du_… også_…  "
    db "er i_… drømmen_…@"
;    db "C-C-CRACKLE!    "
;    db "Why did you come"
;    db "here?  If it    "
;    db "weren't for you,"
;    db "nothing would   "
;    db "have to change! "
;    db "You cannot wake "
;    db "the Wind Fish!  "
;    db "Remember, you..."
;    db "too...are in... "
;    db "...the dream...@"

Dialog0BE::
Dialog0BF::
Dialog0C0::
    db "Uhu! Hei, modige"
    db "gutt, på søken  "
    db "etter å vekke   "
    db "drømmeren!      "
    db "Velkommen til   "
    db "den mystiske    "
    db "skogen! Du vil  "
    db "finne mye       "
    db "mystisk på denne"
    db "uoppdagede øya  "
    db "Koholint! Jeg er" 
    db "redd det er en  "
    db "smule krevende  "
    db "å forlate øya   "
    db "mens Vindfisken "
    db "sover.          "
    db "_… Forresten,   "
    db "har du noensinne"
    db "besøkt Halehula,"
    db "som ligger sør  "
    db "for landsbyen?  "
    db "Gå dit med nøk- "
    db "kelen du finner "
    db "i denne skogen_…"
    db "Vindfisken      "
    db "følger med_…    "
    db "Uhu!@"
;    db "Hoot!  Ho, brave"
;    db "lad, on your    "
;    db "quest to wake   "
;    db "the dreamer!    "
;    db "Welcome to the  "
;    db "Mysterious Wood!"
;    db "Much of mystery "
;    db "you will find on"
;    db "this uncharted  "
;    db "Koholint island!"
;    db "I'm afraid you  "
;    db "may find it a   "
;    db "trifle difficult"
;    db "to leave the    "
;    db "island while the"
;    db "Wind Fish naps. "
;    db "...By the by,   "
;    db "have you ever   "
;    db "visited the Tail"
;    db "Cave, which is  "
;    db "south of the    "
;    db "village?  Go    "
;    db "there with the  "
;    db "key you find in "
;    db "this forest...  "
;    db "The Wind Fish is"
;    db "watching...Hoot!@"

Dialog0C1::
    db "Uhuu! Ta med deg"
    db "den nøkkelen til"
    db "Halehula. Finn  "
    db "instrumentet som"
    db "er gjemt der! Gå"
    db "nå! Vindfisken  "
    db "venter! Uhuuu!@"
;    db "Hoot!  Take the "
;    db "key and go to   "
;    db "the Tail Cave.  "
;    db "Retrieve the    "
;    db "Instrument that "
;    db "is hidden there!"
;    db "Go now!  The    "
;    db "Wind Fish is    "
;    db "waiting!  Hooot!@"

Dialog0C2::
    db "Uhuuu! Det er et"
    db "av «Sirenenes   "
    db "instrumenter»!  "
    db "Jeg må innrømme "
    db "at jeg til å    "
    db "begynne med ikke"
    db "trodde at du var"
    db "virkelig_… Det  "
    db "instrumentet er "
    db "ett av totalt   "
    db "åtte, som sammen"
    db "innehar kraften "
    db "til å vekke     "
    db "Vindfisken! Du  "
    db "må samle alle!  "
    db "Jeg har fått i  "
    db "oppdrag å gi deg"
    db "veibeskrivelse_…"
    db "Ditt neste mål  "
    db "er nordover, i  "
    db "Symresumpen!!   "
    db "Uhuu, ja visst!@"
;    db "Hoooot!  That is"
;    db "an 'Instrument  "
;    db "of the Sirens!' "
;    db "I have to admit,"
;    db "at first I did  "
;    db "not believe you "
;    db "were real...    "
;    db "That Instrument,"
;    db "along with the  "
;    db "seven others in "
;    db "the set, has the"
;    db "power to wake   "
;    db "the Wind Fish!  "
;    db "You must collect"
;    db "them all!  I was"
;    db "instructed to   "
;    db "give you direc- "
;    db "tions...  Your  "
;    db "next goal is    "
;    db "north, in       "
;    db "Goponga Swamp!! "
;    db "Hoot, indeed!@"

Dialog0C3::
    db "Uhu! Det er et  "
    db "fryktinngytende "
    db "dyr du har der! "
    db "Ikke glem at det"
    db "er i Symresumpen"
    db "du finner neste "
    db "instrument!@"
;    db "Hoot!  That is a"
;    db "fearsome looking"
;    db "animal you have "
;    db "there!  Do not  "
;    db "forget, the next"
;    db "Instrument is in"
;    db "Goponga Swamp!@"

Dialog0C4::
    db "Uhuu! Vindfisken"
    db "sover lenge og  "
    db "drømmende i egg-"
    db "et ovenfor_…    "
    db "Når du spiller  "
    db "alle de åtte    "
    db "Sirenenes       "
    db "instrumenter ved"
    db "egget vil han   "
    db "våkne. Dette er,"
    db "min venn, den   "
    db "eneste måten du "
    db "kan forlate     "
    db "denne øya på!   "
    db "Uhu!@"
;    db "Hoooot! The Wind"
;    db "Fish sleeps long"
;    db "and dreamily in "
;    db "the Egg above..."
;    db "When you play   "
;    db "the eight Siren "
;    db "Instruments in  "
;    db "front of the Egg"
;    db "he will awaken. "
;    db "This, my friend,"
;    db "is the only way "
;    db "for you to leave"
;    db "the island! Hoo!@"

Dialog0C5::
    db "Uhu! Hvor mange "
    db "instrumenter har"
    db "du fått tak i så"
    db "langt? Når du   "
    db "spiller dem alle"
    db "foran egget, vil"
    db "Vindfisken våkne"
    db "og du vil for-  "
    db "late øya. Nå må "
    db "du skynde deg   "
    db "til Yahara! De  "
    db "mørke monstre   "
    db "som bor der i   "
    db "sanden vil vise "
    db "deg veien!      "
    db "Uhu! Uhu!@"
;    db "Hoot!  How many "
;    db "Instruments     "
;    db "have you gotten "
;    db "so far?  When   "
;    db "you play the    "
;    db "Instruments in  "
;    db "front of the    "
;    db "Egg, the Wind   "
;    db "Fish will wake  "
;    db "and you will    "
;    db "leave this      "
;    db "island.  Now,   "
;    db "you must hasten "
;    db "to the Yarna    "
;    db "Desert!  The    "
;    db "dark, monstrous "
;    db "inhabitants of  "
;    db "the sand will   "
;    db "show you the    "
;    db "way! Hoot Hoot!@"

Dialog0C6::
    db "Uhu! Nøkkelens  "
    db "form viser en   "
    db "fisk som svømmer"
    db "opp et fosse-   "
    db "fall! Gå nå, til"
    db "fossen i fjel-  "
    db "let! Et hopp fra"
    db "toppen vil ta   "
    db "deg til målet!@"
;    db "Hoot!  The shape"
;    db "of the key shows"
;    db "a fish, swimming"
;    db "up a cascade of "
;    db "water!  Go now  "
;    db "to the mountain "
;    db "waterfall!  A   "
;    db "leap from the   "
;    db "top and you will"
;    db "reach your goal!@"

Dialog0C7::
    db "Uhu! Det finnes "
    db "to templer; det "
    db "ene nordover, og"
    db "det andre sør-  "
    db "over. Gå sørover"
    db "først, der eld- "
    db "gamle ruiner kan"
    db "fortelle om     "
    db "Vindfisken_… Du "
    db "kommer til å    "
    db "lære mye der_…@"
;    db "Hoot!  There are"
;    db "two shrines, one"
;    db "to the north,   "
;    db "the other to the"
;    db "south.  First,  "
;    db "head south,     "
;    db "where ancient   "
;    db "ruins speak of  "
;    db "the Wind Fish..."
;    db "You will learn  "
;    db "much there...@"

Dialog0C8::
    db "Uhu! Jeg ser at "
    db "du har lest     "
    db "relieffet_… Selv"
    db "om det står at  "
    db "øya er en del av"
    db "Vindfiskens     "
    db "drøm, er det    "
    db "ingen som vet   "
    db "det sikkert_…   "
    db "Akkurat som at  "
    db "du ikke kan vite"
    db "en kistes inn-  "
    db "hold før du     "
    db "åpner den, kan  "
    db "du ikke vite om "
    db "dette er en drøm"
    db "før du våkner_… "
    db "Den eneste som  "
    db "vet det sikkert "
    db "er Vindfisken_… "
    db "Stol på følel-  "
    db "sene dine_… Én  "
    db "dag vil du finne"
    db "svaret_…@"
;    db "Hoot!  I see you"
;    db "have read the   "
;    db "relief...  While"
;    db "it does say the "
;    db "island is but a "
;    db "dream of the    "
;    db "Wind Fish, no   "
;    db "one is really   "
;    db "sure...  Just as"
;    db "you cannot know "
;    db "if a chest holds"
;    db "treasure until  "
;    db "you open it, so "
;    db "you cannot tell "
;    db "if this is a    "
;    db "dream until you "
;    db "awaken...  The  "
;    db "only one who    "
;    db "knows for sure  "
;    db "is the Wind     "
;    db "Fish...  Trust  "
;    db "your feelings..."
;    db "Someday you will"
;    db "know for sure...@"

Dialog0C9::
    db "Uhu! De mange   "
    db "monstrene på øya"
    db "frykter at Vind-"
    db "fisken er i ferd"
    db "med å våkne!    "
    db "Monstrenes kraft"
    db "er ekte! De kan "
    db "erobre øya og   "
    db "tilintetgjøre   "
    db "sine fiender!   "
    db "Den dagen kan   "
    db "komme snart! Gå "
    db "nå, til fjell-  "
    db "tårnet! Fly som "
    db "fuglen!         "
    db "Uhu! Uhu!@"
;    db "Hoot!  The many "
;    db "monsters of this"
;    db "island fear that"
;    db "the Wind Fish is"
;    db "about to awaken!"
;    db "The monsters'   "
;    db "power is real!  "
;    db "They may conquer"
;    db "the island and  "
;    db "destroy their   "
;    db "foes!  That day "
;    db "may come soon!  "
;    db "Now, go to the  "
;    db "mountain tower! "
;    db "Fly like a bird!"
;    db "Hoot! Hoot!@"

Dialog0CA::
    db "Uhu! Uhu! Veien "
    db "din er ikke     "
    db "enkel, men du er"
    db "nesten fremme.  "
    db "Gå østover.     "
    db "Vindfisken      "
    db "begynner å bli  "
    db "urolig.@"
;   db "Hoot hoot!      "
;    db "Your path is    "
;    db "not easy, but   "
;    db "you are almost  "
;    db "there. Go east. "
;    db "The Wind Fish   "
;    db "is getting      "
;    db " restless.@"

Dialog0CB::
    db "Uhu! Det er en  "
    db "stund siden våre"
    db "veier krysset   "
    db "hverandre, gutt."
    db "Du må dykke ned "
    db "i Martes bukt   "
    db "for å komme til "
    db "Mallegapet_…    "
    db "Jo nærmere du   "
    db "kommer Vind-    "
    db "fisken, jo mer  "
    db "urolig sover    "
    db "han. Fortsett   "
    db "videre! Uhu!@"
;    db "Hoot!  It has   "
;    db "been some time  "
;    db "since our paths "
;    db "crossed, lad.   "
;    db "You must dive   "
;    db "into the waters "
;    db "of Martha's Bay "
;    db "to enter the    "
;    db "Catfish's Maw..."
;    db "The closer you  "
;    db "get to the Wind "
;    db "Fish, the more  "
;    db "restless he     "
;    db "sleeps.  Carry  "
;    db "onward!  Hoot!@"

Dialog0CC::
    db "Uhu! Den jenta  "
    db "sang sangen sin "
    db "foran egget!    "
    db "«Balladen om    "
    db "Vindfisken» er  "
    db "en oppvåknings- "
    db "sang! Ønsket hun"
    db "virkelig å vekke"
    db "Vindfisken?! Det"
    db "neste instru-   "
    db "mentet er vest- "
    db "over. Spill     "
    db "melodiene dine  "
    db "så døde steiner "
    db "kan høre deg!   "
    db "Vis ditt mot!   "
    db "Vindfisken      "
    db "venter på deg!  "
    db "Uhu!@"
;    db "Hoot!  That girl"
;    db "sang her song in"
;    db "front of the    "
;    db "Egg! Her 'Ballad"
;    db "of the Wind     "
;    db "Fish' is a song "
;    db "of awakening!   "
;    db "Did she actually"
;    db "intend to wake  "
;    db "the Wind Fish?! "
;    db "The next Sirens'"
;    db "Instrument is in"
;    db "the west.  Play "
;    db "your melodies so"
;    db "the unliving    "
;    db "stones might    "
;    db "hear!  Show your"
;    db "courage!  The   "
;    db "Wind Fish waits "
;    db "for you!  Hoot!@"

Dialog0CD::
    db "Tiden har       "
    db "kommet_… Vind-  "
    db "fisken venter_… "
    db "Gå inn i egget_…"
    db "Uhu! Uhu!@"
;    db "The time has    "
;    db "come... The Wind"
;    db "Fish awaits...  "
;    db "Enter the Egg..."
;    db "Hoot! Hoot!@"

Dialog0CE::
Dialog0CF::
    db "Uhu! Unge gutt, "
    db "jeg mener_…     "
    db "Helten #####! Du"
    db "har beseiret    "
    db "Marerittene! Du "
    db "har bevist din  "
    db "visdom, ditt    "
    db "mot, og din     "
    db "kraft!          "
    db "... ... ... ... "
    db "Som en del av   "
    db "Vindfiskens sjel"
    db "er jeg vokteren "
    db "av hans drømme- "
    db "verden_… Men én "
    db "dag kom Mare-   "
    db "rittene inn i   "
    db "drømmen og lagde"
    db "kaos. Så kom du,"
    db "#####, for å    "
    db "redde øya_… Jeg "
    db "har alltid stolt"
    db "på din evne til "
    db "å drive tilbake "
    db "Marerittene.    "
    db "Tusen takk,     "
    db "#####_… Min jobb"
    db "her er gjort_…  "
    db "Vindfisken      "
    db "våkner snart.   "
    db "Farvel_… Uhu!@"
;    db "Hoot! Young lad,"
;    db "I mean... #####,"
;    db "the hero!  You  "
;    db "have defeated   "
;    db "the Nightmares! "
;    db "You have proven "
;    db "your wisdom,    "
;    db "courage and     "
;    db "power!          "
;    db "... ... ... ... "
;    db "As part of the  "
;    db "Wind Fish's     "
;    db "spirit, I am the"
;    db "guardian of his "
;    db "dream world...  "
;    db "But one day, the"
;    db "Nightmares      "
;    db "entered the     "
;    db "dream and began "
;    db "wreaking havoc. "
;    db "Then you, #####,"
;    db "came to rescue  "
;    db "the island...   "
;    db "I have always   "
;    db "trusted in your "
;    db "courage to turn "
;    db "back the Night- "
;    db "mares.  Thank   "
;    db "you, #####... My"
;    db "work is done... "
;    db "The Wind Fish   "
;    db "will wake soon. "
;    db "Good bye...Hoot!@"

Dialog0D0::
    db "... ... ... ... "
    db " ... ... ... ..."
    db "     JEG ER     "
    db "   VINDFISKEN_… "
    db " LENGE HAR JEG  "
    db "    SLUMRET_…   "
    db " I DRØMMENE MINE"
    db " VISTES ET EGG  "
    db " OMRINGET AV EN "
    db " ØY, MED FOLK,  "
    db "  DYR; EN HEL   "
    db "     VERDEN!    "
    db "... ... ... ... "
    db " MEN, SANNELIG, "
    db "ALLE DRØMMER MÅ "
    db " TA SLUTT! NÅR  "
    db " JEG VÅKNER VIL "
    db "  KOHOLINT BLI  "
    db "  BORTE_… BARE  "
    db "MINNET OM DETTE "
    db "   LANDET VIL   "
    db "EKSISTERE I DEN "
    db "VÅKENDE VERDEN_…"
    db "ÉN DAG HUSKER DU"
    db " KANSKJE DENNE  "
    db "ØYA_… DÉT MINNET"
    db "MÅ VÆRE DEN EKTE"
    db "DRØMMEVERDENEN_…"
    db "... ... ... ... "
    db "  KOM, #####_…  "
    db " LA OSS VÅKNE_… "
    db "    SAMMEN!!   @"
;    db "... ... ... ... "
;    db " ... ... ... ..."
;    db " I AM THE WIND  "
;    db "      FISH...   "
;    db " LONG HAS BEEN  "
;    db "  MY SLUMBER... "
;    db " IN MY DREAMS..."
;    db " AN EGG APPEARED"
;    db "     AND WAS    "
;    db "SURROUNDED BY AN"
;    db "  ISLAND, WITH  "
;    db "PEOPLE, ANIMALS,"
;    db "AN ENTIRE WORLD!"
;    db "... ... ... ... "
;    db "  BUT, VERILY,  "
;    db "IT BE THE NATURE"
;    db "  OF DREAMS TO  "
;    db "END! WHEN I DOST"
;    db "AWAKEN, KOHOLINT"
;    db " WILL BE GONE..."
;    db "ONLY THE MEMORY "
;    db " OF THIS DREAM  "
;    db "LAND WILL EXIST "
;    db "  IN THE WAKING "
;    db "      WORLD...  "
;    db " SOMEDAY, THOU  "
;    db "MAY RECALL THIS "
;    db " ISLAND...  THAT"
;    db " MEMORY MUST BE "
;    db " THE REAL DREAM "
;    db "     WORLD...   "
;    db "... ... ... ... "
;    db " COME, #####... "
;    db "LET US AWAKEN..."
;    db "   TOGETHER!!@"

Dialog0D1::
Dialog0D2::
    db " SPILL DE ÅTTE  "
    db " INSTRUMENTENE! "
    db "     SPILL      "
    db "  OPPVÅKNINGS-  "
    db "    SANGEN!!@   "
;    db " PLAY THE EIGHT "
;    db "  INSTRUMENTS!  "
;    db "PLAY THE SONG OF"
;    db "   AWAKENING!!@"

Dialog0D3::
Dialog0D4::
Dialog0D5::
    db "Havfruestatue  @"
;    db "Mermaid Statue  @"

Dialog0D6::
Dialog0D7::
    db "_… #####, du har"
    db "beseiret alle   "
    db "Marerittene!    "
    db "Stig opp trappen"
    db "foran deg!@"
;    db "...#####, you   "
;    db "have beaten all "
;    db "the Nightmares! "
;    db "Climb the stairs"
;    db "before you!@"

Dialog0D8::
    db "Arh! Va err det "
    db "do shtirrer på  "
    db "med ditt for-   "
    db "shtørrelsesglass"
    db "Halt opp med det"
    db "sporenshtreks!@ "
;    db "Ach! Vat are you"
;    db "looking at vith "
;    db "zat magnifying  "
;    db "lens?  Stop it  "
;    db "at vonce!@"

Dialog0D9::
    db "  Uhu!  Uhu!    " 
    db "Så du er gutten "
    db "som eier sverdet"
    db "_… Nå forstår   "
    db "jeg hvorfor     "
    db "monstrene har   "
    db "begynt å bli så "
    db "voldelige_… En  "
    db "modig gutt har  "
    db "kommet for å    "
    db "vekke opp Vind- "
    db "fisken_… Det    "
    db "sies at du ikke "
    db "kan forlate øya "
    db "før du vekker   "
    db "Vindfisken_…    "
    db "Nå bør du dra   "
    db "nordover, til   "
    db "den mystiske    "
    db "skogen. Jeg vil "
    db "vente på deg    "
    db "der!  Uhu!@"
;    db "  Hoot!  Hoot!  "
;    db "So you are the  "
;    db "lad who owns the"
;    db "sword...  Now I "
;    db "understand why  "
;    db "the monsters are"
;    db "starting to act "
;    db "so violently... "
;    db "A courageous lad"
;    db "has come to wake"
;    db "the Wind Fish..."
;    db "It is said that "
;    db "you cannot leave"
;    db "the island      "
;    db "unless you wake "
;    db "the Wind Fish..."
;    db "You should now  "
;    db "go north, to the"
;    db "Mysterious      "
;    db "Forest.  I will "
;    db "wait for you    "
;    db "there!  Hoot!@"

Dialog0DA::
    db "Din plage! Du   "
    db "er bare i veien!@"
;    db "Annoyance!  You "
;    db "are only getting"
;    db "in the way!@"

Dialog0DB::
    db "Kvekk!  Kvekk!  "
    db "Halla, mann, jeg"
    db "er Vortimer, på "
    db "vokal! Bror, du "
    db "ser ut som at du"
    db "ikke skjønner et"
    db "kvekk av musikk!"
    db "Kvekk!@"
;    db "Ribbit!  Ribbit!"
;    db "Hey, man, I'm   "
;    db "Mamu, on vocals!"
;    db "Brother, you    "
;    db "look like you   "
;    db "don't know      "
;    db "squat about     "
;    db "music!  Ribbit!@"

Dialog0DC::
    db "Kvekk!  Kvekk!  "
    db "Jeg er Vortimer,"
    db "på vokal, men   "
    db "det vet du vel  "
    db "allerede. Alle  "
    db "vet hvem jeg er!"
    db "Vil du henge    "
    db "litt med oss og "
    db "høre på når vi  "
    db "jammer? For 300 "
    db "rupier kan du få"
    db "sniklytte på en "
    db "uutgitt låt!    "
    db "Vil du betale?  "
    db "    Ja   Ikke nå<ask>"
;    db "Ribbit!  Ribbit!"
;    db "I'm Mamu, on    "
;    db "vocals!  But I  "
;    db "don't need to   "
;    db "tell you that,  "
;    db "do I?  Everybody"
;    db "knows me!  Want "
;    db "to hang out and "
;    db "listen to us    "
;    db "jam?  For 300   "
;    db "Rupees, we'll   "
;    db "let you listen  "
;    db "to a previously "
;    db "unreleased cut! "
;    db "What do you do? "
;    db "    Pay  Leave<ask>"

Dialog0DD::
    db "Takk_…          " 
    db "Tusen takk_…    "
    db "_… Kvekk!@"
;    db "Thank you...    "
;    db "Thank you very  "
;    db "much... Croak!@"

Dialog0DE::
    db "Det var synd,   "
    db "men vi spiller  "
    db "ikke gratis!@"
;    db "Well, that's a  "
;    db "shame, but we   "
;    db "don't play for  "
;    db "free!@"

Dialog0DF::
    db "Du har lært deg "
    db "Froskens sjele- "
    db "sang! Det er en "
    db "veldig rørende  "
    db "melodi_… Den kan"
    db "til og med skape"
    db "liv og røre i   "
	db "ikke-levende    "
	db "ting!@"
;    db "You've learned  "
;    db "The Frog's Song "
;    db "of Soul!  It's a"
;    db "very moving     "
;    db "tune... It can  "
;    db "even liven up   "
;    db "unliving things!@"

Dialog0E0::
    db "Hvis du spiller "
    db "denne sangen vil"
    db "alt rundt deg   "
    db "føles mer       "
    db "levende!@"
;    db "If you play this"
;    db "song, you'll    "
;    db "make everything "
;    db "around you feel "
;    db "more alive!@"

Dialog0E1::
    db "Hei, guttunge!  "
    db "Du vekket meg   "
    db "fra en god lur! "
    db "_… Takk for det!"
    db "Men nå skal jeg "
    db "få min hevn! Er "
    db "du klar?!       "
    db "    Ja   N-Nei<ask>"
;    db "Hey, Kid!  You  "
;    db "woke me up from "
;    db "a fine nap!!    "
;    db "...Thanks a lot!"
;    db "But now, I'll   "
;    db "get my revenge! "
;    db "Are you ready?! "
;    db "    Yes  N-No<ask>"

Dialog0E2::
    db "Jeg skal la deg "
    db "bære mer magisk "
    db "pulver! He he!  "
    db "Er du klar?!    "
    db "    Ja   N-Nei<ask>"
;    db "I'll let you    "
;    db "carry more Magic"
;    db "Powder!  He He! "
;    db "Are you ready?! "
;    db "    Yes  N-No<ask>"

Dialog0E3::
    db "Alt i orden, jeg"
    db "skal la deg bære"
    db "flere bomber! He"
    db "he! Er du klar?!"
    db "    Ja   N-Nei<ask>"
;    db "Okay, I'll let  "
;    db "you carry more  "
;    db "Bombs! He He He!"
;    db "Are you ready?! "
;    db "    Yes  N-No<ask>"

Dialog0E4::
    db "Greit, jeg skal "
    db "la deg ha flere "
    db "piler! Hehehe!  "
    db "Er du klar?!    "
    db "    Ja   N-Nei<ask>"
;    db "Fine, I'll let  "
;    db "you have more   "
;    db "arrows! Heh Heh!"
;    db "Are you ready?! "
;    db "    Yes  N-No<ask>"

Dialog0E5::
    db "He he he he!    "
    db "Det fortjener   "
    db "du! Se på alt   "
    db "skrapet du er   "
    db "nødt til å bære "
    db "rundt på! Haha! "
    db "Ha det fint!    "
    db "Vi sees!@"
;    db "Heh Heh Heh!    "
;    db "You deserve it! "
;    db "Now look at all "
;    db "that junk you   "
;    db "have to carry!  "
;    db "Hah!  Take care!"
;    db "See you again!@"

Dialog0E6::
    db "?? Det er risset"
    db "inn et bilde i  "
    db "veggen, men du  "
    db "kan ikke se det "
    db "fordi det er for"
    db "mørkt her inne_…@"
;    db "??  There is a  "
;    db "picture carved  "
;    db "on the wall, but"
;    db "you can't see it"
;    db "because it's too"
;    db "dark in here...@"

Dialog0E7::
    db " TIL FINNEREN_… "
    db "  ØYA KOHOLINT  "
    db "  ER BLOTT EN   "
    db "    HILDRING_…  "
    db "    MENNESKE,   "
    db "  MONSTER, HAV, "
    db "  HIMMEL_… ET   "
    db "TABLÅ PÅ ET ØYE-"
    db " LOKK I SØVNENS "
    db " VRIMMEL_… VEKK "
    db " DRØMMEREN, OG  "
    db "  KOHOLINT VIL  "
    db "FORSVINNE, LIKT "
    db "EN SÅPEBOBLE SOM"
    db "SPREKKER_… SKIP-"
    db " BRUDNE, DU BØR "
    db "VITE SANNHETEN! "
    db "... ... ... ... "
    db "Hæ? Tablå?@"
;    db "TO THE FINDER..."
;    db "  THE ISLE OF   "
;    db "KOHOLINT, IS BUT"
;    db "  AN ILLUSION..."
;    db " HUMAN, MONSTER,"
;    db " SEA, SKY... A  "
;    db "SCENE ON THE LID"
;    db " OF A SLEEPER'S "
;    db "  EYE...  AWAKE "
;    db "THE DREAMER, AND"
;    db "  KOHOLINT WILL "
;    db "VANISH MUCH LIKE"
;    db "  A BUBBLE ON A "
;    db "NEEDLE... CAST- "
;    db "AWAY, YOU SHOULD"
;    db "KNOW THE TRUTH! "
;    db "... ... ... ... "
;    db "What?  Illusion?@"

Dialog0E8::
    db "Du fant et gull-"
    db "blad! Trykk     "
    db "START for å se  "
    db "hvor mange du   "
    db "har samlet!@"
;    db "You've found a  "
;    db "Gold Leaf! Press"
;    db "START to see    "
;    db "how many you've "
;    db "collected!@"

Dialog0E9::
    db "Endelig! Du har "
    db "fått det siste  "
    db "gullbladet! Nå  "
    db "bør du snakke   "
    db "med Rikard om   "
    db "den nøkkelen_…@"
;    db "At last!  You've"
;    db "got the final   "
;    db "Golden Leaf!    "
;    db "Now go and see  "
;    db "Richard about   "
;    db "that key...@"

Dialog0EA::
Dialog0EB::
Dialog0EC::
    db "Du fikk en      "
    db "skytsnøtt! Den  "
    db "vil halvere     "
    db "skaden du tar! @"
;    db "You've got a    "
;    db "Guardian Acorn! "
;    db "It will reduce  "
;    db "the damage you  "
;    db "take by half!@"

Dialog0ED::
    db "Du fikk speil-  "
    db "skjoldet! Nå kan"
    db "du reflektere de"
    db "strålene du ikke"
    db "kunne blokkere  "
    db "før!@"
;    db "You've got the  "
;    db "Mirror Shield!  "
;    db "You can now turn"
;    db "back the beams  "
;    db "you couldn't    "
;    db "block before!@"

Dialog0EE::
    db "Du fikk et enda "
    db "kraftigere arm- "
    db "bånd! Nå kan du "
    db "nesten løfte en "
    db "hel hval!@"
;    db "You've got a    "
;    db "more Powerful   "
;    db "Bracelet!  Now  "
;    db "you can almost  "
;    db "lift a whale!@"

Dialog0EF::
    db "Du fant et      "
    db "skjult snegle-  "
    db "hus! Samler du  "
    db "mange av disse, "
    db "vil det helt    "
    db "sikkert skje noe"
    db "bra!@"
;    db "You found a     "
;    db "Secret Seashell!"
;    db "If you collect a"
;    db "lot of these,   "
;    db "something good  "
;    db "is bound to     "
;    db "happen!@"

Dialog0F0::
    db "Har du lyst til "
    db "å ta en flåtetur"
    db "for hundre      "
    db "rupier?         "
    db "    Ja   Aldri<ask>"
;    db "Want to go on a "
;    db "raft ride for a "
;    db "hundred Rupees? "
;    db "    Yes  No Way<ask>"

Dialog0F1::
    db "Greit, flåta er "
    db "klar til deg    "
    db "ute! Kos deg!@"
;    db "Okay, the raft  "
;    db "is ready for you"
;    db "outside!  Enjoy!@"

Dialog0F2::
    db "   Foss ved     "
    db "   Tempelet@"
;   db "Waterfall at the"
;   db "    Shrine@"

Dialog0F3::
    db "    Sør for     "
    db "   Tempelet@"
;    db " South of the   "
;    db "    Shrine@"

Dialog0F4::
    db "  Inngangen til "
    db "    Snutebu@"
;    db "Entrance to the "
;    db " Animal Village@"

Dialog0F5::
    db "Vi fødtes av    "
    db "mareritt_… For å"
    db "ta over denne   "
    db "verdenen tvang  "
    db "vi Vindfisken   " 
    db "til evig søvn!  "
    db "Hvis Vindfisken "
    db "aldri våkner,   "
    db "vil denne øya   "
    db "aldri forsvinne!"
    db "Vi kunne ha her-"
    db "sket over dette "
    db "stedet_… Men du "
    db "måtte komme her "
    db "og forpurre     " 
    db "planene våre!   "
    db "Hehehe! Du vil  "
    db "aldri klare å   "
    db "overvinne oss!!!"
    db "Stålsett deg!@"
;    db "We were born of "
;    db "nightmares... To"
;    db "take over this  "
;    db "world, we made  "
;    db "the Wind Fish   "
;    db "sleep endlessly!"
;    db "If the Wind Fish"
;    db "doesn't wake up,"
;    db "this island will"
;    db "never disappear!"
;    db "We would have   "
;    db "been the masters"
;    db "of this place..."
;    db "But you had to  "
;    db "come here and   "
;    db "disrupt our     "
;    db "plans!  Heh heh!"
;    db "You can never   "
;    db "defeat us!!!    "
;    db "Let's rumble!@"

Dialog0F6::
    db "Denne øya vil   "
    db "forsvinne_…     "
    db "Verdenen vår vil"
    db "forsvinne_…     "
    db "Verdenen vår_…  "
    db "Verdenen_… vår_…@"
;    db "This island is  "
;    db "going to dis-   "
;    db "appear...  Our  "
;    db "world is going  "
;    db "to disappear... "
;    db "Our world...    "
;    db "Our... world... @"

Dialog0F7::
    db "Wow!  #####, kan"
    db "jeg prøve dette?"
    db "Hva sier du?!   "
    db "    Ok   Aldri<ask>"
;    db "Wow!  #####, can"
;    db "I try this?!    "
;    db "What do you say?"
;    db "    Okay No Way<ask>"

Dialog0F8::
    db "Kom igjen! Jeg  "
    db "vil gjøre det!  "
    db "Kan jeg? Det ser"
    db "så gøy ut!      "
    db "    Ja   Greit<ask>"
;    db "C'mon!  I want  "
;    db "to do it! Can I?"
;    db "It looks so fun!"
;    db "    Yes  Okay<ask>"

Dialog0F9::
    db "Du er flink!    "
    db "Du er en proff, "
    db "ikke sant?      "
    db "... ... ... ... "
    db "Vel, stikk av!  "
    db "Proffer får ikke"
    db "lov til å være  "
    db "her!@"
;    db "You're good!    "
;    db "You're a pro,   "
;    db "aren't you?     "
;    db "... ... ... ... "
;    db "Well, beat it!  "
;    db "Pros aren't     "
;    db "allowed in here!@"

Dialog0FA::
    db "Gå vekk!@"
;    db "Go away!@"

Dialog0FB::
    db "Gi deg!@"
;    db "Quit it!@"

Dialog0FC::
    db "Dette er ikke en"
    db "kommode_… Hva?  "
    db "Visste du det?  "
    db "Greit.@"
;    db "This is not a   "
;    db "chest...  What? "
;    db "You knew that?  "
;    db "Okay.@"

Dialog0FD::
    db "##### sjekket   "
    db "kommoden. Jepp! "
    db "Alt ser bra ut!@"
;    db "##### checked   "
;    db "the chest.  Wow!"
;    db "This is a nice  "
;    db "chest!@"

Dialog0FE::
    db "Det er ferdig,  "
    db "dét er det! Bruk"
    db "det varsomt, for"
    db "det er sparsomt!"
    db "Hvorfor ikke    "
    db "prøve litt her  "
    db "i hytta mi?@"
;    db "It's all ready, "
;    db "it is!  Take    "
;    db "care, as there's"
;    db "not much there! "
;    db "Why not try a   "
;    db "bit in my hut?@"

Dialog0FF::
    db "Hei! Hva gjør'u "
    db "i kommoden min?!"
    db "Hvor har'u lært "
    db "å gjøre sånt'a?!@"
;    db "Hey!  What are  "
;    db "ya doin' in my  "
;    db "chest?!  Where'd"
;    db "you learn ta do "
;    db "such a thing?!@"

Dialog100::
    db "Du fikk Full-   "
    db "månecelloen!@"
;    db "You've got the  "
;    db "Full Moon Cello!@"

Dialog101::
    db "Du fikk         "
    db "Konkyliehornet!@"
;    db "You've got the  "
;    db "Conch Horn!@"

Dialog102::
    db "Du fikk Sjø-    "
    db "liljens bjelle!@"    
;    db "You've got the  "
;    db "Sea Lily's Bell!@"

Dialog103::
    db "Du fikk Bølge-  "
    db "kamharpen!@"
;    db "You've got the  "
;    db "Surf Harp!@"

Dialog104::
    db "Du fikk Vind-   "
    db "marimbaen!@"
;    db "You've got the  "
;    db "Wind Marimba!@"

Dialog105::
    db "Du fikk Korall- "
    db "triangelet!@"
;    db "You've got the  "
;    db "Coral Triangle!@"

Dialog106::
    db "Du fikk Kvelds- "
    db "roens orgel!@"
;    db "You've got the  "
;    db "Organ of        "
;    db "  Evening Calm!@"

Dialog107::
    db "Du fikk Torden- "
    db "trommen!@"
;    db "You've got the  "
;    db "Thunder Drum!@"
