Dialog108::
    db "Hei! Det er meg,"
    db "fotografen!     "
    db "Du virker nys-  "
    db "gjerrig på      "
    db "Bestefar Ulrik.@"
;    db "Hi! It's me, the"
;    db "photographer!   "
;    db "You seem curious"
;    db "about Grandpa   "
;    db "Ulrira.@"

Dialog109::
    db "Jeg kaller dette"
    db "«##### oppdager "
    db "Bestefar Ulriks "
    db "hemmelighet»!@"
;    db "I'll call this  "
;    db "'##### Dis-     "
;    db "covers Ulrira's "
;    db "Secret!'@"

Dialog10A::
    db "Stikk av nå     "
    db "før han finner  "
    db "deg, #####.@    "
;    db "#####, now run  "
;    db "away before he  "
;    db "finds you.@"

Dialog10B::
    db "Jeg skal frem-  "
    db "kalle bildet nå."
    db "Kom innom og se "
    db "det senere, ok?@"
;    db "I'll go develop "
;    db "this. Come see  "
;    db "it later, OK?@"

Dialog10C::
    db "Jeg ELSKER å ta "
    db "bilder. Får jeg "
    db "lov til å ta et "
    db "bilde av deg?   "
    db "    Ja   Nei<ask>"
;    db "I just LOVE to  "
;    db "take pictures.  "
;    db "Will you let me "
;    db "take your       "
;    db "picture?        "
;    db "    YES  NO<ask>"

Dialog10D::
    db "Gå bakerst i    "
    db "rommet og still "
    db "deg opp foran   "
    db "bakteppet.@     "
;    db "Go to the back  "
;    db "of the room and "
;    db "stand in front  "
;    db "of the screen.@"

Dialog10E::
    db "Hei der! Jeg har"
    db "ikke tatt bilde "
    db "av deg ennå! Gå "
    db "tilbake og stå  "
    db "foran bakteppet!@"
;    db "Hey! I haven't  "
;    db "taken your      "
;    db "picture yet! Go "
;    db "back and stand  "
;    db "in front of the "
;    db "screen!@"

Dialog10F::
    db "Bildet skal hete"
    db "«Her står en    "
    db "modig mann».    "
    db "Smiiil!@"
;    db "I'll call this  "
;    db "'Here Stands A  "
;    db "Brave Man.'     "
;    db "Say cheese!@"

Dialog110::
    db "Uglestatuen for-"
    db "søker å si noe, "
    db "men du forstår  "
    db "ikke hva den    "
    db "sier fordi den  "
    db "mangler nebbet.@"
;    db "This owl statue "
;    db "is trying to say"
;    db "something, but  "
;    db "you can't       "
;    db "understand it   "
;    db "because it has  "
;    db "no beak.@"

Dialog111::
    db "«Jeg har tatt   "
    db "det som var i   "
    db "denne kista.    "
    db "Kom og hent det,"
    db "hvis du tør!»   "
    db "Mester <skull>@"
; Rart med «boksen» her? Det er jo direkte oversatt, bare skurrer litt. 
;    db "'I've got what  "
;    db "was inside this "
;    db "box.  Come and  "
;    db "get it, if you  "
;    db "can!'  Master <skull>@"

Dialog112::
    db "Gulp! Du fant   "
    db "meg! Du er en   "
    db "ufyselig unge,  "
    db "vet du det?!@"
;    db "Gulp!  You found"
;    db "me!  You're a   "
;    db "real pesky kid, "
;    db "you know that?!@"

Dialog113::
    db "Arrg! Jeg klarer"
    db "ikke slå deg!   "
    db "Jeg stikker!@"
;    db "Arrgh!  I can't "
;    db "beat you!  I'm  "
;    db "outta here!@"

Dialog114::
    db "Du igjen?! Du   "
    db "gir deg aldri_… "
    db "Jeg orker ikke  "
    db "mer av deg!     "
    db "Greit, la oss   "
    db "kjøre på!@"
;    db "You again?!  You"
;    db "keep going and  "
;    db "going... I can't"
;    db "outlast you!    "
;    db "All right, let's"
;    db "do it!@"

Dialog115::
    db "VOFF! Grav! VOV!@"
;    db "WOOF! Dig! RUFF!@"

Dialog116::
    db "Du satte det    "
    db "manglende skje- "
    db "llet på havfrue-"
    db "statuen!@"
;    db "You put the     "
;    db "missing scale in"
;    db "the mermaid     "
;    db "statue!@"

Dialog117::
    db "Hei! Vær litt   "
    db "forsiktig neste "
    db "gang!@"
;    db "Hey! Be more    "
;    db "careful next    "
;    db "time!@"

Dialog118::
    db "Halla! Når du   "
    db "vil lagre er det"
    db "bare å trykke   "
    db "alle knappene på"
    db "én gang!  Eeh_… "
    db "Ikke spør meg   "
    db "hva det betyr,  "
    db "jeg er bare et  "
    db "barn!@"
;    db "Hey, man!  When "
;    db "you want to save"
;    db "just push all   "
;    db "the Buttons at  "
;    db "once!  Uhh...   "
;    db "Don't ask me    "
;    db "what that means,"
;    db "I'm just a kid!@"

Dialog119::
    db "Vel, det virker "
    db "som at du etter "
    db "å ha lagret vil "
    db "begynne ved den "
    db "siste døra du   "
    db "gikk gjennom_…  "
    db "Jeg aner ikke   "
    db "hvorfor, fordi  "
    db "jeg bare er et  "
    db "barn!@"
;    db "Well, it seems  "
;    db "that after you  "
;    db "save, you will  "
;    db "start at the    "
;    db "last door you   "
;    db "went through... "
;    db "I'm not really  "
;    db "sure why that is"
;    db "'cause I'm just "
;    db "a kid!@"

Dialog11A::
    db "Jeg har hørt at "
    db "du kan trykke på"
    db "SELECT for å se "
    db "på kartet over  "
    db "øya_… Men jeg   "
    db "skjønner ikke   "
    db "hva det betyr_…@"
;    db "I heard that you"
;    db "can press SELECT"
;    db "to look at the  "
;    db "island map...   "
;    db "But, I don't    "
;    db "understand what "
;    db "they mean by    "
;    db "that...@"

Dialog11B::
    db "Hvis du begynner"
    db "å gå tom for    "
    db "hjerter er det  "
    db "lurt å gå inn i "
    db "et hus eller en "
    db "hule_… Hvorfor? "
    db "Aner ikke, jeg  "
    db "er bare et barn!@"
;    db "When you're     "
;    db "running out of  "
;    db "Hearts, you'd   "
;    db "better enter a  "
;    db "house or cave..."
;    db "Why?  I have no "
;    db "idea, I'm just a"
;    db "kid!@"

Dialog11C::
    db "Halla! Hva synes"
    db "du om Marin?    "
    db "Ehh_… Jeg vet   "
    db "ikke, jeg er    "
    db "bare et barn!@"
;    db "Hey, dude! What "
;    db "do you think of "
;    db "Marin?  Uhh...  "
;    db "I don't know,   "
;    db "I'm just a kid!@"

Dialog11D::
    db "Hvor er du fra, "
    db "bror?_… Fra     "
    db "utenfor øya? Hva"
    db "er «utenfor»?   "
    db "Det har jeg     "
    db "aldri tenkt på_…@"
;    db "Where are you   "
;    db "from, brother?  "
;    db "...Outside the  "
;    db "island?  What is"
;    db "'outside?'  I've"
;    db "never thought   "
;    db "about it...@"

Dialog11E::
    db "Det svære egget "
    db "på toppen av    "
    db "Tindeggen? Det  "
    db "sies at Vind-   "
    db "fisken sover på "
    db "innsiden_… Hvor-"
    db "for? Neigu om   "
    db "jeg vet_…@"
;    db "The giant egg on"
;    db "top of Tamaranch"
;    db "Mountain?  They "
;    db "say the Wind    "
;    db "Fish is sleeping"
;    db "inside of it... "
;    db "Why?  I don't   "
;    db "know either...@"

Dialog11F::
    db "Hæ, spør du meg "
    db "om når vi kom og"
    db "begynte å bo på "
    db "denne øya? Hva  "
    db "mener du med    "
    db "«når»? Wow! Bare"
    db "det å tenke på  "
    db "det gir meg     "
    db "hodepine!@"
;    db "Dude!  You're   "
;    db "asking me when  "
;    db "we started to   "
;    db "live on this    "
;    db "island?  What do"
;    db "you mean by     "
;    db "'when?'  Whoa!  "
;    db "The concept just"
;    db "makes my head   "
;    db "hurt!@"

Dialog120::
    db "Marin? Hun liker"
    db "å gå og stirre  "
    db "ut på sjøen helt"
    db "alene_… Hvorfor?"
    db "Jeg er bare et  "
    db "barn, spør ikke "
    db "meg!@"
;    db "Marin? She likes"
;    db "to go stare at  "
;    db "the ocean all by"
;    db "herself...  Why?"
;    db "Hey, I'm just a "
;    db "kid, don't ask  "
;    db "me!@"

Dialog121::
    db "Hei_… Hvor er   "
    db "dere to på vei  "
    db "sammen? Hø? Eh, "
    db "jeg mente ikke  "
    db "noe med det_…   "
    db "Jeg er bare et  "
    db "barn!@"
;    db "Hey... Where're "
;    db "you two going   "
;    db "together?  Hunh?"
;    db "Uh, I didn't    "
;    db "mean anything..."
;    db "I'm just a kid!@"

Dialog122::
    db "Hei hei, fyr!   "
    db "Angående drømme-"
    db "tempelet der_…  "
    db "Det sies at det "
    db "er noe veldig   "
    db "bra der inne_…  "
    db "Jeg burde ikke  "
    db "si noe mer, jeg "
    db "er jo bare et   "
    db "barn!@"
;    db "Hey hey, bro!   "
;    db "About the Dream "
;    db "Shrine there... "
;    db "They say there's"
;    db "something good  "
;    db "inside... ...   "
;    db "I better not say"
;    db "anything else   "
;    db "as I'm just a   "
;    db "kid!@"
Dialog123::
    db "Hæ?! Er ikke    "
    db "Marin med deg?  "
    db "Hva skjedde med "
    db "henne?@"
;    db "Hunh?!  Marin's "
;    db "not with you?   "
;    db "What happened to"
;    db "her?@"

Dialog124::
    db "WOW! Det var en "
    db "svær en! Hei,   "
    db "fotofyr! Kan du "
    db "ta et bilde av  "
    db "dette?@"
;    db "WHOA! That's a  "
;    db "big one! Hey,   "
;    db "photo guy! Can  "
;    db "you take a      "
;    db "picture of this?@"

Dialog125::
    db "Jeg føler på meg"
    db "at jeg kommer   "
    db "til å få en stor"
    db "rugg igjen.@"
;    db "I have a        "
;    db "feelin' that    "
;    db "I'll catch a big"
;    db "fish again.@"

Dialog126::
    db "Hvis du ikke    "
    db "forteller noen  "
    db "om meg, skal jeg"
    db "si deg noe nytt-"
    db "ig! Dra til     "
    db "Tromlekysten og "
    db "bruk forstørrel-"
    db "sesglasset, så  "
    db "vil du finne en "
    db "som er som meg.@"
;    db "If you keep me a"
;    db "secret, I'll    "
;    db "tell you some-  "
;    db "thing useful.   "
;    db "Go to Toronbo   "
;    db "Shores, use the "
;    db "magnifying glass"
;    db "and you will    "
;    db "find someone    "
;    db "like me.@"
; litt dårlig oversettelse kanskje 

Dialog127::
    db "Tsk tsk_… Det   "
    db "var synd_…@"
;    db "Tsk tsk...  What"
;    db "a shame...@"

Dialog128::
    db "Å, tusen takk!  "
    db "For en sjenerøs "
    db "person du er!   "
    db "Ah!  Du skal få "
    db "denne i bytte!@"
;    db "Oh thank you!   "
;    db "You are indeed a"
;    db "generous person!"
;    db "Ah!  I will give"
;    db "you this in     "
;    db "return!@"

Dialog129::
    db "Du byttet <yoshi> mot "
    db "<ribbon>! Kanskje du   "
    db "kan bytte sløyfa"
    db "mot noe annet!@"
;    db "You traded your "
;    db "<yoshi> for <ribbon>!  Maybe "
;    db "you can trade   "
;    db "the ribbon for  "
;    db "something else!@"

Dialog12A::
    db "Fordi alle ser  "
    db "så like ut blir "
    db "til og med jeg  "
    db "forvirra noen   "
    db "ganger_…  For-  "
    db "resten, babyen  "
    db "min ønsker seg  "
    db "en Yoshi-dukke. "
    db "Jeg så en i Klo-"
    db "kroken, men jeg "
    db "klarte ikke å få"
    db "tak i den.@"
;    db "Because they all"
;    db "look alike, even"
;    db "I am sometimes  "
;    db "confused. . .   "
;    db "By the way, my  "
;    db "baby wants a    "
;    db "Yoshi Doll.     "
;    db "I saw one at the"
;    db "Trendy Game,    "
;    db "but I couldn't  "
;    db "get it.@"

Dialog12B::
    db "Å! Kan babyen   "
    db "min få den      "
    db "dukken?!        "
    db "    Ja   Nei<ask>"
;    db "Oh!  Will you   "
;    db "give that doll  "
;    db "to my baby?!    "
;    db "    Yes  No<ask>"

Dialog12C::
    db "De er så like at"
    db "til og med jeg  "
    db "blir forvirra   "
    db "noen ganger_…@"
;    db "Because they all"
;    db "look alike, even"
;    db "I am sometimes  "
;    db "confused...     @"

Dialog12D::
    db "Kremt! Jeg må   "
    db "virkelig be deg "
    db "om å ikke ta med"
    db "det grufulle    "
    db "beistet inn hit!"
    db "La det dyret bli"
    db "utenfor, så kan "
    db "jeg snakke med  "
    db "deg. Farvel!@"
;    db "Ahem!  Really, I"
;    db "must insist that"
;    db "you not bring   "
;    db "that awful beast"
;    db "in here!  Leave "
;    db "that creature   "
;    db "outside and then"
;    db "we can talk!    "
;    db "Good Bye!@"

Dialog12E::
    db "Lurer du på hva "
    db "som skjedde med "
    db "spøkelset? Jeg  "
    db "tør vedde på at "
    db "han er lykkelig "
    db "nå, takket være "
    db "deg. Skal vi ta "
    db "et bilde?@"
;    db "You want to know"
;    db "about that      "
;    db "ghost? I'll bet "
;    db "he's happy      "
;    db "thanks to you.  "
;    db "Are you ready   "
;    db "for a picture?@"

Dialog12F::
    db "Å hå hå!        "
    db "Jeg setter vir- "
    db "kelig pris på   "
    db "alt du gjorde   "
    db "for min stakkars"
    db "kjære VovVov!   "
    db "For en snill    "
    db "gutt du er!     "
    db "Hvordan skal jeg"
    db "kunne gjengjelde"
    db "dette? Jeg vet_…"
    db "  SMAAAAAAASK!  "
    db "Du fikk en be-  "
    db "lønning fra     "
    db "Madam MjauMjau_…"
    db "H-h-heldig!@"
;    db "Ho ho ho!       "
;    db "I really appre- "
;    db "ciate what you  "
;    db "did for my poor,"
;    db "precious BowWow!"
;    db "You are such a  "
;    db "nice boy!  How  "
;    db "can I ever repay"
;    db "you?  I know... "
;    db "  SMOOOOOOOCH!  "
;    db "You got a reward"
;    db "from Madam Meow-"
;    db "Meow... ... ... "
;    db "L-l-lucky!@"

Dialog130::
    db "Å hå hå! Min    "
    db "kjære VovVov er "
    db "så stolt av sin "
    db "flotte pels!@"
;    db "Ho ho ho!  My   "
;    db "BowWow is so    "
;    db "proud of his    "
;    db "fine fur coat!@"

Dialog131::
    db "UÆIIIIIIIII!    "
    db "Så forferdelig! "
    db "Min VovVov ble  "
    db "hundenappet av_…"
    db "S-Sk-SKOBOLDER!!"
    db "ÅÅÅH! ÆÆÆÆH!    "
    db "Vær så snill!   "
    db "Noen må hjelpe  "
    db "min stakkars    "
    db "VovVov!!@"
;    db "AIEEEEEEEE!     "
;    db "It's terrrrible!"
;    db "My BowWow was   "
;    db "dognapped by... "
;    db "Mo-mo-MOBLINS!! "
;    db "OHHH!  AHHHH!   "
;    db "Please! Somebody"
;    db "help my poor    "
;    db "BowWow!!@"

Dialog132::
    db "Å, tusen takk!  "
    db "Jeg er så glad  "
    db "for at du tok   "
    db "tilbake babyen  "
    db "min! Er du grei "
    db "og går en tur   "
    db "med ham? Det    "
    db "ville vært til  "
    db "stor hjelp! Kan "
    db "du? Takk!@"
;    db "Oh thank you!   "
;    db "I'm so happy you"
;    db "brought my baby "
;    db "back! Now, would"
;    db "you be a dear   "
;    db "and take him for"
;    db "a walk? It would"
;    db "really help me  "
;    db "out a lot!  You "
;    db "will?!  Thanks!@"

Dialog133::
    db "Vel_… Jeg liker "
    db "å være alene,   "
    db "meg og brevene  "
    db "mine_…          "
    db "Jeg heter Wil-  "
    db "liam! Det eneste"
    db "jeg ikke liker  "
    db "med hobbyen min "
    db "er at jeg aldri "
    db "får noen svar_…@"
;    db "Well... I pretty"
;    db "much stick to   "
;    db "myself, me and  "
;    db "my letters...   "
;    db "My name's Write!"
;    db "The only thing I"
;    db "don't like about"
;    db "my hobby is that"
;    db "I never receive "
;    db "a response...@"

Dialog134::
    db "Hva er dette? Et"
    db "brev til meg?!  "
    db "Jeg er så glad! "
    db "_… Og se! Brevet"
    db "inneholder et   "
    db "fotografi!@"
;    db "What's this?!  A"
;    db "letter for me?! "
;    db "I'm so happy!   "
;    db "...And look! The"
;    db "letter came with"
;    db "a photograph!@"

Dialog135::
    db "Mmm_… Så vakker "
    db "hun er_… Jeg må "
    db "gi deg lønn for "
    db "strevet_… Hmm_… "
    db "Det kan se ut   "
    db "som at alt jeg  "
    db "har er denne    "
    db "feiekosten_… Hva"
    db "Tror du?        "
    db "    Fint Nei_…<ask>"
;    db "Mmm... She's so "
;    db "beautiful...    "
;    db "I must give you "
;    db "something for   "
;    db "your trouble... "
;    db "Hmm...  Well, it"
;    db "looks like all I"
;    db "have is this    "
;    db "broom... how'll "
;    db "that be?        "
;    db "    Fine No...<ask>"

Dialog136::
    db "Du fikk en feie-"
    db "kost som        "
    db "belønning av    "
    db "William! Men hun"
    db "på bildet var jo"
    db "ikke_…@"
;    db "You got a Broom "
;    db "as your reward  "
;    db "from Mr. Write! "
;    db "But that photo  "
;    db "was not of...@"

Dialog137::
    db "Vær så snill!   "
    db "Jeg insisterer, "
    db "ta denne <broom>!     "
    db "    Okei Aldri<ask>"
;    db "Please! I really"
;    db "must insist you "
;    db "have this <broom>!    "
;    db "    Okay No Way<ask>"

Dialog138::
    db "Å boy! Å skrive "
    db "brev er en helt "
    db "fantastisk      "
    db "hobby!@"
;    db "Oh boy!  Letter "
;    db "writing is such "
;    db "a great hobby!@"

Dialog139::
    db "Hallo! Jeg      "
    db "skriver et svar "
    db "til Kristine nå!@"
;    db "Hello!  I'm     "
;    db "writing back to "
;    db "Christine now!@"

Dialog13A::
    db "Vær hilset! Det "
    db "ser kanskje ikke"
    db "sånn ut, men jeg"
    db "pleide å bo på  "
    db "slottet! Alle   "
    db "tjenerne mine   "
    db "gikk berserk og "
    db "jeg ble tvunget "
    db "til å rømme hit "
    db "til villaen     "
    db "min_… Så, du er "
    db "på utkikk etter "
    db "nøkkelen til    "
    db "Ulelesletta? Det"
    db "kan hende jeg   "
    db "kan være be-    "
    db "hjelpelig_… La  "
    db "oss_… Inngå en  "
    db "avtale, hva?    "
    db "Jeg vil at du   "
    db "henter gull-    "
    db "bladet som ble  "
    db "liggende igjen  "
    db "på slottet da   "
    db "jeg rømte_…     "
    db "    Okei Aldri<ask>"
;    db "Salutations!    "
;    db "You wouldn't    "
;    db "know by the look"
;    db "of me, but I    "
;    db "used to live in "
;    db "the castle! My  "
;    db "servants went   "
;    db "berserk and I   "
;    db "was forced to   "
;    db "flee to my      "
;    db "villa... So, you"
;    db "want the key to "
;    db "Ukuku Prairie,  "
;    db "do you?  I may  "
;    db "be able to help "
;    db "you...  Let's   "
;    db "make... a deal, "
;    db "shall we? I want"
;    db "you to retrieve "
;    db "the Golden Leaf "
;    db "I left behind in"
;    db "the castle when "
;    db "I fled...       "
;    db "    Okay No Way<ask>"

Dialog13B::
    db "Fantastisk! For "
    db "å være ærlig, så"
    db "er det fem      "
    db "blader, og jeg  "
    db "vil ha dem alle "
    db "sammen! Okei, du"
    db "kommer til å    "
    db "måtte grave litt"
    db "der borte, så   "
    db "kjøp en spade!  "
    db "Drar du, da?    "
    db "Lykke til!@"
;    db "I am impressed. "
;    db "There are five  "
;    db "leaves in all.  "
;    db "Remember to buy "
;    db "a shovel on your"
;    db "way back.@"
; Jeg baserte min tekst på den originale: 
; Smashing! To
; tell you the
; truth, there are
; five leaves, and
; I want them all!
; Okay, you'll need
; to do some dig-
; ing, so buy a
; shovel! Are you
; off then? Good
; luck!"

Dialog13C::
    db "Nei, nå har jeg "
    db "aldri!  Jeg     "
    db "syntes du så    "
    db "pysete ut, men_…"
    db "La meg være_…   "
    db "Bare stikk!@"
;    db "Well, I never!  "
;    db "I thought you   "
;    db "looked cowardly,"
;    db "but...  Please, "
;    db "leave me... just"
;    db "get out here!@"

Dialog13D::
    db "Ah! Tres Bien!  "
    db "Jeg ser at du   "
    db "har gjenvunnet  "
    db "alle bladene!   "
    db "Flytt nå denne  "
    db "esken, så vil du"
    db "finne belønning-"
    db "en din!@"
;    db "Ahh!  Tres Bien!"
;    db "I see you have  "
;    db "recovered all of"
;    db "the leaves! Now,"
;    db "move this box   "
;    db "and you will    "
;    db "find your       "
;    db "reward!@"
; Skal vi bytte ut “tres bien”? Jeg kom ikke på noe smart.

Dialog13E::
    db "Jeg er deg evig "
    db "takknemlig for  "
    db "at du fikk til- "
    db "bare bladene    "
    db "mine!@"
;    db "I am forever in "
;    db "your debt for   "
;    db "getting my      "
;    db "leaves back!@"

Dialog13F::
    db "Ah!  Bonjour!   "
    db "I rettferdig-   "
    db "hetens navn, og "
    db "for min skyld,  "
    db "må du finne alle"
    db "bladene, #####!@"
;    db "Ah!  Bonjour!   "
;    db "#####, for the  "
;    db "love of justice,"
;    db "and my own sake,"
;    db "you must find   "
;    db "all the leaves!@"

Dialog140::
    db "Eh_… Em_… Ehem_…"
    db "Hvordan skal jeg"
    db "si_… Vær snill  "
    db "og ring_…       "
    db "Utenfor_…       "
    db "Det virker som  "
    db "at gamle Ulrik  "
    db "er en innadvendt"
    db "fyr én til én_…@"
;    db "Er...Uh...Hmm..."
;    db "How to say...   "
;    db "Please call...  "
;    db "Outside...  ... "
;    db "It seems that   "
;    db "old man Ulrira  "
;    db "is a shy guy,   "
;    db "in person...@"

Dialog141::
    db "«RRRING! RRRING!"
    db "Hallo!  Det er  "
    db "meg, Ulrik! Spør"
    db "meg om hva du   "
    db "vil om øya! Hvis"
    db "du går deg vill "
    db "er det bare å   "
    db "ringe! Ha det!  "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hello!  It's me,"
;    db "Ulrira!  Ask me "
;    db "anything about  "
;    db "the island!  If "
;    db "you get lost,   "
;    db "give me a call! "
;    db "Bye! CLICK!'@"

Dialog142::
    db "«RRRING! RRRING!"
    db "Hallo, det er   "
    db "Ulrik!_… Vel,   "
    db "de fleste sko-  "
    db "bolder bor i den"
    db "mystiske skogen,"
    db "men det er også "
    db "noen i hulene i "
    db "Tipptopphøydene."
    db "Håper det var   "
    db "dette du lurte  "
    db "på! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hello, this is  "
;    db "Ulrira! ...Well,"
;    db "most Moblins    "
;    db "live in the Mys-"
;    db "terious Forest, "
;    db "but some live in"
;    db "the caves of Tal"
;    db "Tal Heights...  "
;    db "I hope that is  "
;    db "what you wanted "
;    db "to know! CLICK!'@"

Dialog143::
    db "«RRRING! RRRING!"
    db "Ja, du snakker  "
    db "med Ulrik. De   "
    db "ufordøyelige    "
    db "blomstene i Sym-"
    db "resumpen_… De   "
    db "blomstene er det"
    db "beste VovVov vet"
    db "å spise. Ta ham "
    db "med på tur dit  "
    db "da, vel? KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Yes, this is    "
;    db "Ulrira.  The    "
;    db "Indigestible    "
;    db "Flowers of      "
;    db "Goponga Swamp..."
;    db "Those flowers   "
;    db "are BowWow's    "
;    db "favorite.  Why  "
;    db "don't you take  "
;    db "him for a walk  "
;    db "there?  CLICK!'@"

Dialog144::
    db "«RRRING! RRRING!"
    db "Hei, det er     "
    db "Ulrik! _… Har du"
    db "møtt alle på    "
    db "hele øya? Det er"
    db "en mann ved navn"
    db "Rikard som bor  "
    db "ved Jettegrytene"
    db "sørøst for      "
    db "landsbyen. Du   "
    db "burde stikke in-"
    db "nom! Det er alt "
    db "jeg kan fortelle"
    db "deg nå! Ha det! "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "...Have you met "
;    db "everyone on the "
;    db "island?  There's"
;    db "a man named     "
;    db "Richard who     "
;    db "lives in Pothole"
;    db "Field, southeast"
;    db "of the village. "
;    db "Why not pay him "
;    db "a visit?  That's"
;    db "all I can tell  "
;    db "you for now!    "
;    db "Bye!  CLICK!'@"

Dialog145::
    db "«RRRING! RRRING!"
    db "Gamle Ulrik her!"
    db "_… Liker du     "
    db "bananer? Prøv å "
    db "snakke med folk "
    db "i landsbyen     "
    db "igjen!          "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Old man Ulrira  "
;    db "here! ...Do you "
;    db "like bananas?   "
;    db "Try talking to  "
;    db "people in the   "
;    db "village again!  "
;    db "Bye!  CLICK!'@"

Dialog146::
    db "«RRRING! RRRING!"
    db "Ulrik her! Vet  "
    db "du, det er et   "
    db "bibliotek i     "
    db "landsbyen som   "
    db "har masse infor-"
    db "masjon til deg! "
    db "Snakkes!        "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira speaking!"
;    db "You know, there "
;    db "is a library in "
;    db "the village that"
;    db "might have some "
;    db "good information"
;    db "for you!  Talk  "
;    db "to you later!   "
;    db "CLICK!'@"

Dialog147::
    db "«RRRING! RRRING!"
    db "Ja, det er      "
    db "Ulrik! Sier du  "
    db "at du ikke har  "
    db "funnet alle fem "
    db "gullbladene? Du "
    db "får spørre kråka"
    db "på slottet. Jeg "
    db "tipper han kan  "
    db "hjelpe. Ha det! "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "You say you     "
;    db "haven't found   "
;    db "all five Golden "
;    db "Leaves? Go ask  "
;    db "the crow at the "
;    db "castle. I'm sure"
;    db "he can help you."
;    db "Bye!            "
;    db "CLICK!'@"

Dialog148::
    db "«RRRING! RRRING!"
    db "Ulrik her!_…    "
    db "Spade_… Har du  "
    db "kjøpt en spade? "
    db "Kanskje du kan  "
    db "finne noe hvis  "
    db "du graver her og"
    db "der! Ha det!    "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira here! ..."
;    db "Shovel...  Did  "
;    db "you purchase a  "
;    db "shovel?  You may"
;    db "find something  "
;    db "if you dig here "
;    db "and there!  Bye!"
;    db "CLICK!'@"

Dialog149::
    db "«RRRING! RRRING!"
    db "Ja, det er      "
    db "Ulrik! Hula på  "
    db "Ulelesletta er  "
    db "nøkkelen! Ja,   "
    db "jeg mener nøk-  "
    db "kelhula, eller  "
    db "Nøkkelkjelleren,"
    db "da! Ha det!     "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "The cave in the "
;    db "Ukuku Prairie is"
;    db "the key!  Yes, I"
;    db "mean the key    "
;    db "cave, no pun    "
;    db "intended!  Bye! "
;    db "CLICK!'@"

Dialog14A::
    db "«RRRING! RRRING!"
    db "Hei, dette er   "
    db "Ulrik! Sørøst på"
    db "øya, i Yahara-  "
    db "ørkenen, finner "
    db "du noe som heter"
    db "Ulkenøkkelen.   "
    db "Hmmm_… Hvor mye "
    db "tydeligere må   "
    db "jeg si det?     "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, this is     "
;    db "Ulrira!  In the "
;    db "Yarna Desert,   "
;    db "which is located"
;    db "in the southeast"
;    db "of the island,  "
;    db "you will find   "
;    db "something called"
;    db "the Angler Key. "
;    db "Hmmm... How much"
;    db "more obvious do "
;    db "I have to be?   "
;    db "Bye! CLICK!'@"

Dialog14B::
    db "«RRRING! RRRING!"
    db "Dette er Ulrik! "
    db "Nå hjemsøkes du "
    db "av et spøkelse? "
    db "Vel, hva med å  "
    db "ta ham med dit  "
    db "han har lyst til"
    db "å dra?          "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "This is Ulrira! "
;    db "Now you're being"
;    db "haunted by a    "
;    db "ghost?! Well,   "
;    db "how about taking"
;    db "him where he    "
;    db "wants to go?    "
;    db "Bye! CLICK!'@"

Dialog14C::
    db "«RRRING! RRRING!"
    db "Hei, det er     "
    db "Ulrik! Er mallen"
    db "sin munn vid-   "
    db "åpen? Det høres "
    db "ut som et flott "
    db "sted å dykke!   "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "The Catfish's   "
;    db "mouth is wide   "
;    db "open?  It sounds"
;    db "like a great    "
;    db "place to dive!  "
;    db "Bye!  CLICK!'@"

Dialog14D::
    db "«RRRING! RRRING!"
    db "Ulrik her!_… _… "
    db "Har du vært i   "
    db "Ansiktstempelet?"
    db "Det ligger nord "
    db "for Snutebu. Det"
    db "er en veldig    "
    db "interessant     "
    db "ruin_… KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ulrira here! ..."
;    db "Have you been to"
;    db "the Face Shrine?"
;    db "It is north of  "
;    db "Animal Village. "
;    db "That is a very  "
;    db "interesting     "
;    db "ruin... CLICK!'@"

Dialog14E::
    db "«RRRING! RRRING!"
    db "Hei, det er     "
    db "Ulrik! Har du   "
    db "hørt om Måsebus "
    db "flygende hane?  "
    db "I de gode, gamle"
    db "dager pleide den"
    db "å la oss fly når"
    db "vi holdt den    "
    db "over hodet_… Nå "
    db "ligger den      "
    db "begravd under   "
    db "værhanen_… Var  "
    db "det nyttig for  "
    db "deg? Håper det! "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "Have you heard  "
;    db "of the Flying   "
;    db "Rooster of Mabe "
;    db "Village?  In the"
;    db "good old days,  "
;    db "it used to give "
;    db "us rides if we  "
;    db "held it above   "
;    db "our heads... Now"
;    db "it is lying     "
;    db "under the       "
;    db "Weathercock...  "
;    db "Is that useful  "
;    db "for you?  I hope"
;    db "so! Bye! CLICK!'@"

Dialog14F::
    db "«RRRING! RRRING!"
    db "Hei, det er     "
    db "Ulrik! Er hodet "
    db "til skilpadden  "
    db "i veien? Pust   "
    db "litt liv i den, "
    db "så beveger den  "
    db "seg! Det er helt"
    db "sant! Sant!     "
    db "Ha det! KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Hi, it's Ulrira!"
;    db "The head of the "
;    db "turtle is in    "
;    db "your way?  Put  "
;    db "life into it and"
;    db "it will move!   "
;    db "It's true! True!"
;    db "Bye!  CLICK!'@"

Dialog150::
    db "   _… SUMP_…    "
    db "En sti åpner seg"
    db "i anemonene_…@" 
;    db "   ...SWAMP...  "
;    db " A path opens..."
;    db "in the blooms...@"

Dialog151::
    db "  _… SLETTE_…   "
    db "  _… SLETTE_…   "
    db "    Slettene    "
    db "    venter_…@"
;    db "  ...PRAIRIE... "
;    db "  ...PRAIRIE... "
;    db " The Prairie is "
;    db "     waiting...@"

Dialog152::
    db "   _… FOSS_…    "
    db "Det er skjult i "
    db "fossen_…@"
;    db "...WATERFALL... "
;    db "It is hidden in "
;    db "the waterfall...@"

Dialog153::
    db "   _… BUKT_…    "
    db "Veien din går   "
    db "inn i bukta_…@"
;    db "    ...BAY...   "
;    db "Your road goes  "
;    db "into the bay... @"

Dialog154::
    db "  _… TEMPEL_…   "
    db "En av øyas      "
    db "hemmeligheter i "
    db "tempelet_…@"
;    db "   ...SHRINE... "
;    db "An island secret"
;    db "in the shrine...@"

Dialog155::
    db "  _… FJELL_…    "
    db "Noe kaller      "
    db "_… fra fjellet_…@"
;    db " ...MOUNTAIN... "
;    db "Something calls "
;    db "  ...from the   "
;    db "  mountains...@"

Dialog156::
    db " _… LEIRGAUK_…  "
    db "Leirgaukens     "
    db "musikk fører_…@"
;    db "  ...OCARINA... "
;    db "The music of the"
;    db "Ocarina leads...@"

Dialog157::
    db "   _… EGG_…     "
    db "Egget på fjellet"
    db "kaller på deg!@"
;    db "    ...EGG....  "
;    db "The Egg on the  "
;    db "mountain calls!@"

Dialog158::
Dialog159::
    db "Da får DU feie  "
    db "denne øya!@"
;    db "Then YOU sweep  "
;    db "the island!@"

Dialog15A::
    db "JIPPI! Jeg har  "
    db "det bra, og du?!@"
;    db "YAHOO!   I'm    "
;    db "fine, and you?!@"

Dialog15B::
    db "JIPPI! Jeg jobb-"
    db "et for hardt og "
    db "nå er kosten min"
    db "slitt ned til   " 
    db "skaftet!@"
;    db "YAHOO!  I worked"
;    db "too hard and now"
;    db "my broom is worn"
;    db "to the handle!@"

Dialog15C::
    db "JIPPI! JIPPI!   "
    db "En ny kost?! Til"
    db "meg? Det er     "
    db "det, ikke sant?!"
    db "    Ja   Nei<ask>"
;    db "YAHOO!  YAHOO!  "
;    db "A new broom?!   "
;    db "For me?  It is, "
;    db "isn't it?!      "
;    db "    Yes  No<ask>"

Dialog15D::
    db "Okei! Da kan du "
    db "få denne fiske- "
    db "kroken jeg fant "
    db "da jeg feide ved"
    db "elvebredden!@"
;    db "Okay!  In return"
;    db "you can have    "
;    db "this fishing    "
;    db "hook I found    "
;    db "when I swept by "
;    db "the river bank!@"

Dialog15E::
    db "Du byttet <broom> mot "
    db "fiskekroken <fishhook>!  "
    db "Hva kommer      "
    db "fiskekroken til "
    db "å bli?@"
;    db "You exchanged <broom> "
;    db "for the fishing "
;    db "hook <fishhook>!  What   "
;    db "will the fishing"
;    db "hook become?@"

Dialog15F::
    db "JIPPI! En ny    "
    db "kost! Supert!@"
;    db "YAHOO!  A new   "
;    db "broom!  Superb!@"

Dialog160::
    db "Jul-i-ius! Hva?!"
    db "Greit, kjøter!  " 
    db "La oss slåss!!@"
;    db "Kiiiki!  What?! "
;    db "All right, mutt!"
;    db "Let's battle!!@"

Dialog161::
    db "Oo! Ooo! Aa! Aa!"
    db "Banan! Apen     "
    db "Julius! Sulten! "
    db "Apen Julius!@"
;    db "Chi-kiita! Chi- "
;    db "kiita!  Kiki the"
;    db "monkey!  Hungry!"
;    db "Kiki the monkey!@"

Dialog162::
    db "    <bananas>!    <bananas>!    "
    db "Oo! Ooo! Julius!"
    db "Aper! Kom! Be-  "
    db "lønn ham! Aaa!@"
;    db "    <bananas>!    <bananas>!    "
;    db "Oooh! Ooh! Kiki!"
;    db "Monkeys!  Come! "
;    db "Repay him! Kiki!@"

Dialog163::
    db "Apestreker!     "
    db "Ferdig! Ha det! "
    db "Ooo! Julius!@"
;    db "Monkey business!"
;    db "Done!  Bye bye! "
;    db "Oooh!  Kiki!@"

Dialog164::
    db "Du fant en pinne"
    db "en av apene la  "
    db "igjen_… Du tar  "
    db "den!@"
;    db "You found a     "
;    db "stick a monkey  "
;    db "left behind...  "
;    db "You take it!@"

Dialog165::
    db "    <bananas>!    <bananas>!    "
    db "  Ooo!  Ooo!    "
    db " Gi til Julius?!"
    db "    Ja   Nei!<ask>"
;    db "    <bananas>!    <bananas>!    "
;    db "  Oooh!  Oooh!  "
;    db " Give to Kiki!? "
;    db "    Yes  No!<ask>"

Dialog166::
    db "Du har virkelig "
    db "ingen anelse om "
    db "hvordan man     "
    db "snakker til en  "
    db "dame, har du    "
    db "vel? Du skulle  "
    db "hatt med deg    "
    db "blomster eller  "
    db "noe, da ville   "
    db "jeg vært mer    "
    db "tilbøyelig til å"
    db "snakke med deg_…"
    db "I mitt tilfelle "
    db "ville hibiskus  " 
    db "vært det beste_…@"
;    db "You don't know  "
;    db "the proper      "
;    db "etiquette when  "
;    db "dealing with a  "
;    db "lady, do you?   "
;    db "You should have "
;    db "brought flowers "
;    db "or something,   "
;    db "then I might be "
;    db "more inclined to"
;    db "talk with you..."
;    db "Oh yes, in my   "
;    db "case, hibiscus  "
;    db "are best...@"

Dialog167::
    db "Å, du tok med en"
    db "hibiskus til    "
    db "meg! Så søtt!   "
    db "Vel, siden du er"
    db "slik en sjarmør,"
    db "kan du gjøre meg"
    db "en tjeneste? Vil"
    db "du høre?        "
    db "    Ja   Nei<ask>"
;    db "Oh, you brought "
;    db "me a hibiscus!  "
;    db "How sweet! Well,"
;    db "since you are   "
;    db "such a gentleman"
;    db "I have a request"
;    db "to make of you. "
;    db "Will you listen?"
;    db "    Yes  No<ask>"

Dialog168::
    db "Jeg trenger å få"
    db "levert dette    "
    db "brevet til en   "
    db "William som bor "
    db "ved kanten av   "
    db "den mystiske    "
    db "skogen, er du   "
    db "snill!@"
;    db "I would like you"
;    db "to take this    "
;    db "letter to a Mr. "
;    db "Write who lives "
;    db "on the border of"
;    db "the Mysterious  "
;    db "Forest, please!@"

Dialog169::
    db "_… Jaha? Og jeg "
    db "som trodde du   "
    db "var en galant   "
    db "herre_…@"
;    db "...Is that so?  "
;    db "And I thought   "
;    db "you were a      "
;    db "gentleman...@"

Dialog16A::
    db "Du byttet <flower2> mot "
    db "en geits brev <letter>!"
    db "_… Kjempebra!?@"
;    db "You traded <flower2> for"
;    db "a goat's letter "
;    db "<letter>!  ...Great!?@"

Dialog16B::
    db "Vet du, noen    "
    db "ganger klarer   "
    db "jeg ikke å mot- "
    db "stå fristelsen  "
    db "av å spise en   "
    db "deilig papirbit,"
    db "selv om det er  "
    db "et brev til min "
    db "kjære William_… "
    db "Så flaut!@"
;    db "You know, some- "
;    db "times I can't   "
;    db "help eating a   "
;    db "delicious piece "
;    db "of paper, even  "
;    db "if it's a letter"
;    db "to my darling   "
;    db "Mr. Write... How"
;    db "embarrassing!@"

Dialog16C::
    db "Du reddet Vov-  "
    db "Vov! For et gru-"
    db "fullt beist!@"
;    db "You've saved    "
;    db "BowWow!  What a "
;    db "fearsome beast!@"

Dialog16D::
    db "Wow! Hanen har  "
    db "gjenoppstått!   "
    db "Han virker      "
    db "veldig vennlig!@"
;    db "Wow! The Rooster"
;    db "has recovered!  "
;    db "He seems very   "
;    db "friendly!@"

Dialog16E::
    db "«RRRING! RRRING!"
    db "Ja, det er      "
    db "Ulrik! Kona mi  "
    db "dro til Snutebu "
    db "og lot meg være "
    db "igjen alene. Kan"
    db "du si at hun må "
    db "komme hjem så   "
    db "fort hun er     "
    db "ferdig med å    "
    db "feie?           "
    db "Ha det!         "
    db "KLIKK!»@"
;    db "'BRRING! BRRING!"
;    db "Ya, it's Ulrira!"
;    db "My wife went to "
;    db "the Animal      "
;    db "Village and left"
;    db "me all alone.   "
;    db "Can you tell    "
;    db "her to come home"
;    db "as soon as she  "
;    db "is done         "
;    db "cleaning?       "
;    db "Bye!            "
;    db "CLICK!'@"

Dialog16F::
    db "Bestemor er ikke"
    db "her. Hun er i   "
    db "Snutebu. Det var"
    db "dét bestefar    "
    db "Ulrik sa på     "
    db "telefonen!@"
;    db "Grandma's not   "
;    db "here. She's in  "
;    db "the Animal      "
;    db "Village. That's "
;    db "what Grandpa    "
;    db "Ulrira said on  "
;    db "the phone!@"

Dialog177::
Dialog170::
    db "Jepp, Fartein   "
    db "gikk seg bort,  "
    db "akkurat som han "
    db "sa! Nå er jeg   "
    db "så skrubbsulten "
    db "at jeg ikke kan "
    db "røre meg! Har du"
    db "noe proviant?   "
    db "    Ja   Niks<ask>"
;    db "Yep, Papahl got "
;    db "lost, just like "
;    db "he said!  Now, I"
;    db "am so famished I"
;    db "can't move!  Can"
;    db "you give me some"
;    db "vittles?        "
;    db "    Yes  Nope<ask>"

Dialog171::
    db "Du er en iskald "
    db "kis_…@"
;    db "You're one cold "
;    db "hombre...@"

Dialog172::
    db "Denne <pineapple> er helt "
    db "nydelig! Jeg    "
    db "skal spise <pineapple>    "
    db "med én gang!    "
    db " Bon Appétit!@"
; Det er visst aksent over e-en på fransk, skal vi ha den med? 
;    db "This <pineapple> is so    "
;    db "delicious!  I'm "
;    db "going to eat the"
;    db "<pineapple> right now!    "
;    db " Bon Appetit!@"

Dialog173::
    db "AH! Dette er    "
    db "ikke ment som en"
    db "belønning_… Her,"
    db "ta denne <flower2>! Det "
    db "Det er en       "
    db "hibiskus!@"
;    db "AH!  This isn't "
;    db "meant to be a   "
;    db "reward...  Here,"
;    db "take this <flower2>!    "
;    db "It's a hibiscus!@"

Dialog174::
    db "Du byttet <pineapple> mot "
    db "en <flower2>!@"
;    db "You traded the <pineapple>"
;    db "for the <flower2>!@"

Dialog175::
    db "Nydelig! Nam!   "
    db "Nå er jeg full  "
    db "av energi!@"
;    db "Delicious!  Yum!"
;    db "I'm filled with "
;    db "energy, now!@"

Dialog176::
    db "Nok en gang,    "
    db "tusen takk!@"
;    db "I've got to say,"
;    db "thanks again!@"

Dialog178::
    db "Hun har opplevd "
    db "en forferdelig  "
    db "tragedie i huset"
    db "over gata! Det  "
    db "er helt grusomt,"
    db "og alt jeg kan  "
    db "gjøre er å feie!@"
;    db "She's had an    "
;    db "awful tragedy   "
;    db "in the house    "
;    db "across the way! "
;    db "It's just awful,"
;    db "and all I can do"
;    db "is sweep!@"

Dialog179::
    db "Jeg er dette    "
    db "husets sjel. Jeg"
    db "har ventet på en"
    db "som kunne over- "
    db "vinne mørket.   "
    db "Finn alle de    "
    db "hemmelige skjel-"
    db "lene og gå gjen-"
    db "nom åpningen for"
    db "å få det        "
    db "ultimate sverd!@"
;    db "I am the spirit "
;    db "of the mansion. "
;    db "I have been     "
;    db "waiting for     "
;    db "someone to      "
;    db "overcome the    "
;    db "darkness. Find  "
;    db "all the secret  "
;    db "shells and go   "
;    db "through the     "
;    db "gate to receive "
;    db "the ultimate    "
;    db "sword!@"
; Forslag til synonymer for «ultimate» tas imot med thx

Dialog17A::
    db "Hmmm. Ingenting "
    db "skjedde. Du har "
    db "sikkert ikke nok"
    db "skjell.@"
;    db "Hmmm. No        "
;    db "response. You   "
;    db "must not have   "
;    db "enough shells.@"

Dialog17B::
    db "Min jobb her er "
    db "fullført.@"
;    db "My job here     "
;    db "is finished.@"

Dialog17C::
;    db "Hei du! Har du  " Kommenterer ut denne, for Bank1C blir full og denne dialogen brukes ikke i spillet
;    db "vært i foto-    "
;    db "butikken i Tipp-"
;    db "topphøydene?    "
;    db "Ungdommer liker "
;    db "å gå dit og ta  "
;    db "bilder av seg   "
;    db "selv. Virker    "
;    db "litt rart, spør "
;    db "du meg.@"
;    db "Hey you! Have   "
;    db "you been to the "
;    db "Camera Shop in  "
;    db "Tal Tal Heights?"
;    db "Iyoung people   "
;    db " like to go ther"
;    db "eand take       "
;    db " pictures of    "
;    db " themselves.    "
;    db " Seems kinda    "
;    db " funny to me.@"

Dialog17D::
    db "Kom inn og få en"
    db "suvenir i form  "
    db "av et bilde!@"
;    db "Step right up   "
;    db "and get your    "
;    db "souvenir photo!@"

Dialog17E::
    db "Godt jobba! Bruk"
    db "det på fiendene "
    db "dine og se hva  "
    db "som skjer. Hvis "
    db "du går tom, er  "
    db "det bare å dra  "
    db "til skogen og   "
    db "plukke mer sopp,"
    db "så skal jeg lage"
    db "mer.@"
;    db "Good job!       "
;    db "Use it on your  "
;    db "enemies and see "
;    db "what happens.   "
;    db "If you run out, "
;    db "go to the for-  "
;    db "est, pick some  "
;    db "mushrooms, and  "
;    db "I will make you "
;    db "more.@"

Dialog17F::
    db ". . . .! Jeg kan"
    db "ikke røre meg!  "
    db "Men det går bra."
    db "Det lille       "
    db "sverdet ditt kan"
    db "ikke knuse denne"
    db "flaska!@" 
;    db ". . . .! I can't"
;    db "move! But I am  "
;    db "still all right."
;    db "Your little     "
;    db "sword won't     "
;    db "break this      "
;    db "bottle!@"

Dialog180::
    db "Sminke! Smykker!"
    db "Kjoler! Jeg vil "
    db "ha alt sammen!  "
    db "Sukk_… Og noen  "
    db "aksessoarer     "
    db "hadde vært      "
    db "fint_…@"
;    db "Make-up! Jewels!"
;    db "Dresses!  I want"
;    db "it all!  Sigh..."
;    db "And some new    "
;    db "accessories     "
;    db "would be nice...@"

Dialog181::
    db "Sminke! Smykker!"
    db "Kjoler! Jeg vil "
    db "ha alt sammen!  "
    db "Sukk_… Og noen  "
    db "aksessoarer     "
    db "hadde vært      "
    db "fint_…          "
    db "Å! Den sløyfa!  "
    db "Jeg trenger den!"
    db "Vil du bytte den"
    db "mot hundemat?   "
    db "    Ja   Nei!<ask>"
;    db "Make-up! Jewels!"
;    db "Dresses!  I want"
;    db "it all!  Sigh..."
;    db "And some new    "
;    db "accessories     "
;    db "would be nice..."
;    db "Oh! That Ribbon!"
;    db "I need it!  Will"
;    db "you trade for my"
;    db "dog food?       "
;    db "    Yes  No!<ask>"

Dialog182::
    db "Du byttet <ribbon> mot "
    db "<dogfood>! Den er full  "
    db "av saftig kjøtt!@"
;    db "You exchanged <ribbon> "
;    db "for <dogfood>! It's full"
;    db "of juicy beef!@"

Dialog183::
    db "Heldig! Takk!   "
    db "Vel, her har du "
    db "<dogfood>!@"
;    db "Lucky!  Thanks! "
;    db "Well, here's    "
;    db "your <dogfood>!@"

Dialog184::
    db "Hæ?! Jeg kan    "
    db "ikke tro det! Du"
    db "er så slem!!@"
;    db "Eh?!  I can't   "
;    db "believe it!  You"
;    db "are the worst!!@"

Dialog185::
    db "Jeg er Mons,    "
    db "månefiskens     "
    db "barn! Har du en "
    db "leirgauk?       "
    db "    Ja   Nei<ask>"
;    db "I am Manbo,     "
;    db "child of the Sun"
;    db "Fish!  Have you "
;    db "got an Ocarina? "
;    db "    Yes  No<ask>"

Dialog186::
    db "Nei vel_… Blubb "
    db "Blubb Blupp!@"
;    db "Very well...    "
;    db "Glub Blub Bloop!@"

Dialog187::
    db "Ahaha! Da kan   "
    db "jeg lære deg    "
    db "sangen min!     "
    db "Blupp!@"
;    db "Ahaha!  Then I  "
;    db "can teach you my"
;    db "song! Bloop!@"

Dialog188::
    db "Du lærte Mons'  "
    db "Mambo! Du burde "
    db "spille den når  "
    db "du kommer deg   "
    db "opp av vannet!@"
;    db "You've learned  "
;    db "Manbo's Mambo!  "
;    db "When you get out"
;    db "of the water,   "
;    db "play it!@"

Dialog189::
    db "Jeg er Mons,    "
    db "månefiskens     "
    db "barn! Når du    "
    db "spiller mamboen "
    db "min kan du tele-"
    db "portere til     "
    db "Mons' pytt! Prøv"
    db " å spille denne "
    db "melodien i      "
    db "fangehull også! "
    db "Cha-cha-cha!@"
;    db "I am Manbo,     "
;    db "child of the Sun"
;    db "Fish!  When you "
;    db "play my Mambo,  "
;    db "you can warp to "
;    db "Manbo Pond!  Try"
;    db "this tune in the"
;    db "dungeons, too!  "
;    db "Cha-cha-cha!@"

Dialog18A::
    db "Aha_… Du har    "
    db "ingen leirgauk, "
    db "så_… Blubb!@"
;    db "Aha... You don't"
;    db "have an Ocarina,"
;    db "so...Glub glub!@"

Dialog18B::
    db "Kyllinger nå til"
    db "dags har ikke   "
    db "kampviljen de   "
    db "pleide å ha! I  "
    db "gamle dager     "
    db "kunne de fly,   "
    db "flaks flaks! Men"
    db "nå, se her!     "
    db "Klukk klukk!@"
;    db "Chickens these  "
;    db "days don't have "
;    db "the fighting    "
;    db "spirit they used"
;    db "to!  In the old "
;    db "days, they could"
;    db "fly, flap flap! "
;    db "But now, see?   "
;    db "Cluck cluck!@"

Dialog18C::
    db "Wow!  Utrolig!  "
    db "Den hanen der   "
    db "flyr faktisk!   "
    db "Det er akkurat  "
    db "som jeg sa, hæ? "
    db "Har du prøvd å  "
    db "holde ham over  "
    db "hodet? Klukk    "
    db "klukk!@"
;    db "Wow!  Amazing!  "
;    db "That rooster is "
;    db "actually flying!"
;    db "It's just like I"
;    db "said, eh?  Have "
;    db "you tried to    "
;    db "hold him over   "
;    db "your head? Cluck"
;    db "Cluck!@"

Dialog18D::
    db "Åååå!  Endelig! "
    db "Denne flygende  "
    db "hanen er den    "
    db "beste!@"
;    db "Wooo!  Finally! "
;    db "This flying     "
;    db "rooster is the  "
;    db "greatest!@"

Dialog18E::
    db " Her hviler Den "
    db " flygende hane@"
;    db " Here Sleeps The"
;    db " Flying Rooster@"

Dialog18F::
    db "Er det den hav- "
    db "frushell? Jeg   "
    db "kan ikke bruke  "
    db "den nå. Jeg må  "
    db "jobbe med denne "
    db "tegning. Du kan "
    db "gå og gjøre     "
    db "fertig den      "
    db "shtatue for meg.@"
;    db "Iz zat zee      "
;    db "Mermaid scale?  "
;    db "I can't use it  "
;    db "now. I have to  "
;    db "werk on zis     "
;    db "drawing. You    "
;    db "should go finish"
;    db "zee mermaid     "
;    db "statue for me.@"
